package ghost

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

func (h *Handler) HandleProvisionDatabase(w http.ResponseWriter, r *http.Request) {
	var req ProvisionDatabaseRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "INVALID_REQUEST", "invalid request body")
		return
	}

	sql := h.generateSQLSchema(req.Schema)
	migration := fmt.Sprintf("-- Auto-generated by Ghost Mode\n-- Generated at: %s\n\n%s", time.Now().Format(time.RFC3339), sql)

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"ok":        true,
		"sql":       sql,
		"migration": migration,
		"artifacts": []Artifact{
			{Name: "schema.sql", Type: "schema", Path: "/ghost/artifacts/schema.sql", Size: len(sql)},
		},
	})
}

func (h *Handler) generateSQLSchema(schemaJSON string) string {
	_ = schemaJSON
	tables := []string{
		`CREATE TABLE IF NOT EXISTS users (
			id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			email VARCHAR(255) UNIQUE NOT NULL,
			password_hash VARCHAR(255) NOT NULL,
			created_at TIMESTAMPTZ DEFAULT NOW(),
			updated_at TIMESTAMPTZ DEFAULT NOW()
		);`,
		`CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);`,
		`CREATE TABLE IF NOT EXISTS sessions (
			id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			user_id UUID REFERENCES users(id) ON DELETE CASCADE,
			token VARCHAR(512) NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			created_at TIMESTAMPTZ DEFAULT NOW()
		);`,
		`CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);`,
	}

	sql := "--- Ghost Mode Auto-generated Schema\n"
	for _, t := range tables {
		sql += t + "\n\n"
	}
	return sql
}

func (h *Handler) HandleProvisionAPI(w http.ResponseWriter, r *http.Request) {
	var req ProvisionAPIRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "INVALID_REQUEST", "invalid request body")
		return
	}

	code := h.generateAPIHandlers(req.Spec)

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"ok":       true,
		"handlers": code,
		"artifacts": []Artifact{
			{Name: "handlers.go", Type: "code", Path: "/ghost/artifacts/handlers.go", Size: len(code)},
		},
	})
}

func (h *Handler) generateAPIHandlers(spec string) string {
	_ = spec
	return `// Auto-generated by Ghost Mode
package api

import "net/http"

func RegisterRoutes(r *mux.Router) {
	// Auth routes
	r.HandleFunc("/auth/register", HandleRegister).Methods("POST")
	r.HandleFunc("/auth/login", HandleLogin).Methods("POST")

	// User routes
	r.HandleFunc("/users/me", HandleGetMe).Methods("GET")
	r.HandleFunc("/users/me", HandleUpdateMe).Methods("PUT")

	// Health check
	r.HandleFunc("/health", HandleHealth).Methods("GET")
}
`
}

func (h *Handler) HandleProvisionDocker(w http.ResponseWriter, r *http.Request) {
	var req ProvisionDockerRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "INVALID_REQUEST", "invalid request body")
		return
	}

	dockerCompose := h.generateDockerCompose(req.Services)

	writeJSON(w, http.StatusOK, map[string]interface{}{
		"ok":      true,
		"compose": dockerCompose,
		"artifacts": []Artifact{
			{Name: "docker-compose.yml", Type: "config", Path: "/ghost/artifacts/docker-compose.yml", Size: len(dockerCompose)},
		},
	})
}

func (h *Handler) generateDockerCompose(services []DockerServiceSpec) string {
	result := "version: '3.9'\n\nservices:\n"
	for _, svc := range services {
		result += fmt.Sprintf("  %s:\n", svc.Name)
		result += fmt.Sprintf("    image: %s\n", svc.Image)
		if len(svc.Ports) > 0 {
			result += "    ports:\n"
			for _, p := range svc.Ports {
				result += fmt.Sprintf("      - \"%s\"\n", p)
			}
		}
		if len(svc.Env) > 0 {
			result += "    environment:\n"
			for k, v := range svc.Env {
				result += fmt.Sprintf("      %s: \"%s\"\n", k, v)
			}
		}
		if len(svc.Volumes) > 0 {
			result += "    volumes:\n"
			for _, v := range svc.Volumes {
				result += fmt.Sprintf("      - %s\n", v)
			}
		}
		if len(svc.DependsOn) > 0 {
			result += "    depends_on:\n"
			for _, d := range svc.DependsOn {
				result += fmt.Sprintf("      - %s\n", d)
			}
		}
		result += "\n"
	}
	return result
}
