// Package autoreadme generates README documentation for registry functions.
// It creates human-friendly markdown from function metadata, schemas, and runtime config.
package autoreadme

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Generator holds configuration for README generation.
type Generator struct {
	BaseURL string // e.g. https://api.functionfly.com
}

// FunctionMeta holds the metadata needed to generate a README.
type FunctionMeta struct {
	Author           string
	Name             string
	Title            string
	Description      string
	Version          string
	Runtime          string
	TimeoutMs        int
	MemoryMB         int
	Deterministic    bool
	SideEffects      string
	Idempotent       bool
	CacheTTL         int
	Capabilities     []string
	Category         string
	Tags             []string
	InputSchema      map[string]interface{}
	OutputSchema     map[string]interface{}
	InputExample     interface{}
	OutputExample    interface{}
	TrustScore       float64
	PublishedAt      time.Time
	Downloads        int64
	FunctionURL      string
	OwnerAvatarURL   string
	Stars            int
	OpenIssues       int
	ClosedIssues     int
	LastCommitDate   time.Time
	LastReleaseDate  time.Time
	ReleaseVersion   string
	CoveragePercent  float64
}

// NewGenerator creates a new README generator.
func NewGenerator(baseURL string) *Generator {
	if baseURL == "" {
		baseURL = "https://api.functionfly.com"
	}
	return &Generator{BaseURL: strings.TrimSuffix(baseURL, "/")}
}

// Generate creates a markdown README for the given function metadata.
func (g *Generator) Generate(meta FunctionMeta) string {
	var b bytes.Buffer

	// Title & description
	b.WriteString(fmt.Sprintf("# %s\n\n", firstNonEmpty(meta.Title, meta.Name)))
	if meta.Description != "" {
		b.WriteString(fmt.Sprintf("%s\n\n", meta.Description))
	}

	// Badges
	b.WriteString(g.badges(meta))
	b.WriteString("\n")

	// Quick Actions (for function READMEs)
	b.WriteString("## 🚀 Quick Deploy\n\n")
	b.WriteString(fmt.Sprintf("```bash\nffly deploy %s/%s\n```\n\n", meta.Author, meta.Name))
	b.WriteString("## 🔑 Common Tasks\n\n")
	b.WriteString(fmt.Sprintf("- [Invoke this function](%s)\n", g.functionInvokeURL(meta)))
	b.WriteString("- [View invocation logs](https://docs.functionfly.com/logs)\n")
	b.WriteString("- [Set up triggers](https://docs.functionfly.com/triggers)\n")
	b.WriteString("- [Monitor health](https://docs.functionfly.com/monitoring)\n\n")

	// Overview
	b.WriteString("## Overview\n\n")
	b.WriteString(g.overview(meta))
	b.WriteString("\n")

	// Input
	if len(meta.InputSchema) > 0 || meta.InputExample != nil {
		b.WriteString("## Input\n\n")
		if meta.InputSchema != nil {
			b.WriteString("### Schema\n\n")
			b.WriteString(g.codeBlock(meta.InputSchema, "json"))
			b.WriteString("\n")
		}
		if meta.InputExample != nil {
			b.WriteString("### Example\n\n")
			b.WriteString(g.codeBlock(meta.InputExample, "json"))
			b.WriteString("\n")
		}
	}

	// Output
	if len(meta.OutputSchema) > 0 || meta.OutputExample != nil {
		b.WriteString("## Output\n\n")
		if meta.OutputSchema != nil {
			b.WriteString("### Schema\n\n")
			b.WriteString(g.codeBlock(meta.OutputSchema, "json"))
			b.WriteString("\n")
		}
		if meta.OutputExample != nil {
			b.WriteString("### Example\n\n")
			b.WriteString(g.codeBlock(meta.OutputExample, "json"))
			b.WriteString("\n")
		}
	}

	// Runtime Configuration
	b.WriteString("## Runtime Configuration\n\n")
	b.WriteString(g.runtimeTable(meta))
	b.WriteString("\n")

	// Capabilities
	if len(meta.Capabilities) > 0 {
		b.WriteString("## Capabilities\n\n")
		for _, cap := range meta.Capabilities {
			b.WriteString(fmt.Sprintf("- %s\n", humanizeCapability(cap)))
		}
		b.WriteString("\n")
	}

	// Tags
	if len(meta.Tags) > 0 {
		b.WriteString("## Tags\n\n")
		for _, tag := range meta.Tags {
			b.WriteString(fmt.Sprintf("- `%s`\n", tag))
		}
		b.WriteString("\n")
	}

	// Example Usage
	b.WriteString("## Example Usage\n\n")
	b.WriteString(g.exampleUsage(meta))
	b.WriteString("\n")

	// Trust & Verification
	b.WriteString("## Trust & Verification\n\n")
	b.WriteString(g.trustSection(meta))
	b.WriteString("\n")

	// Footer
	b.WriteString("---\n\n")
	b.WriteString(fmt.Sprintf("*Generated by FunctionFly on %s*\n", meta.PublishedAt.Format("2006-01-02")))

	return b.String()
}

func (g *Generator) badges(meta FunctionMeta) string {
	var badges []string

	// Runtime badge
	if meta.Runtime != "" {
		badges = append(badges, fmt.Sprintf("<img src=\"https://img.shields.io/badge/runtime-%s-blue.svg?style=flat-square\" alt=\"Runtime\"/>", meta.Runtime))
	}

	// Deterministic badge
	if meta.Deterministic {
		badges = append(badges, "<img src=\"https://img.shields.io/badge/deterministic-yes-green.svg?style=flat-square\" alt=\"Deterministic\"/>")
	} else {
		badges = append(badges, "<img src=\"https://img.shields.io/badge/deterministic-no-yellow.svg?style=flat-square\" alt=\"Deterministic\"/>")
	}

	// Side effects badge
	se := meta.SideEffects
	if se == "" {
		se = "none"
	}
	color := "green"
	if se == "network" {
		color = "yellow"
	} else if se == "external_state" {
		color = "red"
	}
	badges = append(badges, fmt.Sprintf("<img src=\"https://img.shields.io/badge/side%%20effects-%s-%s.svg?style=flat-square\" alt=\"Side Effects\"/>", se, color))

	// Idempotent badge
	if meta.Idempotent {
		badges = append(badges, "<img src=\"https://img.shields.io/badge/idempotent-yes-green.svg?style=flat-square\" alt=\"Idempotent\"/>")
	}

	// Downloads badge
	if meta.Downloads > 0 {
		badges = append(badges, fmt.Sprintf("<img src=\"https://img.shields.io/badge/downloads-%d-blue.svg?style=flat-square\" alt=\"Downloads\"/>", meta.Downloads))
	}

	// Version badge
	if meta.ReleaseVersion != "" {
		badges = append(badges, fmt.Sprintf("<img src=\"https://img.shields.io/badge/version-%s-blue.svg?style=flat-square\" alt=\"Version\"/>", meta.ReleaseVersion))
	}

	// Code coverage badge
	if meta.CoveragePercent > 0 {
		coverageColor := "red"
		if meta.CoveragePercent >= 80 {
			coverageColor = "green"
		} else if meta.CoveragePercent >= 50 {
			coverageColor = "yellow"
		}
		badges = append(badges, fmt.Sprintf("<img src=\"https://img.shields.io/badge/coverage-%.0f%%-%s.svg?style=flat-square\" alt=\"Coverage\"/>", meta.CoveragePercent, coverageColor))
	}

	// Open/Closed issues badges
	if meta.OpenIssues > 0 || meta.ClosedIssues > 0 {
		badges = append(badges, fmt.Sprintf("<img src=\"https://img.shields.io/github/issues/functionfly/functionfly?label=open&style=flat-square\" alt=\"Open Issues\"/>"))
		badges = append(badges, fmt.Sprintf("<img src=\"https://img.shields.io/github/issues-closed/functionfly/functionfly?label=closed&color=green&style=flat-square\" alt=\"Closed Issues\"/>"))
	}

	if len(badges) == 0 {
		return ""
	}
	return "<div style=\"display:flex;gap:8px;flex-wrap:wrap;align-items:center;\">" + strings.Join(badges, "") + "</div>\n\n"
}

func (g *Generator) overview(meta FunctionMeta) string {
	parts := []string{
		fmt.Sprintf("**%s** (`%s/%s`) is a `%s` function published by `@%s`.",
			firstNonEmpty(meta.Title, meta.Name),
			meta.Author,
			meta.Name,
			meta.Runtime,
			meta.Author,
		),
	}

	if meta.Deterministic {
		parts = append(parts, " It is **deterministic**, meaning it will produce the same output given the same input every time.")
	}

	if meta.Idempotent {
		parts = append(parts, " It is **idempotent**, so it is safe to retry on failure.")
	}

	if meta.CacheTTL > 0 {
		parts = append(parts, fmt.Sprintf(" Results are cached for **%d seconds**.", meta.CacheTTL))
	}

	return strings.Join(parts, "") + "\n"
}

func (g *Generator) runtimeTable(meta FunctionMeta) string {
	rows := []string{
		"| Property | Value |",
		"|----------|-------|",
		fmt.Sprintf("| Runtime | `%s` |", meta.Runtime),
		fmt.Sprintf("| Timeout | %d ms |", meta.TimeoutMs),
		fmt.Sprintf("| Memory | %d MB |", meta.MemoryMB),
		fmt.Sprintf("| Deterministic | %s |", boolYesNo(meta.Deterministic)),
		fmt.Sprintf("| Side Effects | %s |", firstNonEmpty(meta.SideEffects, "none")),
		fmt.Sprintf("| Idempotent | %s |", boolYesNo(meta.Idempotent)),
	}
	if meta.CacheTTL > 0 {
		rows = append(rows, fmt.Sprintf("| Cache TTL | %d s |", meta.CacheTTL))
	}
	if meta.Category != "" {
		rows = append(rows, fmt.Sprintf("| Category | %s |", meta.Category))
	}
	return strings.Join(rows, "\n") + "\n"
}

func (g *Generator) exampleUsage(meta FunctionMeta) string {
	endpoint := fmt.Sprintf("%s/v1/%s/%s", g.BaseURL, meta.Author, meta.Name)

	var exampleInput string
	if meta.InputExample != nil {
		b, _ := json.MarshalIndent(meta.InputExample, "", "  ")
		exampleInput = string(b)
	} else if len(meta.InputSchema) > 0 {
		b, _ := json.MarshalIndent(meta.InputSchema, "", "  ")
		exampleInput = string(b)
	} else {
		exampleInput = "{}"
	}

	var b bytes.Buffer
	b.WriteString("### cURL\n\n")
	b.WriteString(fmt.Sprintf("```bash\ncurl -X POST %s \\\n", endpoint))
	b.WriteString("  -H \"Content-Type: application/json\" \\\n")
	b.WriteString(fmt.Sprintf("  -d '%s'\n", exampleInput))
	b.WriteString("```\n")

	b.WriteString("\n### JavaScript\n\n")
	b.WriteString("```javascript\n")
	b.WriteString(fmt.Sprintf("const response = await fetch('%s', {\n", endpoint))
	b.WriteString("  method: 'POST',\n")
	b.WriteString("  headers: { 'Content-Type': 'application/json' },\n")
	b.WriteString(fmt.Sprintf("  body: JSON.stringify(%s)\n", exampleInput))
	b.WriteString("});\n")
	b.WriteString("const result = await response.json();\n")
	b.WriteString("```\n")

	return b.String()
}

func (g *Generator) trustSection(meta FunctionMeta) string {
	score := meta.TrustScore
	if score <= 0 {
		score = 50 // default
	}
	if score > 100 {
		score = 100
	}

	level := "medium"
	switch {
	case score >= 80:
		level = "high"
	case score >= 60:
		level = "high"
	case score >= 40:
		level = "medium"
	case score >= 20:
		level = "low"
	default:
		level = "untrusted"
	}

	return fmt.Sprintf(
		"This function has a **%.0f%%** trust score (%s).\n\n"+
		"Trust scores are calculated based on execution history, determinism verification, "+
		"replay consistency, and community ratings.\n",
		score, level,
	)
}

func (g *Generator) codeBlock(v interface{}, lang string) string {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return fmt.Sprintf("```%s\n%v\n```", lang, v)
	}
	return fmt.Sprintf("```%s\n%s\n```", lang, string(b))
}

func firstNonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

func boolYesNo(v bool) string {
	if v {
		return "Yes"
	}
	return "No"
}

func humanizeCapability(cap string) string {
	m := map[string]string{
		"fetch:read":  "HTTP Read (makes outbound GET requests)",
		"fetch:write": "HTTP Write (makes outbound POST/PUT/DELETE requests)",
		"crypto":      "Cryptographic operations (hashing, signing)",
		"cache:read":  "Cache Read (reads from shared cache)",
		"cache:write": "Cache Write (writes to shared cache)",
		"kv":          "Key-Value Storage (read/write persistent KV)",
		"webhook":     "Webhook dispatch (sends webhook callbacks)",
		"email":       "Email sending (sends outbound emails)",
		"storage":     "File Storage (reads/writes files)",
		"ai":          "AI/ML inference (calls AI models)",
		"external_api": "External API calls (generic outbound APIs)",
	}
	if h, ok := m[cap]; ok {
		return fmt.Sprintf("`%s` — %s", cap, h)
	}
	return fmt.Sprintf("`%s`", cap)
}

func (g *Generator) functionInvokeURL(meta FunctionMeta) string {
	if meta.FunctionURL != "" {
		return meta.FunctionURL
	}
	return fmt.Sprintf("%s/v1/%s/%s", g.BaseURL, meta.Author, meta.Name)
}
