// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package functionfly

import (
	"context"

	"github.com/functionfly/functionfly/internal/adapters/common"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEdgeDeploymentClientInterface creates a new instance of MockEdgeDeploymentClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEdgeDeploymentClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEdgeDeploymentClientInterface {
	mock := &MockEdgeDeploymentClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEdgeDeploymentClientInterface is an autogenerated mock type for the EdgeDeploymentClientInterface type
type MockEdgeDeploymentClientInterface struct {
	mock.Mock
}

type MockEdgeDeploymentClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEdgeDeploymentClientInterface) EXPECT() *MockEdgeDeploymentClientInterface_Expecter {
	return &MockEdgeDeploymentClientInterface_Expecter{mock: &_m.Mock}
}

// BindRoutes provides a mock function for the type MockEdgeDeploymentClientInterface
func (_mock *MockEdgeDeploymentClientInterface) BindRoutes(ctx context.Context, appName string, routes []common.RouteBinding) error {
	ret := _mock.Called(ctx, appName, routes)

	if len(ret) == 0 {
		panic("no return value specified for BindRoutes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []common.RouteBinding) error); ok {
		r0 = returnFunc(ctx, appName, routes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEdgeDeploymentClientInterface_BindRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindRoutes'
type MockEdgeDeploymentClientInterface_BindRoutes_Call struct {
	*mock.Call
}

// BindRoutes is a helper method to define mock.On call
//   - ctx context.Context
//   - appName string
//   - routes []common.RouteBinding
func (_e *MockEdgeDeploymentClientInterface_Expecter) BindRoutes(ctx any, appName any, routes any) *MockEdgeDeploymentClientInterface_BindRoutes_Call {
	return &MockEdgeDeploymentClientInterface_BindRoutes_Call{Call: _e.mock.On("BindRoutes", ctx, appName, routes)}
}

func (_c *MockEdgeDeploymentClientInterface_BindRoutes_Call) Run(run func(ctx context.Context, appName string, routes []common.RouteBinding)) *MockEdgeDeploymentClientInterface_BindRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []common.RouteBinding
		if args[2] != nil {
			arg2 = args[2].([]common.RouteBinding)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_BindRoutes_Call) Return(err error) *MockEdgeDeploymentClientInterface_BindRoutes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_BindRoutes_Call) RunAndReturn(run func(ctx context.Context, appName string, routes []common.RouteBinding) error) *MockEdgeDeploymentClientInterface_BindRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFunction provides a mock function for the type MockEdgeDeploymentClientInterface
func (_mock *MockEdgeDeploymentClientInterface) DeleteFunction(ctx context.Context, appName string) error {
	ret := _mock.Called(ctx, appName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFunction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, appName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEdgeDeploymentClientInterface_DeleteFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFunction'
type MockEdgeDeploymentClientInterface_DeleteFunction_Call struct {
	*mock.Call
}

// DeleteFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - appName string
func (_e *MockEdgeDeploymentClientInterface_Expecter) DeleteFunction(ctx any, appName any) *MockEdgeDeploymentClientInterface_DeleteFunction_Call {
	return &MockEdgeDeploymentClientInterface_DeleteFunction_Call{Call: _e.mock.On("DeleteFunction", ctx, appName)}
}

func (_c *MockEdgeDeploymentClientInterface_DeleteFunction_Call) Run(run func(ctx context.Context, appName string)) *MockEdgeDeploymentClientInterface_DeleteFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_DeleteFunction_Call) Return(err error) *MockEdgeDeploymentClientInterface_DeleteFunction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_DeleteFunction_Call) RunAndReturn(run func(ctx context.Context, appName string) error) *MockEdgeDeploymentClientInterface_DeleteFunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionStatus provides a mock function for the type MockEdgeDeploymentClientInterface
func (_mock *MockEdgeDeploymentClientInterface) GetFunctionStatus(ctx context.Context, appName string) (*StatusResponse, error) {
	ret := _mock.Called(ctx, appName)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionStatus")
	}

	var r0 *StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*StatusResponse, error)); ok {
		return returnFunc(ctx, appName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *StatusResponse); ok {
		r0 = returnFunc(ctx, appName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, appName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEdgeDeploymentClientInterface_GetFunctionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionStatus'
type MockEdgeDeploymentClientInterface_GetFunctionStatus_Call struct {
	*mock.Call
}

// GetFunctionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - appName string
func (_e *MockEdgeDeploymentClientInterface_Expecter) GetFunctionStatus(ctx any, appName any) *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call {
	return &MockEdgeDeploymentClientInterface_GetFunctionStatus_Call{Call: _e.mock.On("GetFunctionStatus", ctx, appName)}
}

func (_c *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call) Run(run func(ctx context.Context, appName string)) *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call) Return(statusResponse *StatusResponse, err error) *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call) RunAndReturn(run func(ctx context.Context, appName string) (*StatusResponse, error)) *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFunction provides a mock function for the type MockEdgeDeploymentClientInterface
func (_mock *MockEdgeDeploymentClientInterface) RegisterFunction(ctx context.Context, spec *common.DeploymentSpec) (*DeployResponse, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for RegisterFunction")
	}

	var r0 *DeployResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *common.DeploymentSpec) (*DeployResponse, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *common.DeploymentSpec) *DeployResponse); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeployResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *common.DeploymentSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEdgeDeploymentClientInterface_RegisterFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFunction'
type MockEdgeDeploymentClientInterface_RegisterFunction_Call struct {
	*mock.Call
}

// RegisterFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *common.DeploymentSpec
func (_e *MockEdgeDeploymentClientInterface_Expecter) RegisterFunction(ctx any, spec any) *MockEdgeDeploymentClientInterface_RegisterFunction_Call {
	return &MockEdgeDeploymentClientInterface_RegisterFunction_Call{Call: _e.mock.On("RegisterFunction", ctx, spec)}
}

func (_c *MockEdgeDeploymentClientInterface_RegisterFunction_Call) Run(run func(ctx context.Context, spec *common.DeploymentSpec)) *MockEdgeDeploymentClientInterface_RegisterFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *common.DeploymentSpec
		if args[1] != nil {
			arg1 = args[1].(*common.DeploymentSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_RegisterFunction_Call) Return(deployResponse *DeployResponse, err error) *MockEdgeDeploymentClientInterface_RegisterFunction_Call {
	_c.Call.Return(deployResponse, err)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_RegisterFunction_Call) RunAndReturn(run func(ctx context.Context, spec *common.DeploymentSpec) (*DeployResponse, error)) *MockEdgeDeploymentClientInterface_RegisterFunction_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnvironment provides a mock function for the type MockEdgeDeploymentClientInterface
func (_mock *MockEdgeDeploymentClientInterface) SetEnvironment(ctx context.Context, appName string, envVars map[string]string, secrets map[string]string) error {
	ret := _mock.Called(ctx, appName, envVars, secrets)

	if len(ret) == 0 {
		panic("no return value specified for SetEnvironment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string, map[string]string) error); ok {
		r0 = returnFunc(ctx, appName, envVars, secrets)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEdgeDeploymentClientInterface_SetEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvironment'
type MockEdgeDeploymentClientInterface_SetEnvironment_Call struct {
	*mock.Call
}

// SetEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - appName string
//   - envVars map[string]string
//   - secrets map[string]string
func (_e *MockEdgeDeploymentClientInterface_Expecter) SetEnvironment(ctx any, appName any, envVars any, secrets any) *MockEdgeDeploymentClientInterface_SetEnvironment_Call {
	return &MockEdgeDeploymentClientInterface_SetEnvironment_Call{Call: _e.mock.On("SetEnvironment", ctx, appName, envVars, secrets)}
}

func (_c *MockEdgeDeploymentClientInterface_SetEnvironment_Call) Run(run func(ctx context.Context, appName string, envVars map[string]string, secrets map[string]string)) *MockEdgeDeploymentClientInterface_SetEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_SetEnvironment_Call) Return(err error) *MockEdgeDeploymentClientInterface_SetEnvironment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_SetEnvironment_Call) RunAndReturn(run func(ctx context.Context, appName string, envVars map[string]string, secrets map[string]string) error) *MockEdgeDeploymentClientInterface_SetEnvironment_Call {
	_c.Call.Return(run)
	return _c
}
