// Code generated by mockery v2.53.6. DO NOT EDIT.

package functionfly

import (
	context "context"

	common "github.com/functionfly/functionfly/internal/adapters/common"

	mock "github.com/stretchr/testify/mock"
)

// MockEdgeDeploymentClientInterface is an autogenerated mock type for the EdgeDeploymentClientInterface type
type MockEdgeDeploymentClientInterface struct {
	mock.Mock
}

type MockEdgeDeploymentClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEdgeDeploymentClientInterface) EXPECT() *MockEdgeDeploymentClientInterface_Expecter {
	return &MockEdgeDeploymentClientInterface_Expecter{mock: &_m.Mock}
}

// BindRoutes provides a mock function with given fields: ctx, appName, routes
func (_m *MockEdgeDeploymentClientInterface) BindRoutes(ctx context.Context, appName string, routes []common.RouteBinding) error {
	ret := _m.Called(ctx, appName, routes)

	if len(ret) == 0 {
		panic("no return value specified for BindRoutes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []common.RouteBinding) error); ok {
		r0 = rf(ctx, appName, routes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEdgeDeploymentClientInterface_BindRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindRoutes'
type MockEdgeDeploymentClientInterface_BindRoutes_Call struct {
	*mock.Call
}

// BindRoutes is a helper method to define mock.On call
//   - ctx context.Context
//   - appName string
//   - routes []common.RouteBinding
func (_e *MockEdgeDeploymentClientInterface_Expecter) BindRoutes(ctx interface{}, appName interface{}, routes interface{}) *MockEdgeDeploymentClientInterface_BindRoutes_Call {
	return &MockEdgeDeploymentClientInterface_BindRoutes_Call{Call: _e.mock.On("BindRoutes", ctx, appName, routes)}
}

func (_c *MockEdgeDeploymentClientInterface_BindRoutes_Call) Run(run func(ctx context.Context, appName string, routes []common.RouteBinding)) *MockEdgeDeploymentClientInterface_BindRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]common.RouteBinding))
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_BindRoutes_Call) Return(_a0 error) *MockEdgeDeploymentClientInterface_BindRoutes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_BindRoutes_Call) RunAndReturn(run func(context.Context, string, []common.RouteBinding) error) *MockEdgeDeploymentClientInterface_BindRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFunction provides a mock function with given fields: ctx, appName
func (_m *MockEdgeDeploymentClientInterface) DeleteFunction(ctx context.Context, appName string) error {
	ret := _m.Called(ctx, appName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFunction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, appName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEdgeDeploymentClientInterface_DeleteFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFunction'
type MockEdgeDeploymentClientInterface_DeleteFunction_Call struct {
	*mock.Call
}

// DeleteFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - appName string
func (_e *MockEdgeDeploymentClientInterface_Expecter) DeleteFunction(ctx interface{}, appName interface{}) *MockEdgeDeploymentClientInterface_DeleteFunction_Call {
	return &MockEdgeDeploymentClientInterface_DeleteFunction_Call{Call: _e.mock.On("DeleteFunction", ctx, appName)}
}

func (_c *MockEdgeDeploymentClientInterface_DeleteFunction_Call) Run(run func(ctx context.Context, appName string)) *MockEdgeDeploymentClientInterface_DeleteFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_DeleteFunction_Call) Return(_a0 error) *MockEdgeDeploymentClientInterface_DeleteFunction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_DeleteFunction_Call) RunAndReturn(run func(context.Context, string) error) *MockEdgeDeploymentClientInterface_DeleteFunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionStatus provides a mock function with given fields: ctx, appName
func (_m *MockEdgeDeploymentClientInterface) GetFunctionStatus(ctx context.Context, appName string) (*StatusResponse, error) {
	ret := _m.Called(ctx, appName)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionStatus")
	}

	var r0 *StatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*StatusResponse, error)); ok {
		return rf(ctx, appName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *StatusResponse); ok {
		r0 = rf(ctx, appName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*StatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, appName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEdgeDeploymentClientInterface_GetFunctionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionStatus'
type MockEdgeDeploymentClientInterface_GetFunctionStatus_Call struct {
	*mock.Call
}

// GetFunctionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - appName string
func (_e *MockEdgeDeploymentClientInterface_Expecter) GetFunctionStatus(ctx interface{}, appName interface{}) *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call {
	return &MockEdgeDeploymentClientInterface_GetFunctionStatus_Call{Call: _e.mock.On("GetFunctionStatus", ctx, appName)}
}

func (_c *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call) Run(run func(ctx context.Context, appName string)) *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call) Return(_a0 *StatusResponse, _a1 error) *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call) RunAndReturn(run func(context.Context, string) (*StatusResponse, error)) *MockEdgeDeploymentClientInterface_GetFunctionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFunction provides a mock function with given fields: ctx, spec
func (_m *MockEdgeDeploymentClientInterface) RegisterFunction(ctx context.Context, spec *common.DeploymentSpec) (*DeployResponse, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for RegisterFunction")
	}

	var r0 *DeployResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *common.DeploymentSpec) (*DeployResponse, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *common.DeploymentSpec) *DeployResponse); ok {
		r0 = rf(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeployResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *common.DeploymentSpec) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEdgeDeploymentClientInterface_RegisterFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFunction'
type MockEdgeDeploymentClientInterface_RegisterFunction_Call struct {
	*mock.Call
}

// RegisterFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - spec *common.DeploymentSpec
func (_e *MockEdgeDeploymentClientInterface_Expecter) RegisterFunction(ctx interface{}, spec interface{}) *MockEdgeDeploymentClientInterface_RegisterFunction_Call {
	return &MockEdgeDeploymentClientInterface_RegisterFunction_Call{Call: _e.mock.On("RegisterFunction", ctx, spec)}
}

func (_c *MockEdgeDeploymentClientInterface_RegisterFunction_Call) Run(run func(ctx context.Context, spec *common.DeploymentSpec)) *MockEdgeDeploymentClientInterface_RegisterFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*common.DeploymentSpec))
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_RegisterFunction_Call) Return(_a0 *DeployResponse, _a1 error) *MockEdgeDeploymentClientInterface_RegisterFunction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_RegisterFunction_Call) RunAndReturn(run func(context.Context, *common.DeploymentSpec) (*DeployResponse, error)) *MockEdgeDeploymentClientInterface_RegisterFunction_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnvironment provides a mock function with given fields: ctx, appName, envVars, secrets
func (_m *MockEdgeDeploymentClientInterface) SetEnvironment(ctx context.Context, appName string, envVars map[string]string, secrets map[string]string) error {
	ret := _m.Called(ctx, appName, envVars, secrets)

	if len(ret) == 0 {
		panic("no return value specified for SetEnvironment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string, map[string]string) error); ok {
		r0 = rf(ctx, appName, envVars, secrets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEdgeDeploymentClientInterface_SetEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvironment'
type MockEdgeDeploymentClientInterface_SetEnvironment_Call struct {
	*mock.Call
}

// SetEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - appName string
//   - envVars map[string]string
//   - secrets map[string]string
func (_e *MockEdgeDeploymentClientInterface_Expecter) SetEnvironment(ctx interface{}, appName interface{}, envVars interface{}, secrets interface{}) *MockEdgeDeploymentClientInterface_SetEnvironment_Call {
	return &MockEdgeDeploymentClientInterface_SetEnvironment_Call{Call: _e.mock.On("SetEnvironment", ctx, appName, envVars, secrets)}
}

func (_c *MockEdgeDeploymentClientInterface_SetEnvironment_Call) Run(run func(ctx context.Context, appName string, envVars map[string]string, secrets map[string]string)) *MockEdgeDeploymentClientInterface_SetEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_SetEnvironment_Call) Return(_a0 error) *MockEdgeDeploymentClientInterface_SetEnvironment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEdgeDeploymentClientInterface_SetEnvironment_Call) RunAndReturn(run func(context.Context, string, map[string]string, map[string]string) error) *MockEdgeDeploymentClientInterface_SetEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEdgeDeploymentClientInterface creates a new instance of MockEdgeDeploymentClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEdgeDeploymentClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEdgeDeploymentClientInterface {
	mock := &MockEdgeDeploymentClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
