package billing

import (
	"fmt"
	"strings"

	"github.com/functionfly/functionfly/internal/storage"
)

// GenerateWorkerScript combines bundle function templates into a single
// Cloudflare Worker script with URL-based routing. Each template becomes
// an async handler function, and the default export dispatches by pathname.
func GenerateWorkerScript(templates []*storage.BundleFunctionTemplate) []byte {
	var b strings.Builder

	b.WriteString("// Auto-generated by FunctionFly — do not edit\n")
	b.WriteString("export default {\n")
	b.WriteString("  async fetch(request, env) {\n")
	b.WriteString("    const url = new URL(request.url);\n")
	b.WriteString("    const path = url.pathname;\n\n")

	for _, tmpl := range templates {
		funcName := sanitizeFuncName(tmpl.FunctionName)
		b.WriteString(fmt.Sprintf("    if (path === '%s') return %s(request, env);\n", tmpl.RoutePath, funcName))
	}

	b.WriteString("\n    return new Response('Not found', { status: 404 });\n")
	b.WriteString("  }\n")
	b.WriteString("};\n\n")

	for _, tmpl := range templates {
		funcName := sanitizeFuncName(tmpl.FunctionName)
		b.WriteString(fmt.Sprintf("async function %s(request, env) {\n", funcName))
		b.WriteString("  try {\n")

		// Wrap the template code in a function body.
		// Templates use req/res pattern; adapt to CF Workers Request/Response.
		adapted := adaptTemplateCode(tmpl.Code)
		b.WriteString(indent(adapted, "    "))

		b.WriteString("  } catch (err) {\n")
		b.WriteString("    return new Response(JSON.stringify({ error: err.message }), {\n")
		b.WriteString("      status: 500,\n")
		b.WriteString("      headers: { 'Content-Type': 'application/json' }\n")
		b.WriteString("    });\n")
		b.WriteString("  }\n")
		b.WriteString("}\n\n")
	}

	return []byte(b.String())
}

// sanitizeFuncName converts a function name like "stripe-webhook" to "handleStripeWebhook".
func sanitizeFuncName(name string) string {
	parts := strings.Split(name, "-")
	for i := range parts {
		parts[i] = strings.Title(parts[i])
	}
	return "handle" + strings.Join(parts, "")
}

// adaptTemplateCode rewrites template code from the req/res pattern to CF Workers
// Request/Response pattern.
func adaptTemplateCode(code string) string {
	code = strings.TrimSpace(code)

	// Strip the outer "export default async (req, env) => {" and closing "};"
	code = stripExportWrapper(code)

	// Adapt req.body → await request.json()
	code = strings.ReplaceAll(code, "req.body", "await request.json()")

	// Adapt state API: state.set → env.STATE.put, state.get → env.STATE.get
	code = strings.ReplaceAll(code, "state.set(", "env.STATE.put(")
	code = strings.ReplaceAll(code, "state.get(", "env.STATE.get(")

	// Adapt res.json({ ... }) → return new Response(JSON.stringify({ ... }), { headers })
	code = adaptResponseCalls(code)

	// Adapt res.status(N).json({ ... })
	code = adaptStatusResponseCalls(code)

	return code
}

// stripExportWrapper removes the "export default async (req, env) => {" wrapper.
func stripExportWrapper(code string) string {
	// Handle various wrapper patterns
	wrappers := []string{
		"export default async (req, res) => {",
		"export default async (req, env) => {",
		"export default (req, res) => {",
		"export default (req, env) => {",
	}

	for _, wrapper := range wrappers {
		if strings.HasPrefix(code, wrapper) {
			code = strings.TrimPrefix(code, wrapper)
			// Remove trailing "};"
			code = strings.TrimSuffix(code, "};")
			code = strings.TrimSuffix(code, "}")
			return strings.TrimSpace(code)
		}
	}

	return code
}

// adaptResponseCalls converts res.json({ ... }) to return new Response(JSON.stringify({ ... }), ...)
func adaptResponseCalls(code string) string {
	lines := strings.Split(code, "\n")
	var result []string

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// res.json({...})
		if strings.HasPrefix(trimmed, "res.json(") && strings.HasSuffix(trimmed, ");") {
			payload := trimmed[len("res.json(") : len(trimmed)-2] // strip "res.json(" and ");"
			indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
			result = append(result, fmt.Sprintf("%sreturn new Response(JSON.stringify(%s), { headers: { 'Content-Type': 'application/json' } });", indent, payload))
			continue
		}

		result = append(result, line)
	}

	return strings.Join(result, "\n")
}

// adaptStatusResponseCalls converts res.status(N).json({ ... }) to return new Response(...)
func adaptStatusResponseCalls(code string) string {
	lines := strings.Split(code, "\n")
	var result []string

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// res.status(N).json({...})
		if strings.Contains(trimmed, "res.status(") && strings.Contains(trimmed, ").json(") {
			// Extract status code and payload
			statusStart := strings.Index(trimmed, "res.status(") + len("res.status(")
			statusEnd := strings.Index(trimmed[statusStart:], ")")
			statusCode := trimmed[statusStart : statusStart+statusEnd]

			jsonStart := strings.Index(trimmed, ").json(") + len(").json(")
			payload := trimmed[jsonStart : len(trimmed)-1] // strip trailing ";"

			indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
			result = append(result, fmt.Sprintf("%sreturn new Response(JSON.stringify(%s), { status: %s, headers: { 'Content-Type': 'application/json' } });", indent, payload, statusCode))
			continue
		}

		result = append(result, line)
	}

	return strings.Join(result, "\n")
}

// indent adds the given prefix to each non-empty line.
func indent(code string, prefix string) string {
	lines := strings.Split(code, "\n")
	var result []string
	for _, line := range lines {
		if strings.TrimSpace(line) == "" {
			result = append(result, "")
		} else {
			result = append(result, prefix+line)
		}
	}
	return strings.Join(result, "\n") + "\n"
}
