// Package frgapigen provides auto-generated REST and GraphQL APIs from graph definitions
// This enables "Backend as a Graph" - graphs become full API endpoints automatically
package frgapigen

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/functionfly/functionfly/internal/frg"
	"github.com/functionfly/functionfly/internal/storage/state"
	"github.com/google/uuid"
	"github.com/gorilla/mux"
	"github.com/sirupsen/logrus"
)

// AutoGeneratedAPIHandler serves auto-generated REST/GraphQL APIs from graph definitions
type AutoGeneratedAPIHandler struct {
	frgRepo      *frg.Repository
	stateRepo    *state.StateRepository
	engine       *frg.ExecutionEngine
	graphAPIBase string
}

// NewAutoGeneratedAPIHandler creates a new auto-generated API handler
func NewAutoGeneratedAPIHandler(
	frgRepo *frg.Repository,
	stateRepo *state.StateRepository,
	engine *frg.ExecutionEngine,
	graphAPIBase string,
) *AutoGeneratedAPIHandler {
	if graphAPIBase == "" {
		graphAPIBase = "/api/graphs"
	}
	return &AutoGeneratedAPIHandler{
		frgRepo:      frgRepo,
		stateRepo:    stateRepo,
		engine:       engine,
		graphAPIBase: graphAPIBase,
	}
}

// RouteRegistrar registers dynamic routes for all published graphs
func (h *AutoGeneratedAPIHandler) RouteRegistrar(router *mux.Router) error {
	ctx := context.Background()

	// Get all published graphs
	filter := &frg.DefinitionFilter{
		Limit: 1000,
	}
	graphs, err := h.frgRepo.ListDefinitions(ctx, filter)
	if err != nil {
		return fmt.Errorf("failed to list graphs: %w", err)
	}

	// Register routes for each published graph
	for _, graph := range graphs {
		if graph.PublishedAt == nil {
			continue // Skip unpublished graphs
		}

		h.registerGraphRoutes(router, graph)
	}

	logrus.WithField("graph_count", len(graphs)).Info("Registered auto-generated API routes")
	return nil
}

// registerGraphRoutes registers routes for a single graph
func (h *AutoGeneratedAPIHandler) registerGraphRoutes(router *mux.Router, graph *frg.GraphDefinition) {
	basePath := fmt.Sprintf("%s/%s/%s", h.graphAPIBase, graph.Author, graph.Name)

	// Parse trigger config to determine HTTP method
	var triggerConfig frg.TriggerConfig
	if err := json.Unmarshal(graph.TriggerConfig, &triggerConfig); err != nil {
		triggerConfig = frg.TriggerConfig{Type: "webhook", Config: map[string]interface{}{"method": "POST", "path": "/execute"}}
	}

	method := "POST"
	if m, ok := triggerConfig.Config["method"].(string); ok {
		method = strings.ToUpper(m)
	}

	// Register the main execution endpoint
	router.HandleFunc(basePath+"/execute", h.createGraphHandler(graph)).Methods(method, "OPTIONS")

	// Register status endpoint
	router.HandleFunc(basePath+"/status/{instance_id}", h.createStatusHandler(graph)).Methods("GET", "OPTIONS")

	// Register OpenAPI spec endpoint
	router.HandleFunc(basePath+"/spec", h.createOpenAPIHandler(graph)).Methods("GET", "OPTIONS")

	// Register GraphQL endpoint (always available)
	router.HandleFunc(basePath+"/graphql", h.createGraphQLHandler(graph)).Methods("POST", "OPTIONS", "GET")

	// If this is a sync graph, also register at the base path for simpler access
	if graph.ExecutionMode == frg.ExecutionModeSync {
		router.HandleFunc(basePath, h.createGraphHandler(graph)).Methods(method, "OPTIONS")
	}

	logrus.WithFields(logrus.Fields{
		"author": graph.Author,
		"name":   graph.Name,
		"path":   basePath,
		"method": method,
	}).Debug("Registered auto-generated API routes for graph")
}

// createGraphHandler creates an HTTP handler for graph execution
func (h *AutoGeneratedAPIHandler) createGraphHandler(graph *frg.GraphDefinition) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		// Parse request body
		var input map[string]interface{}
		if r.Method == "POST" || r.Method == "PUT" || r.Method == "PATCH" {
			if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
				respondError(w, http.StatusBadRequest, "Invalid JSON body")
				return
			}
		}

		// Add query parameters to input
		queryParams := make(map[string]interface{})
		for key, values := range r.URL.Query() {
			if len(values) == 1 {
				queryParams[key] = values[0]
			} else {
				queryParams[key] = values
			}
		}
		if len(queryParams) > 0 {
			input["_query"] = queryParams
		}

		// Add headers to input
		headerParams := make(map[string]interface{})
		for key, values := range r.Header {
			// Skip sensitive headers
			if !isSensitiveHeader(key) {
				if len(values) == 1 {
					headerParams[key] = values[0]
				} else {
					headerParams[key] = values
				}
			}
		}
		if len(headerParams) > 0 {
			input["_headers"] = headerParams
		}

		// Execute based on mode
		switch graph.ExecutionMode {
		case frg.ExecutionModeSync:
			h.handleSyncExecution(ctx, w, graph, input)
		case frg.ExecutionModeAsync:
			h.handleAsyncExecution(ctx, w, graph, input)
		case frg.ExecutionModeStreaming:
			h.handleStreamingExecution(ctx, w, r, graph, input)
		default:
			// Default to sync
			h.handleSyncExecution(ctx, w, graph, input)
		}
	}
}

// handleSyncExecution handles synchronous graph execution
func (h *AutoGeneratedAPIHandler) handleSyncExecution(ctx context.Context, w http.ResponseWriter, graph *frg.GraphDefinition, input map[string]interface{}) {
	start := time.Now()

	result, err := h.engine.ExecuteSync(ctx, graph, input)
	if err != nil {
		logrus.WithError(err).WithField("graph_id", graph.ID).Error("Sync execution failed")
		respondError(w, http.StatusInternalServerError, fmt.Sprintf("Execution failed: %v", err))
		return
	}

	// Build response
	var output interface{}
	if result.Output != nil {
		if err := json.Unmarshal(result.Output, &output); err != nil {
			output = string(result.Output)
		}
	}

	response := map[string]interface{}{
		"success":     result.Status == frg.InstanceStatusCompleted,
		"instance_id": result.InstanceID.String(),
		"output":      output,
		"duration_ms": result.DurationMs,
	}

	if result.Status == frg.InstanceStatusFailed {
		response["error"] = result.Error
	}

	logrus.WithFields(logrus.Fields{
		"graph_id":    graph.ID,
		"instance_id": result.InstanceID,
		"duration_ms": time.Since(start).Milliseconds(),
		"status":      result.Status,
	}).Debug("Sync graph execution completed")

	respondJSON(w, http.StatusOK, response)
}

// handleAsyncExecution handles asynchronous graph execution
func (h *AutoGeneratedAPIHandler) handleAsyncExecution(ctx context.Context, w http.ResponseWriter, graph *frg.GraphDefinition, input map[string]interface{}) {
	instance, err := h.engine.ExecuteAsync(ctx, graph, input)
	if err != nil {
		logrus.WithError(err).WithField("graph_id", graph.ID).Error("Async execution failed")
		respondError(w, http.StatusInternalServerError, fmt.Sprintf("Execution failed: %v", err))
		return
	}

	response := map[string]interface{}{
		"accepted":    true,
		"instance_id": instance.ID.String(),
		"status":      string(instance.Status),
		"status_url":  fmt.Sprintf("%s/%s/%s/status/%s", h.graphAPIBase, graph.Author, graph.Name, instance.ID.String()),
	}

	logrus.WithFields(logrus.Fields{
		"graph_id":    graph.ID,
		"instance_id": instance.ID,
	}).Debug("Async graph execution started")

	respondJSON(w, http.StatusAccepted, response)
}

// handleStreamingExecution handles streaming graph execution
func (h *AutoGeneratedAPIHandler) handleStreamingExecution(ctx context.Context, w http.ResponseWriter, r *http.Request, graph *frg.GraphDefinition, input map[string]interface{}) {
	// Set up SSE headers
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	// Execute the graph in streaming mode
	// This would use the graph's streaming capabilities
	// For now, we return a simple stream with the result

	result, err := h.engine.ExecuteSync(ctx, graph, input)
	if err != nil {
		fmt.Fprintf(w, "event: error\ndata: %s\n\n", jsonEscape(fmt.Sprintf("Execution failed: %v", err)))
		return
	}

	var output interface{}
	if result.Output != nil {
		json.Unmarshal(result.Output, &output)
	}

	outputJSON, _ := json.Marshal(output)

	fmt.Fprintf(w, "event: result\ndata: %s\n\n", outputJSON)
	fmt.Fprintf(w, "event: complete\ndata: \"done\"\n\n")
}

// createStatusHandler creates a handler for checking instance status
func (h *AutoGeneratedAPIHandler) createStatusHandler(graph *frg.GraphDefinition) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		instanceIDStr := vars["instance_id"]

		instanceID, err := uuid.Parse(instanceIDStr)
		if err != nil {
			respondError(w, http.StatusBadRequest, "Invalid instance ID")
			return
		}

		instance, err := h.frgRepo.GetInstanceByID(r.Context(), instanceID)
		if err != nil {
			respondError(w, http.StatusNotFound, "Instance not found")
			return
		}

		var output interface{}
		if instance.OutputData != nil {
			json.Unmarshal(instance.OutputData, &output)
		}

		response := map[string]interface{}{
			"instance_id":  instance.ID.String(),
			"graph_id":     instance.DefinitionID.String(),
			"status":       string(instance.Status),
			"output":       output,
			"duration_ms":  instance.TotalDurationMs,
			"created_at":   instance.CreatedAt,
			"started_at":   instance.StartedAt,
			"completed_at": instance.CompletedAt,
		}

		if instance.ErrorMessage != nil {
			response["error"] = *instance.ErrorMessage
		}

		respondJSON(w, http.StatusOK, response)
	}
}

// createOpenAPIHandler generates and serves OpenAPI 3.0 spec for the graph
func (h *AutoGeneratedAPIHandler) createOpenAPIHandler(graph *frg.GraphDefinition) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		basePath := fmt.Sprintf("%s/%s/%s", h.graphAPIBase, graph.Author, graph.Name)

		var inputSchema map[string]interface{}
		json.Unmarshal(graph.InputSchema, &inputSchema)

		var outputSchema map[string]interface{}
		json.Unmarshal(graph.OutputSchema, &outputSchema)

		// Parse trigger config
		var triggerConfig frg.TriggerConfig
		json.Unmarshal(graph.TriggerConfig, &triggerConfig)

		method := "POST"
		if m, ok := triggerConfig.Config["method"].(string); ok {
			method = strings.ToUpper(m)
		}

		paths := map[string]interface{}{
			basePath: map[string]interface{}{
				strings.ToLower(method): map[string]interface{}{
					"operationId": fmt.Sprintf("execute_%s_%s", graph.Author, graph.Name),
					"summary":     fmt.Sprintf("Execute %s/%s graph", graph.Author, graph.Name),
					"requestBody": map[string]interface{}{
						"content": map[string]interface{}{
							"application/json": map[string]interface{}{
								"schema": inputSchema,
							},
						},
					},
					"responses": map[string]interface{}{
						"200": map[string]interface{}{
							"description": "Successful execution",
							"content": map[string]interface{}{
								"application/json": map[string]interface{}{
									"schema": map[string]interface{}{
										"type": "object",
										"properties": map[string]interface{}{
											"success":     map[string]interface{}{"type": "boolean"},
											"instance_id": map[string]interface{}{"type": "string", "format": "uuid"},
											"output":      outputSchema,
											"duration_ms": map[string]interface{}{"type": "integer"},
										},
									},
								},
							},
						},
						"202": map[string]interface{}{
							"description": "Async execution accepted",
							"content": map[string]interface{}{
								"application/json": map[string]interface{}{
									"schema": map[string]interface{}{
										"type": "object",
										"properties": map[string]interface{}{
											"accepted":    map[string]interface{}{"type": "boolean"},
											"instance_id": map[string]interface{}{"type": "string", "format": "uuid"},
											"status":      map[string]interface{}{"type": "string"},
											"status_url":  map[string]interface{}{"type": "string", "format": "uri"},
										},
									},
								},
							},
						},
					},
				},
			},
		}

		// Add status endpoint
		paths[basePath+"/status/{instance_id}"] = map[string]interface{}{
			"get": map[string]interface{}{
				"operationId": fmt.Sprintf("status_%s_%s", graph.Author, graph.Name),
				"summary":     "Check execution status",
				"parameters": []map[string]interface{}{
					{
						"name":     "instance_id",
						"in":       "path",
						"required": true,
						"schema":   map[string]interface{}{"type": "string", "format": "uuid"},
					},
				},
				"responses": map[string]interface{}{
					"200": map[string]interface{}{
						"description": "Status retrieved successfully",
					},
				},
			},
		}

		spec := map[string]interface{}{
			"openapi": "3.0.0",
			"info": map[string]interface{}{
				"title":            fmt.Sprintf("%s/%s API", graph.Author, graph.Name),
				"version":          graph.Version,
				"description":      graph.AIDescription,
				"x-graph-id":       graph.ID.String(),
				"x-author":         graph.Author,
				"x-execution-mode": graph.ExecutionMode,
			},
			"paths": paths,
			"servers": []map[string]interface{}{
				{"url": h.graphAPIBase},
			},
		}

		respondJSON(w, http.StatusOK, spec)
	}
}

// createGraphQLHandler creates a GraphQL handler for the graph
func (h *AutoGeneratedAPIHandler) createGraphQLHandler(graph *frg.GraphDefinition) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method == "GET" {
			// Return GraphiQL interface for testing
			w.Header().Set("Content-Type", "text/html")
			fmt.Fprint(w, graphiQLTemplate)
			return
		}

		// Parse GraphQL request
		var request struct {
			Query         string                 `json:"query"`
			Variables     map[string]interface{} `json:"variables,omitempty"`
			OperationName string                 `json:"operationName,omitempty"`
		}

		if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
			respondError(w, http.StatusBadRequest, "Invalid GraphQL request")
			return
		}

		// Simple GraphQL execution - convert to graph execution
		// This is a simplified implementation - a full implementation would
		// parse the GraphQL query and map it to graph nodes

		input := map[string]interface{}{
			"_graphql_query":     request.Query,
			"_graphql_variables": request.Variables,
			"_graphql_operation": request.OperationName,
		}

		// Add regular variables as input
		for k, v := range request.Variables {
			input[k] = v
		}

		// Execute the graph
		result, err := h.engine.ExecuteSync(r.Context(), graph, input)
		if err != nil {
			respondError(w, http.StatusInternalServerError, fmt.Sprintf("Execution failed: %v", err))
			return
		}

		// Format as GraphQL response
		var output interface{}
		if result.Output != nil {
			json.Unmarshal(result.Output, &output)
		}

		graphqlResponse := map[string]interface{}{
			"data": output,
		}

		if result.Status == frg.InstanceStatusFailed {
			graphqlResponse["errors"] = []map[string]interface{}{
				{
					"message": result.Error,
					"extensions": map[string]interface{}{
						"instance_id": result.InstanceID.String(),
					},
				},
			}
			delete(graphqlResponse, "data")
		}

		respondJSON(w, http.StatusOK, graphqlResponse)
	}
}

// Helper functions

func isSensitiveHeader(header string) bool {
	sensitive := []string{"authorization", "cookie", "x-api-key", "x-auth-token"}
	headerLower := strings.ToLower(header)
	for _, s := range sensitive {
		if headerLower == s {
			return true
		}
	}
	return false
}

func jsonEscape(s string) string {
	// Simple JSON string escaping
	result := strings.ReplaceAll(s, `\`, `\\`)
	result = strings.ReplaceAll(result, `"`, `\`+`"`)
	return result
}

func respondJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(data)
}

func respondError(w http.ResponseWriter, status int, message string) {
	respondJSON(w, status, map[string]interface{}{
		"error": message,
		"code":  status,
	})
}

// GraphiQL HTML template for testing GraphQL endpoints
var graphiQLTemplate = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>GraphQL Playground</title>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/graphql-playground-react/build/static/css/index.css" />
  <link rel="shortcut icon" href="//cdn.jsdelivr.net/npm/graphql-playground-react/build/favicon.png" />
  <script src="//cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js"></script>
</head>
<body>
  <div id="root"></div>
  <script>
    window.addEventListener('DOMContentLoaded', function() {
      GraphQLPlayground.init(document.getElementById('root'), {
        endpoint: window.location.pathname,
        settings: {
          'request.credentials': 'include'
        }
      })
    })
  </script>
</body>
</html>`
