package consciousness

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// AnalysisDuration measures how long tenant analysis takes
	AnalysisDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "consciousness_analysis_duration_seconds",
			Help:    "Duration of consciousness analysis per tenant",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"tenant_id"},
	)

	// InsightsGenerated counts insights generated by category and severity
	InsightsGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "consciousness_insights_generated_total",
			Help: "Total number of insights generated",
		},
		[]string{"category", "severity"},
	)

	// AnalyzerErrors counts analyzer errors by analyzer name
	AnalyzerErrors = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "consciousness_analyzer_errors_total",
			Help: "Total number of analyzer errors",
		},
		[]string{"analyzer"},
	)

	// DispatchFailures counts notification dispatch failures by channel
	DispatchFailures = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "consciousness_dispatch_failures_total",
			Help: "Total number of notification dispatch failures",
		},
		[]string{"channel"},
	)

	// DispatchSuccess counts successful notification dispatches by channel
	DispatchSuccess = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "consciousness_dispatch_success_total",
			Help: "Total number of successful notification dispatches",
		},
		[]string{"channel"},
	)

	// ActiveTenantsGauge tracks number of tenants with consciousness enabled
	ActiveTenantsGauge = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "consciousness_active_tenants",
			Help: "Number of tenants with consciousness feature enabled",
		},
	)

	// ScoreValue tracks the system awareness score by tenant
	ScoreValue = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "consciousness_score_value",
			Help: "Current system awareness score by tenant",
		},
		[]string{"tenant_id"},
	)

	// AnalysisInProgress tracks currently running analyses
	AnalysisInProgress = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "consciousness_analysis_in_progress",
			Help: "Number of consciousness analyses currently in progress",
		},
	)

	// RetryQueueSize tracks the size of the retry queue for failed deliveries
	RetryQueueSize = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "consciousness_retry_queue_size",
			Help: "Number of failed deliveries waiting for retry",
		},
	)
)

// RecordInsightGenerated records an insight generation metric
func RecordInsightGenerated(category, severity string) {
	InsightsGenerated.WithLabelValues(category, string(severity)).Inc()
}

// RecordAnalyzerError records an analyzer error metric
func RecordAnalyzerError(analyzerName string) {
	AnalyzerErrors.WithLabelValues(analyzerName).Inc()
}

// RecordDispatchFailure records a notification dispatch failure
func RecordDispatchFailure(channel string) {
	DispatchFailures.WithLabelValues(channel).Inc()
}

// RecordDispatchSuccess records a successful notification dispatch
func RecordDispatchSuccess(channel string) {
	DispatchSuccess.WithLabelValues(channel).Inc()
}

// RecordAnalysisDuration records the duration of a tenant analysis
func RecordAnalysisDuration(tenantID string, durationSeconds float64) {
	AnalysisDuration.WithLabelValues(tenantID).Observe(durationSeconds)
}

// RecordScore records the system awareness score for a tenant
func RecordScore(tenantID string, score float64) {
	ScoreValue.WithLabelValues(tenantID).Set(score)
}
