-- Rollback complete billing system
DROP INDEX IF EXISTS idx_coupon_redemptions_tenant_id;
DROP INDEX IF EXISTS idx_coupon_redemptions_coupon_id;
DROP INDEX IF EXISTS idx_coupons_active;
DROP INDEX IF EXISTS idx_coupons_code;
DROP INDEX IF EXISTS idx_usage_rollups_period;
DROP INDEX IF EXISTS idx_usage_rollups_tenant_id;
DROP INDEX IF EXISTS idx_usage_events_event_type;
DROP INDEX IF EXISTS idx_usage_events_timestamp;
DROP INDEX IF EXISTS idx_usage_events_tenant_id;
DROP INDEX IF EXISTS idx_invoices_status;
DROP INDEX IF EXISTS idx_invoices_tenant_id;
DROP INDEX IF EXISTS idx_subscriptions_status;
DROP INDEX IF EXISTS idx_subscriptions_tenant_id;

DROP TABLE IF EXISTS coupon_redemptions;
DROP TABLE IF EXISTS coupons;
DROP TABLE IF EXISTS usage_rollups;
DROP TABLE IF EXISTS usage_events;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS subscriptions;