-- Remove function content verification tables

DROP TRIGGER IF EXISTS update_registry_function_signatures_updated_at ON registry_function_signatures;
DROP TRIGGER IF EXISTS update_registry_function_malware_scans_updated_at ON registry_function_malware_scans;
DROP TRIGGER IF EXISTS update_registry_function_approvals_updated_at ON registry_function_approvals;
DROP TRIGGER IF EXISTS update_registry_function_approval_comments_updated_at ON registry_function_approval_comments;
DROP TRIGGER IF EXISTS update_registry_function_verification_status_updated_at ON registry_function_verification_status;

DROP TABLE IF EXISTS registry_function_verification_status;
DROP TABLE IF EXISTS registry_function_approval_comments;
DROP TABLE IF EXISTS registry_function_approvals;
DROP TABLE IF EXISTS registry_function_malware_scans;
DROP TABLE IF EXISTS registry_function_signatures;