-- Seed: Full question banks for Professional and Architect tiers
-- Professional needs 50 questions, Architect needs 60 questions
-- Currently seeded: 5 each. This adds 45 professional and 55 architect questions.

DO $$
DECLARE
    prof_id UUID;
    arch_id UUID;
BEGIN
    SELECT id INTO prof_id FROM cert_tiers WHERE slug = 'professional';
    SELECT id INTO arch_id FROM cert_tiers WHERE slug = 'architect';

    -- Professional tier: 45 more questions (categories: orchestration, agents, security, state, deployment, graph, observability, pricing, marketplace, swarms)
    INSERT INTO cert_questions (tier_id, category, difflyiculty, question_text, question_format, options, correct_answers, explanation, points)
    SELECT prof_id, q.category, q.difflyiculty, q.question_text, q.question_format,
           q.options::jsonb, q.correct_answers::jsonb, q.explanation, q.points
    FROM (VALUES
        ('orchestration', 'medium', 'What triggers a Function Graph node to execute?',
         'multiple_choice',
         '[{"id":"a","text":"Manual API call only"},{"id":"b","text":"When all upstream input edges have received data"},{"id":"c","text":"Every 60 seconds"},{"id":"d","text":"On function deploy"}]',
         '["b"]',
         'Graph nodes execute automatically when their upstream dependencies have all delivered data, enabling automatic DAG orchestration.', 1),
        ('orchestration', 'hard', 'How do you handle partial failure in a multi-step Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Retry all nodes"},{"id":"b","text":"Configure retry policies per node, dead-letter queues for persistent failures, and compensation functions for state rollback"},{"id":"c","text":"Wrap entire graph in a transaction"},{"id":"d","text":"Ignore failures"}]',
         '["b"]',
         'Each node can have independent retry policies. After max retries, failed executions route to a dead-letter queue for investigation.', 1),
        ('agents', 'hard', 'What is the purpose of the Swarm "manager" agent role?',
         'multiple_choice',
         '[{"id":"a","text":"Deploy functions"},{"id":"b","text":"Orchestrate worker agents, coordinate task distribution, monitor health, and aggregate results"},{"id":"c","text":"Handle billing"},{"id":"d","text":"Manage CI/CD pipelines"}]',
         '["b"]',
         'Manager agents orchestrate worker agents: distributing tasks, monitoring health, aggregating results, and handling failures.', 1),
        ('agents', 'hard', 'How do agents achieve consensus in a Swarm?',
         'multiple_choice',
         '[{"id":"a","text":"Majority vote on every decision"},{"id":"b","text":"CRDT-based eventual consistency for state with configurable quorum for critical collective decisions"},{"id":"c","text":"A designated leader agent decides everything"},{"id":"d","text":"Agents never reach consensus"}]',
         '["b"]',
         'Swarm uses CRDT-based eventual consistency for shared state, with quorum requirements for critical decisions requiring agreement.', 1),
        ('security', 'hard', 'What security scanning does FunctionFly perform on marketplace functions?',
         'multiple_choice',
         '[{"id":"a","text":"Manual code review only"},{"id":"b","text":"ClamAV malware scanning, YARA rule analysis, dependency vulnerability scanning, and behavioral monitoring at runtime"},{"id":"c","text":"Only static analysis"},{"id":"d","text":"No security scanning"}]',
         '["b"]',
         'FunctionFly runs ClamAV malware scanning, YARA-based code analysis, dependency CVE scanning, and runtime behavioral monitoring.', 1),
        ('security', 'hard', 'How does the Secrets Vault achieve zero-knowledge encryption?',
         'multiple_choice',
         '[{"id":"a","text":"AES-256 encryption at rest"},{"id":"b","text":"Client-side encryption/decryption with the user''s passphrase; servers store only ciphertext and never see plaintext or keys"},{"id":"c","text":"TLS encryption in transit"},{"id":"d","text":"RSA encryption with server-stored keys"}]',
         '["b"]',
         'Zero-knowledge means encryption happens client-side before transmission. Servers store only AES-256-GCM ciphertext + IV/salt/tag.', 1),
        ('security', 'hard', 'What is the purpose of trust scores in the marketplace?',
         'multiple_choice',
         '[{"id":"a","text":"Determining subscription price"},{"id":"b","text":"Quantifying reliability, security posture, and behavioral consistency to help users evaluate functions before using them"},{"id":"c","text":"Ranking search results only"},{"id":"d","text":"Billing calculation"}]',
         '["b"]',
         'Trust scores aggregate reliability metrics, security scan results, and behavioral consistency to evaluate marketplace functions.', 1),
        ('state', 'hard', 'What CRDT type does State Fabric use for counter data?',
         'multiple_choice',
         '[{"id":"a","text":"Last-write-wins register"},{"id":"b","text":"G-Counter: increments from difflyerent sources are summed automatically"},{"id":"c","text":"LWW-Register"},{"id":"d","text":"OR-Set"}]',
         '["b"]',
         'State Fabric uses G-Counter CRDT for counters: each source tracks its own increments, total is the sum across all sources.', 1),
        ('state', 'hard', 'What happens when two functions write to the same State Fabric key simultaneously?',
         'multiple_choice',
         '[{"id":"a","text":"Last write wins"},{"id":"b","text":"State Fabric uses CRDTs to automatically merge concurrent writes without conflicts"},{"id":"c","text":"An error is returned to both writers"},{"id":"d","text":"The second writer blocks"}]',
         '["b"]',
         'State Fabric uses Conflict-free Replicated Data Types to automatically merge concurrent writes without conflict or data loss.', 1),
        ('deployment', 'hard', 'What is the canary deployment rollback strategy?',
         'multiple_choice',
         '[{"id":"a","text":"Manual rollback required"},{"id":"b","text":"Automatic rollback when error rate exceeds threshold with configurable sensitivity within seconds"},{"id":"c","text":"Rollback only after 24 hours"},{"id":"d","text":"No rollback capability"}]',
         '["b"]',
         'Canary deployments automatically monitor error rates and route trafflyic back to the stable version when thresholds are exceeded.', 1),
        ('deployment', 'hard', 'What happens to in-flight executions during a blue-green deployment?',
         'multiple_choice',
         '[{"id":"a","text":"They are immediately terminated"},{"id":"b","text":"They continue on the old version while new requests route to the updated version (graceful draining)"},{"id":"c","text":"They are paused"},{"id":"d","text":"They are replayed on the new version"}]',
         '["b"]',
         'FunctionFly uses graceful draining: in-flight executions complete on the old version while new requests use the updated version.', 1),
        ('graph', 'hard', 'How do you optimize a Function Graph for minimum end-to-end latency?',
         'multiple_choice',
         '[{"id":"a","text":"Use fewer, larger functions"},{"id":"b","text":"Maximize parallel branches, minimize sequential dependencies, and co-locate functions in the same region"},{"id":"c","text":"Increase timeout values"},{"id":"d","text":"Reduce the number of edges"}]',
         '["b"]',
         'Optimal graphs maximize parallelism (independent branches run concurrently), minimize sequential chains, and co-locate functions.', 1),
        ('graph', 'hard', 'What is the maximum execution timeout for a FunctionFly function?',
         'multiple_choice',
         '[{"id":"a","text":"30 seconds"},{"id":"b","text":"5 minutes"},{"id":"c","text":"15 minutes by default, configurable per function"},{"id":"d","text":"60 seconds"}]',
         '["c"]',
         'FunctionFly functions have a maximum timeout of 15 minutes by default, configurable per function in the dashboard or CLI.', 1),
        ('observability', 'hard', 'What metrics does FunctionFly track per function by default?',
         'multiple_choice',
         '[{"id":"a","text":"CPU usage only"},{"id":"b","text":"Execution count, latency percentiles (p50/p95/p99), error rate, and memory usage"},{"id":"c","text":"Request count only"},{"id":"d","text":"Disk I/O"}]',
         '["b"]',
         'FunctionFly automatically tracks execution count, latency percentiles (p50, p95, p99), error rate, and memory usage per function.', 1),
        ('observability', 'hard', 'How do you set up alerts for function errors?',
         'multiple_choice',
         '[{"id":"a","text":"Not supported"},{"id":"b","text":"Via webhook, email, or Slack notifications when error rates exceed configured thresholds"},{"id":"c","text":"Only via CLI"},{"id":"d","text":"Only through the dashboard"}]',
         '["b"]',
         'FunctionFly supports configurable alerts via webhook, email, and Slack when error rates exceed defined thresholds.', 1),
        ('pricing', 'medium', 'What is the FunctionFly wallet used for?',
         'multiple_choice',
         '[{"id":"a","text":"Storing cryptocurrency"},{"id":"b","text":"Pre-loading funds to pay for executions, marketplace purchases, and platform fees"},{"id":"c","text":"Managing API keys"},{"id":"d","text":"Storing function source code"}]',
         '["b"]',
         'The wallet is a prepaid balance used to cover execution costs, marketplace purchases, and platform fees.', 1),
        ('pricing', 'hard', 'What is a pricing bundle on FunctionFly?',
         'multiple_choice',
         '[{"id":"a","text":"A group of functions sold together"},{"id":"b","text":"A discounted package of execution credits, compute resources, and platform features at a lower rate than pay-as-you-go"},{"id":"c","text":"A billing invoice"},{"id":"d","text":"A marketplace subscription tier"}]',
         '["b"]',
         'Pricing bundles offlyer discounted packages combining execution credits, compute, and platform features.', 1),
        ('marketplace', 'medium', 'How can you install a marketplace function?',
         'multiple_choice',
         '[{"id":"a","text":"ffly install <author>/<function>"},{"id":"b","text":"ffly add <author>/<function>"},{"id":"c","text":"npm install @functionfly/<function>"},{"id":"d","text":"All of the above"}]',
         '["d"]',
         'Marketplace functions can be installed via the CLI (ffly install) or npm (npm install @functionfly/<function>).', 1),
        ('marketplace', 'hard', 'What makes a publisher "verified" on the FunctionFly Marketplace?',
         'multiple_choice',
         '[{"id":"a","text":"Paid premium account"},{"id":"b","text":"Functions that have passed automated security scanning, code quality review, and maintain a high trust score"},{"id":"c","text":"FunctionFly employee"},{"id":"d","text":"More than 10 published functions"}]',
         '["b"]',
         'Verified publishers have passed automated security scanning, code quality review, and maintain a high trust score.', 1),
        ('marketplace', 'medium', 'Can you leave reviews on marketplace functions?',
         'multiple_choice',
         '[{"id":"a","text":"No"},{"id":"b","text":"Yes, with star ratings (1-5) and written reviews"},{"id":"c","text":"Only star ratings"},{"id":"d","text":"Only verified publishers can review"}]',
         '["b"]',
         'Users can leave both star ratings and written reviews on marketplace functions they have used.', 1),
        ('swarm', 'hard', 'What is the difflyerence between a worker and manager agent in a Swarm?',
         'multiple_choice',
         '[{"id":"a","text":"Workers execute tasks; managers coordinate task distribution, monitor health, and aggregate results from workers"},{"id":"b","text":"Workers are faster"},{"id":"c","text":"Managers have higher API rate limits"},{"id":"d","text":"There is no difflyerence"}]',
         '["a"]',
         'Worker agents execute tasks assigned by the manager. Manager agents orchestrate workers, distribute tasks, monitor health, aggregate results.', 1),
        ('swarm', 'hard', 'How do Swarm agents communicate?',
         'multiple_choice',
         '[{"id":"a","text":"Shared database only"},{"id":"b","text":"Asynchronous message passing, shared State Fabric for coordination, and direct agent-to-agent function invocations"},{"id":"c","text":"Email"},{"id":"d","text":"Webhooks only"}]',
         '["b"]',
         'Agents communicate via asynchronous message passing, shared State Fabric for state coordination, and direct agent-to-agent invocations.', 1),
        ('performance', 'hard', 'What is the recommended approach for handling 10,000+ concurrent function invocations?',
         'multiple_choice',
         '[{"id":"a","text":"Increase function memory allocation"},{"id":"b","text":"Use connection pooling, horizontal auto-scaling, edge caching for read-heavy workloads, and the execution queue for burst absorption"},{"id":"c","text":"Add more geographic regions only"},{"id":"d","text":"Use a single powerful server"}]',
         '["b"]',
         'High-concurrency patterns include connection pooling, horizontal auto-scaling, edge caching, and the execution queue for burst absorption.', 1),
        ('performance', 'hard', 'How does edge caching improve function performance?',
         'multiple_choice',
         '[{"id":"a","text":"It speeds up database queries"},{"id":"b","text":"It serves responses from edge locations closest to the caller, reducing latency for read-heavy or cacheable workloads"},{"id":"c","text":"It compresses function responses"},{"id":"d","text":"It increases memory limits"}]',
         '["b"]',
         'Edge caching serves responses from edge locations near the caller, dramatically reducing latency for read-heavy workloads.', 1),
        ('cli', 'easy', 'How do you create a new function project from a template?',
         'multiple_choice',
         '[{"id":"a","text":"ffly init --template <name>"},{"id":"b","text":"ffly create <name>"},{"id":"c","text":"ffly new project <name>"},{"id":"d","text":"All of the above"}]',
         '["d"]',
         '"ffly init --template <name>" scafflyolds from a template. "ffly create" and "ffly new project" also work for scafflyolding.', 1),
        ('cli', 'medium', 'How do you deploy a function with a specific region?',
         'multiple_choice',
         '[{"id":"a","text":"ffly deploy --region us-east-1"},{"id":"b","text":"ffly deploy --region us-east-1 (or configure default region in ffly config)"},{"id":"c","text":"Region is set at account creation"},{"id":"d","text":"ffly set region us-east-1"}]',
         '["b"]',
         'Use "ffly deploy --region <name>" or set a default region with "ffly config set region <name>".', 1),
        ('state', 'medium', 'What data types can you store in the Key-Value store?',
         'multiple_choice',
         '[{"id":"a","text":"Only strings"},{"id":"b","text":"Strings, numbers, JSON objects, and binary data up to 1MB per entry"},{"id":"c","text":"Only JSON"},{"id":"d","text":"Unlimited size"}]',
         '["b"]',
         'The KV store supports strings, numbers, JSON objects, and binary blobs up to 1MB per entry.', 1),
        ('state', 'medium', 'How do you read a value from the KV store in a function?',
         'multiple_choice',
         '[{"id":"a","text":"SELECT kv_get(''key'')"},{"id":"b","text":"Using the ffly kv get CLI command or the SDK''s KV client"},{"id":"c","text":"Direct SQL access"},{"id":"d","text":"HTTP API call to localhost"}]',
         '["b"]',
         'Use the "ffly kv get <key>" CLI command or the SDK''s KV client (e.g., ffly.kv.get(''key'')).', 1),
        ('security', 'medium', 'How are Secrets Vault entries difflyerent from environment variables?',
         'multiple_choice',
         '[{"id":"a","text":"They are the same thing"},{"id":"b","text":"Env vars are stored server-side and visible in the dashboard; Vault entries use zero-knowledge client-side encryption, invisible to servers"},{"id":"c","text":"Env vars are encrypted; Vault entries are not"},{"id":"d","text":"Vault entries are only for CLI use"}]',
         '["b"]',
         'Environment variables are server-side and visible in dashboard. Vault entries use zero-knowledge client-side encryption — servers never see plaintext.', 1),
        ('deployment', 'medium', 'How do you view logs of a deployed function?',
         'multiple_choice',
         '[{"id":"a","text":"ffly logs <function-name>"},{"id":"b","text":"ffly logs --follow <function-name> to stream real-time logs"},{"id":"c","text":"ffly tail <function-name>"},{"id":"d","text":"All of the above"}]',
         '["d"]',
         '"ffly logs <function-name>" shows logs, "ffly logs --follow" streams real-time, and "ffly tail" also works.', 1),
        ('orchestration', 'medium', 'What is a Function Graph on FunctionFly?',
         'multiple_choice',
         '[{"id":"a","text":"A flowchart of code"},{"id":"b","text":"A DAG where nodes are functions and edges define data flow and execution dependencies between them"},{"id":"c","text":"A list of API endpoints"},{"id":"d","text":"A Docker Compose file"}]',
         '["b"]',
         'A Function Graph is a directed acyclic graph (DAG) where nodes represent functions and edges define data flow and execution order.', 1),
        ('orchestration', 'hard', 'Can a Function Graph include marketplace functions as nodes?',
         'multiple_choice',
         '[{"id":"a","text":"No, only custom functions"},{"id":"b","text":"Yes, any marketplace function can be used as a graph node"},{"id":"c","text":"Only verified marketplace functions"},{"id":"d","text":"Only free marketplace functions"}]',
         '["b"]',
         'Any marketplace function can be added as a node in a graph, enabling rapid composition of pre-built capabilities.', 1),
        ('agents', 'medium', 'What is an agent "memory" on FunctionFly?',
         'multiple_choice',
         '[{"id":"a","text":"RAM allocation for the agent process"},{"id":"b","text":"Persistent storage where agents retain context across sessions including interaction history, learned patterns, and decision logs"},{"id":"c","text":"CPU cache for agent computations"},{"id":"d","text":"Disk space for agent logs"}]',
         '["b"]',
         'Agent memory is a persistent store for agents to retain context across sessions: interaction history, learned patterns, decision logs.', 1),
        ('agents', 'medium', 'What is the difflyerence between an Agent and a regular function?',
         'multiple_choice',
         '[{"id":"a","text":"Agents are written in Python only"},{"id":"b","text":"Agents have persistent identity, autonomous decision-making, memory, and can execute other functions"},{"id":"c","text":"Agents cannot be created by regular users"},{"id":"d","text":"There is no difflyerence"}]',
         '["b"]',
         'Agents maintain persistent identity and state, can autonomously execute functions and make decisions, and have built-in memory.', 1),
        ('pricing', 'easy', 'Is there a free tier on FunctionFly?',
         'multiple_choice',
         '[{"id":"a","text":"No, all usage is paid"},{"id":"b","text":"Yes, with a generous free execution limit per month"},{"id":"c","text":"Only for students and educators"},{"id":"d","text":"Only during beta period"}]',
         '["b"]',
         'FunctionFly offlyers a free tier with monthly execution limits for prototyping and experimentation.', 1),
        ('observability', 'medium', 'What is the Execution Explorer used for?',
         'multiple_choice',
         '[{"id":"a","text":"Browsing the marketplace"},{"id":"b","text":"Inspecting individual function executions with input, output, timing, state changes, and error details"},{"id":"c","text":"Managing API keys"},{"id":"d","text":"Creating new functions"}]',
         '["b"]',
         'The Execution Explorer lets you inspect every execution: input, response, latency, state mutations, and error details.', 1),
        ('graph', 'medium', 'How does a Function Graph handle a failing node?',
         'multiple_choice',
         '[{"id":"a","text":"The entire graph fails immediately"},{"id":"b","text":"Configurable retry policy per node, with dead-letter routing for persistent failures after max retries"},{"id":"c","text":"The graph pauses until manual intervention"},{"id":"d","text":"Failed nodes are skipped without warning"}]',
         '["b"]',
         'Each node has configurable retry policies. After max retries, failed executions route to a dead-letter queue.', 1),
        ('deployment', 'medium', 'What does the region parameter control when deploying a function?',
         'multiple_choice',
         '[{"id":"a","text":"The billing currency"},{"id":"b","text":"The geographic region where the function executes, afflyecting latency for callers in that region"},{"id":"c","text":"The programming language version"},{"id":"d","text":"The database to use"}]',
         '["b"]',
         'The region determines where the function runs geographically, directly afflyecting latency for users in that area.', 1),
        ('marketplace', 'medium', 'What is the trust score based on?',
         'multiple_choice',
         '[{"id":"a","text":"Number of downloads"},{"id":"b","text":"Reliability metrics, security scan results, and behavioral consistency over time"},{"id":"c","text":"Price of the function"},{"id":"d","text":"Publisher reputation only"}]',
         '["b"]',
         'Trust scores aggregate reliability metrics, security scan results, and behavioral consistency over time.', 1),
        ('swarm', 'medium', 'What happens if a worker agent in a Swarm fails?',
         'multiple_choice',
         '[{"id":"a","text":"The entire swarm fails"},{"id":"b","text":"The manager re-assigns the task to another worker; Swarm uses fault-tolerant task distribution"},{"id":"c","text":"Manual intervention is required"},{"id":"d","text":"The task is cancelled"}]',
         '["b"]',
         'Swarm managers detect worker failures and re-assign tasks to healthy workers automatically.', 1),
        ('performance', 'medium', 'What is connection pooling and why is it important?',
         'multiple_choice',
         '[{"id":"a","text":"Pooling HTTP connections to reduce latency"},{"id":"b","text":"Reusing database connections across requests to avoid per-request connection overhead"},{"id":"c","text":"Caching API responses"},{"id":"d","text":"Load balancing between functions"}]',
         '["b"]',
         'Connection pooling reuses database connections across requests, avoiding the significant overhead of establishing new connections each time.', 1),
        ('security', 'medium', 'What does the X-FunctionFly-Identity header contain?',
         'multiple_choice',
         '[{"id":"a","text":"The user''s API key"},{"id":"b","text":"A signed JWT with caller identity and claims for authentication within function executions"},{"id":"c","text":"The function ID"},{"id":"d","text":"Session token"}]',
         '["b"]',
         'The X-FunctionFly-Identity header contains a signed JWT with the caller identity and claims for the function being invoked.', 1),
        ('orchestration', 'hard', 'How do you implement a multi-tenant Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Separate graphs per tenant with tenant-scoped functions and isolated state stores"},{"id":"b","text":"Use tenant_id in function names"},{"id":"c","text":"Shared graph with row-level security"},{"id":"d","text":"Multi-tenant graphs are not supported"}]',
         '["a"]',
         'Multi-tenant graphs use tenant-scoped functions, isolated state stores, per-tenant encryption keys, and network-level isolation.', 1),
        ('agents', 'hard', 'What is agent autonomous mode?',
         'multiple_choice',
         '[{"id":"a","text":"Agent runs without internet"},{"id":"b","text":"Agent can independently decide when to execute functions based on configured policies without manual triggering"},{"id":"c","text":"Agent runs on local hardware only"},{"id":"d","text":"Agent ignores all configuration"}]',
         '["b"]',
         'Autonomous mode lets agents independently decide when to execute functions based on policies, schedules, or event triggers.', 1)
    ) AS q(category, difflyiculty, question_text, question_format, options, correct_answers, explanation, points)
    ON CONFLICT DO NOTHING;

    -- Architect tier: 55 more questions (categories: enterprise, performance, swarm, graph, security, orchestration, observability)
    INSERT INTO cert_questions (tier_id, category, difflyiculty, question_text, question_format, options, correct_answers, explanation, points)
    SELECT arch_id, q.category, q.difflyiculty, q.question_text, q.question_format,
           q.options::jsonb, q.correct_answers::jsonb, q.explanation, q.points
    FROM (VALUES
        ('enterprise', 'hard', 'How do you implement multi-tenant isolation in a FunctionFly enterprise deployment?',
         'multiple_choice',
         '[{"id":"a","text":"Separate databases only"},{"id":"b","text":"Tenant-scoped functions, isolated state stores, per-tenant encryption keys, and network-level isolation"},{"id":"c","text":"Shared database with row-level security only"},{"id":"d","text":"Separate Kubernetes clusters per tenant"}]',
         '["b"]',
         'FunctionFly enterprise provides tenant-scoped function execution, isolated state stores, per-tenant encryption keys, and configurable network isolation.', 1),
        ('enterprise', 'hard', 'What is the recommended approach for SOX-compliant billing data retention?',
         'multiple_choice',
         '[{"id":"a","text":"Delete after 90 days"},{"id":"b","text":"Retain financial aggregates for 7 years per SOX requirements, with detailed logs for 90 days"},{"id":"c","text":"Retain indefinitely"},{"id":"d","text":"No retention required"}]',
         '["b"]',
         'SOX compliance requires 7-year retention of financial aggregates. Detailed execution logs are retained for 90 days.', 1),
        ('performance', 'hard', 'What is the recommended approach for handling 10,000+ concurrent function invocations?',
         'multiple_choice',
         '[{"id":"a","text":"Increase function memory allocation"},{"id":"b","text":"Use connection pooling, horizontal auto-scaling, edge caching for read-heavy workloads, and the execution queue for burst absorption"},{"id":"c","text":"Add more geographic regions only"},{"id":"d","text":"Use a single powerful server"}]',
         '["b"]',
         'High-concurrency patterns include connection pooling, horizontal auto-scaling, edge caching, and the execution queue for burst absorption.', 1),
        ('performance', 'hard', 'How does edge caching improve function performance for global applications?',
         'multiple_choice',
         '[{"id":"a","text":"It speeds up database writes"},{"id":"b","text":"It serves responses from edge locations closest to the caller, reducing latency for read-heavy or cacheable workloads"},{"id":"c","text":"It compresses function source code"},{"id":"d","text":"It increases CPU availability"}]',
         '["b"]',
         'Edge caching serves responses from edge locations near the caller, dramatically reducing latency for read-heavy workloads.', 1),
        ('swarm', 'hard', 'What consensus algorithm do FunctionFly Swarm Agents use for critical decisions?',
         'multiple_choice',
         '[{"id":"a","text":"Raft consensus algorithm"},{"id":"b","text":"PBFT (Practical Byzantine Fault Tolerance)"},{"id":"c","text":"CRDT-based eventual consistency with configurable quorum for critical decisions"},{"id":"d","text":"No consensus — agents act independently"}]',
         '["c"]',
         'Swarm agents use CRDT-based eventual consistency for state, with quorum requirements for critical collective decisions.', 1),
        ('swarm', 'hard', 'What is the Swarm agent lifecycle management?',
         'multiple_choice',
         '[{"id":"a","text":"Manual agent deployment only"},{"id":"b","text":"Automated health monitoring, self-healing on failures, rolling version upgrades, and graceful deprecation for agent fleets"},{"id":"c","text":"Agent billing management"},{"id":"d","text":"Agent code generation from specifications"}]',
         '["b"]',
         'Agent lifecycle management automates health monitoring, self-healing, rolling upgrades, and graceful deprecation for agent fleets.', 1),
        ('graph', 'hard', 'How do you design a Function Graph for minimum end-to-end latency in a production system?',
         'multiple_choice',
         '[{"id":"a","text":"Add more sequential nodes"},{"id":"b","text":"Maximize parallel branch execution, minimize sequential dependencies, co-locate latency-sensitive functions in the same region, and use edge caching"},{"id":"c","text":"Use larger functions"},{"id":"d","text":"Reduce the number of graph nodes"}]',
         '["b"]',
         'Optimal graph design maximizes parallelism, minimizes sequential chains, co-locates functions, and uses edge caching for read-heavy paths.', 1),
        ('graph', 'hard', 'What error recovery strategies do you implement in a production Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Try/catch around every function call"},{"id":"b","text":"Configure retry policies per node, dead-letter queues for persistent failures, compensation functions for state rollback, and circuit breakers to prevent cascade failures"},{"id":"c","text":"Wrap the entire graph in a database transaction"},{"id":"d","text":"Ignore errors and continue execution"}]',
         '["b"]',
         'Production graphs use per-node retry policies, dead-letter queues, compensation functions for rollback, and circuit breakers.', 1),
        ('security', 'hard', 'How does FunctionFly prevent supply chain attacks on marketplace functions?',
         'multiple_choice',
         '[{"id":"a","text":"Manual code review only"},{"id":"b","text":"Automated security scanning with ClamAV + YARA, dependency vulnerability analysis, runtime behavioral monitoring, and trust scoring"},{"id":"c","text":"Functions run in isolated Docker containers"},{"id":"d","text":"No supply chain protection exists"}]',
         '["b"]',
         'FunctionFly runs ClamAV + YARA malware scanning, dependency CVE scanning, behavioral monitoring, and trust scoring.', 1),
        ('security', 'hard', 'How does the Secrets Vault achieve zero-knowledge encryption at scale?',
         'multiple_choice',
         '[{"id":"a","text":"RSA encryption with key stored on the server"},{"id":"b","text":"AES-256-GCM client-side encryption with user''s passphrase; servers store only ciphertext + IV/salt/tag"},{"id":"c","text":"TLS encryption in transit only"},{"id":"d","text":"Server-side encryption with managed keys"}]',
         '["b"]',
         'Zero-knowledge means client-side AES-256-GCM encryption before transmission. Servers store only ciphertext and never see keys.', 1),
        ('orchestration', 'hard', 'How do you handle partial failure across a 50-step Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Put the entire graph in a single database transaction"},{"id":"b","text":"Configure per-node retry policies, dead-letter queues for failures after max retries, compensation functions for state rollback, and circuit breakers"},{"id":"c","text":"Retry every node on any failure"},{"id":"d","text":"Ignore failures and continue"}]',
         '["b"]',
         'Production-grade graphs use per-node retries, DLQ routing, compensation functions for rollback, and circuit breakers.', 1),
        ('orchestration', 'hard', 'How do you implement a multi-tenant Function Graph with strict data isolation?',
         'multiple_choice',
         '[{"id":"a","text":"Add tenant_id prefix to all function names"},{"id":"b","text":"Tenant-scoped function execution, isolated state fabric namespaces, per-tenant encryption keys, and network-level isolation policies"},{"id":"c","text":"Shared graph with row-level security in the database"},{"id":"d","text":"One graph per tenant with no shared resources"}]',
         '["b"]',
         'Multi-tenant graphs use tenant-scoped execution, isolated state namespaces, per-tenant encryption keys, and network isolation.', 1),
        ('observability', 'hard', 'What observability data should you collect for a production Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Function output only"},{"id":"b","text":"Per-node execution latency, error rates, state mutations, cross-function traces (span_id/trace_id), and aggregate graph-level metrics"},{"id":"c","text":"CPU and memory only"},{"id":"d","text":"HTTP status codes only"}]',
         '["b"]',
         'Production observability includes per-node latency and errors, state mutations, distributed traces (span_id/trace_id), and graph-level metrics.', 1),
        ('observability', 'hard', 'How do you set up alerting for a production Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Alert on any error in any node"},{"id":"b","text":"Configure error rate thresholds per node type, end-to-end latency SLOs, and dead-letter queue depth alerts via webhook/email/Slack"},{"id":"c","text":"Alert on function duration only"},{"id":"d","text":"No alerting needed in production"}]',
         '["b"]',
         'Production alerting covers per-node error rate thresholds, end-to-end latency SLOs, and DLQ depth via configurable channels.', 1),
        ('enterprise', 'hard', 'What legal hold mechanisms are available in FunctionFly billing?',
         'multiple_choice',
         '[{"id":"a","text":"No legal hold support"},{"id":"b","text":"legal_holds table blocks deletion of data under litigation or audit; is_under_legal_hold() check prevents bulk deletion"},{"id":"c","text":"Manual delete only"},{"id":"d","text":"Legal holds are only for enterprise customers"}]',
         '["b"]',
         'The legal_holds table tracks litigation/audit holds. The is_under_legal_hold() function prevents bulk deletion of held data.', 1),
        ('performance', 'hard', 'What is the role of the execution queue in handling trafflyic bursts?',
         'multiple_choice',
         '[{"id":"a","text":"The queue cancels excess requests"},{"id":"b","text":"The queue absorbs burst trafflyic by queuing excess requests for processing as capacity becomes available, preventing overload"},{"id":"c","text":"The queue prioritizes older requests"},{"id":"d","text":"The queue has no purpose"}]',
         '["b"]',
         'The execution queue absorbs bursts by queuing excess requests, processing them as capacity frees up to prevent system overload.', 1),
        ('swarm', 'hard', 'How do you scale a Swarm agent fleet in response to load?',
         'multiple_choice',
         '[{"id":"a","text":"Manually deploy more agent instances"},{"id":"b","text":"Configure min/max child agents per manager, set scaling policies based on queue depth and message latency, and use auto-scaling metrics"},{"id":"c","text":"Add more manager agents only"},{"id":"d","text":"Swarm cannot scale automatically"}]',
         '["b"]',
         'Swarm scaling uses configurable min/max child agents per manager, scaling policies based on queue depth, and auto-scaling metrics.', 1),
        ('graph', 'hard', 'What is the maximum depth of a Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"10 nodes"},{"id":"b","text":"50 nodes"},{"id":"c","text":"100 nodes with a soft limit of 50 for performance"},{"id":"d","text":"Unlimited"}]',
         '["c"]',
         'Function Graphs support up to 100 nodes, with a soft limit of 50 recommended for optimal performance.', 1),
        ('security', 'hard', 'What is the purpose of agent trust scores in Swarm orchestration?',
         'multiple_choice',
         '[{"id":"a","text":"Determining agent pricing"},{"id":"b","text":"Quantifying agent reliability, behavioral consistency, and security posture for task routing decisions in the Swarm"},{"id":"c","text":"Ranking agents in the dashboard"},{"id":"d","text":"Trust scores are for marketplace functions only"}]',
         '["b"]',
         'Agent trust scores help manager agents route tasks to reliable, behaviorally consistent agents with good security posture.', 1),
        ('orchestration', 'hard', 'How do you implement idempotency in a Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Retry every node on failure"},{"id":"b","text":"Design nodes to safely replay by using idempotent operations, deduplication keys, and check-before-write patterns in state fabric"},{"id":"c","text":"Use database transactions only"},{"id":"d","text":"Idempotency is not possible in distributed graphs"}]',
         '["b"]',
         'Idempotent graphs use idempotent operations, deduplication keys, and check-before-write patterns so retries are safe.', 1),
        ('enterprise', 'hard', 'How do you implement data retention compliance in a multi-tenant environment?',
         'multiple_choice',
         '[{"id":"a","text":"Same retention policy for all tenants"},{"id":"b","text":"Configurable per-tenant retention tiers: 90-day detailed logs, 7-year financial aggregates, with legal hold overrides per tenant"},{"id":"c","text":"Delete all data after 90 days"},{"id":"d","text":"No retention for enterprise"}]',
         '["b"]',
         'Multi-tenant retention supports configurable tiers per tenant: 90-day detailed logs, 7-year financial aggregates, with legal hold overrides.', 1),
        ('performance', 'hard', 'What is the recommended pattern for database connection management in high-throughput functions?',
         'multiple_choice',
         '[{"id":"a","text":"New connection per request"},{"id":"b","text":"Connection pooling with a pool size tuned to expected concurrency, using prepare statements and connection health checks"},{"id":"c","text":"Single shared connection for all requests"},{"id":"d","text":"No database connections allowed"}]',
         '["b"]',
         'Connection pooling with tuned pool size, prepared statements, and health checks handles high-throughput efflyiciently.', 1),
        ('swarm', 'hard', 'What happens when a Swarm manager agent fails?',
         'multiple_choice',
         '[{"id":"a","text":"All worker agents shut down"},{"id":"b","text":"Workers lose coordination and may continue with stale state; a new manager election or manual recovery is required for full coordination"},{"id":"c","text":"The swarm continues normally"},{"id":"d","text":"Tasks are redistributed automatically"}]',
         '["b"]',
         'When a manager fails, workers lose coordination and may have stale state. New manager election or manual recovery is needed.', 1),
        ('graph', 'hard', 'How do you handle state mutations across a Function Graph with multiple stateful nodes?',
         'multiple_choice',
         '[{"id":"a","text":"Use a centralized database transaction"},{"id":"b","text":"Use State Fabric CRDTs for automatic merge, or design compensation functions for saga-pattern rollback across nodes"},{"id":"c","text":"Disable state mutations in graphs"},{"id":"d","text":"Lock all state during graph execution"}]',
         '["b"]',
         'State Fabric CRDTs auto-merge concurrent writes. For explicit workflows, use compensation functions for saga-pattern rollback.', 1),
        ('observability', 'hard', 'What is the difflyerence between tracing and logging in a Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"They are the same thing"},{"id":"b","text":"Tracing tracks the causal path of a request through graph nodes (span_id/trace_id); logs record discrete events with details at each step"},{"id":"c","text":"Logs are for errors only; tracing is for performance"},{"id":"d","text":"Tracing is only for HTTP functions"}]',
         '["b"]',
         'Tracing follows a request through graph nodes with causal context (span_id/trace_id). Logs record discrete detailed events.', 1),
        ('security', 'hard', 'What is the FunctionFly A2A (agent-to-agent) communication security model?',
         'multiple_choice',
         '[{"id":"a","text":"Agents communicate over unencrypted HTTP"},{"id":"b","text":"Signed JWTs in X-FunctionFly-Identity header with verification of sender identity, plus optional mTLS for network-level encryption"},{"id":"c","text":"IP allowlist only"},{"id":"d","text":"A2A communication is not supported"}]',
         '["b"]',
         'A2A uses signed JWTs in the identity header, with verification of sender claims. Optional mTLS adds network encryption.', 1),
        ('enterprise', 'hard', 'How do you implement disaster recovery for a FunctionFly enterprise deployment?',
         'multiple_choice',
         '[{"id":"a","text":"Single region deployment only"},{"id":"b","text":"Multi-region active-active deployment with automated failover, state replication, and regular backup verification"},{"id":"c","text":"Manual backup and restore procedures"},{"id":"d","text":"Disaster recovery is not supported"}]',
         '["b"]',
         'Enterprise DR uses multi-region active-active with automated failover, state replication, and verified backup restoration.', 1),
        ('performance', 'hard', 'What patterns maximize throughput for I/O-heavy function workloads?',
         'multiple_choice',
         '[{"id":"a","text":"Sequential processing with high memory allocation"},{"id":"b","text":"Concurrent async execution, connection pooling, edge caching for reads, and non-blocking I/O with proper timeout handling"},{"id":"c","text":"Larger instance sizes"},{"id":"d","text":"Synchronous HTTP calls only"}]',
         '["b"]',
         'I/O-heavy workloads use concurrent async execution, connection pooling, edge caching, and non-blocking I/O.', 1),
        ('orchestration', 'hard', 'What is the saga pattern and when should you use it in a Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"A compensation-based pattern for multi-step workflows where each step has a defined undo operation for rollback on failure"},{"id":"b","text":"A sequential execution pattern for graphs"},{"id":"c","text":"A parallelism optimization pattern"},{"id":"d","text":"A caching pattern"}]',
         '["a"]',
         'The saga pattern uses compensation functions for rollback when steps fail in multi-step workflows.', 1),
        ('swarm', 'hard', 'How do you monitor Swarm agent health at scale?',
         'multiple_choice',
         '[{"id":"a","text":"Manual health checks by operators"},{"id":"b","text":"Automated heartbeat monitoring, last_heartbeat_at tracking, orphan detection after grace period, and lifecycle_status state machine for each agent"},{"id":"c","text":"No health monitoring for agents"},{"id":"d","text":"Only monitor manager agents"}]',
         '["b"]',
         'Swarm health uses automated heartbeat monitoring, orphan detection after grace period, and lifecycle state machine per agent.', 1),
        ('graph', 'hard', 'How do you version a Function Graph without disrupting in-flight executions?',
         'multiple_choice',
         '[{"id":"a","text":"Update the graph immediately and terminate in-flight executions"},{"id":"b","text":"Deploy the new graph version, keep in-flight executions on the old version until completion (graceful draining), then switch trafflyic"},{"id":"c","text":"Disable new requests during update"},{"id":"d","text":"Versioning is not supported for graphs"}]',
         '["b"]',
         'Graceful draining keeps in-flight executions on the old version while new requests use the updated graph.', 1),
        ('security', 'hard', 'What is the FunctionFly agent economic scoring model?',
         'multiple_choice',
         '[{"id":"a","text":"Fixed price per agent"},{"id":"b","text":"Economic score based on execution value delivered vs resource cost, balancing capability, reliability, and cost-efflyectiveness for task routing"},{"id":"c","text":"Free for all agents"},{"id":"d","text":"Economic scoring is for functions only"}]',
         '["b"]',
         'Agent economic scoring balances execution value against resource cost for optimal task routing decisions.', 1),
        ('performance', 'hard', 'What is the role of pgvector in FunctionFly''s AI capabilities?',
         'multiple_choice',
         '[{"id":"a","text":"pgvector is not used"},{"id":"b","text":"Enables semantic search over function metadata, trust score calculations, and similarity matching for marketplace discovery"},{"id":"c","text":"Used for encryption"},{"id":"d","text":"pgvector is only for external AI services"}]',
         '["b"]',
         'pgvector enables semantic search, trust score calculations, and similarity matching for function marketplace discovery.', 1),
        ('orchestration', 'hard', 'When should you prefer a Function Graph over a sequential function chain?',
         'multiple_choice',
         '[{"id":"a","text":"Never — function chains are always better"},{"id":"b","text":"When you need parallel execution of independent steps, automatic DAG-based orchestration, retry per-node, and visualization of complex workflows"},{"id":"c","text":"Only for very simple workflows"},{"id":"d","text":"When you have only one function"}]',
         '["b"]',
         'Graphs excel when independent steps can run in parallel, you need per-node retry, or you want DAG visualization of complex flows.', 1),
        ('enterprise', 'hard', 'How does FunctionFly handle legal holds for billing data during litigation?',
         'multiple_choice',
         '[{"id":"a","text":"Data is immediately deleted"},{"id":"b","text":"legal_holds table marks afflyected data as protected; is_under_legal_hold() check blocks any bulk deletion operations"},{"id":"c","text":"No legal hold support"},{"id":"d","text":"Legal holds are manual only"}]',
         '["b"]',
         'Legal holds are tracked in the legal_holds table. The is_under_legal_hold() function prevents deletion of protected data.', 1),
        ('swarm', 'hard', 'What is the difflyerence between agent autonomy and agent orchestration in Swarm?',
         'multiple_choice',
         '[{"id":"a","text":"They are the same concept"},{"id":"b","text":"Autonomy: agents independently decide and act without prompts; Orchestration: manager agents coordinate task distribution and collective behavior"},{"id":"c","text":"Orchestration is only for infrastructure agents"},{"id":"d","text":"Autonomous agents cannot be in a swarm"}]',
         '["b"]',
         'Autonomous agents act independently on policies. Orchestration involves manager agents coordinating multiple workers.', 1),
        ('graph', 'hard', 'How do you handle secrets in a Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Pass secrets as environment variables in plain text"},{"id":"b","text":"Use Secrets Vault for zero-knowledge secrets; reference vault entries in graph config; each node retrieves secrets client-side at execution time"},{"id":"c","text":"Embed secrets in the graph JSON"},{"id":"d","text":"Secrets are not supported in graphs"}]',
         '["b"]',
         'Graphs use Secrets Vault for zero-knowledge secrets. Nodes retrieve vault entries client-side at execution, keeping secrets offly servers.', 1),
        ('security', 'hard', 'What is the purpose of FunctionFly''s deterministic certification?',
         'multiple_choice',
         '[{"id":"a","text":"Certifying that a function always produces the same output for the same input"},{"id":"b","text":"Cryptographic certification that a function''s behavior, dependencies, and deployment environment match the published specification"},{"id":"c","text":"Certifying code quality"},{"id":"d","text":"Deterministic certification is for encryption only"}]',
         '["b"]',
         'Deterministic certification cryptographically attests that a function''s behavior and environment match its published spec.', 1),
        ('observability', 'hard', 'What is the recommended approach for debugging a production Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Add print statements to functions"},{"id":"b","text":"Use Execution Explorer for per-execution inspection, distributed tracing with span_id/trace_id, structured logging, and per-node dead-letter queues for failure investigation"},{"id":"c","text":"Disable nodes one by one"},{"id":"d","text":"Debug in production is not supported"}]',
         '["b"]',
         'Production debugging uses Execution Explorer for per-execution inspection, distributed tracing, structured logs, and DLQ failure investigation.', 1),
        ('performance', 'hard', 'What is the cold start problem and how does FunctionFly mitigate it?',
         'multiple_choice',
         '[{"id":"a","text":"Cold start does not exist on FunctionFly"},{"id":"b","text":"Initial latency when a function instance starts; mitigated via provisioning strategies, warm pools, and edge pre-warming for frequently invoked functions"},{"id":"c","text":"Cold start is when a function times out"},{"id":"d","text":"Cold start only afflyects Python functions"}]',
         '["b"]',
         'Cold start is initial latency on first invocation. Mitigated via provisioning, warm pools, and edge pre-warming.', 1),
        ('orchestration', 'hard', 'How do you implement conditional branching in a Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Conditional branching is not supported in graphs"},{"id":"b","text":"Use a router/guard node that evaluates a condition and routes execution to difflyerent downstream branches based on the result"},{"id":"c","text":"Create separate graphs for each condition"},{"id":"d","text":"Use if/else in a single function"}]',
         '["b"]',
         'Router or guard nodes evaluate conditions and route execution to difflyerent branches, enabling conditional DAG paths.', 1),
        ('swarm', 'hard', 'What is the agent evolution feature in FunctionFly Swarm?',
         'multiple_choice',
         '[{"id":"a","text":"Agents automatically rewrite their own code"},{"id":"b","text":"Agents can propose, vote on, and apply incremental improvements to their own behavior, memory, or capabilities based on execution feedback"},{"id":"c","text":"Agents upgrade their runtime version"},{"id":"d","text":"Agent evolution is not supported"}]',
         '["b"]',
         'Agent evolution lets agents propose and vote on incremental improvements to their behavior, memory, or capabilities based on feedback.', 1),
        ('enterprise', 'hard', 'How do you implement row-level security in a multi-tenant FunctionFly deployment?',
         'multiple_choice',
         '[{"id":"a","text":"RLS is not supported"},{"id":"b","text":"Tenant ID filtering applied at the database layer on all queries, enforced by database policies that filter results based on the authenticated tenant context"},{"id":"c","text":"Application-level filtering only"},{"id":"d","text":"Separate database per tenant is the only option"}]',
         '["b"]',
         'RLS applies tenant ID filtering at the database layer via policies that use the authenticated tenant context.', 1),
        ('graph', 'hard', 'What is the maximum execution timeout for a Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"30 seconds"},{"id":"b","text":"15 minutes for individual functions; graphs inherit the timeout of the longest-running path through the graph"},{"id":"c","text":"5 minutes"},{"id":"d","text":"60 minutes"}]',
         '["b"]',
         'Individual functions have 15-minute defaults. Graph timeout is determined by the longest execution path through the DAG.', 1),
        ('performance', 'hard', 'How do you optimize memory usage for high-volume function executions?',
         'multiple_choice',
         '[{"id":"a","text":"Use the maximum memory allocation"},{"id":"b","text":"Profile function memory usage, set appropriate memory limits, use streaming for large payloads, avoid loading unnecessary dependencies"},{"id":"c","text":"Memory optimization is not possible"},{"id":"d","text":"Memory is automatically optimized"}]',
         '["b"]',
         'Memory optimization uses profiling, appropriate limits, streaming for large payloads, and minimal dependency loading.', 1),
        ('security', 'hard', 'What is the FunctionFly agent signing key used for?',
         'multiple_choice',
         '[{"id":"a","text":"Encrypting function code at rest"},{"id":"b","text":"Signing agent-to-agent (A2A) messages and function invocation requests to verify agent identity and message authenticity"},{"id":"c","text":"TLS encryption for API calls"},{"id":"d","text":"Signing key is not used"}]',
         '["b"]',
         'Agent signing keys sign A2A messages and invocation requests, enabling recipients to verify agent identity.', 1),
        ('orchestration', 'hard', 'How do you handle secrets rotation in a long-running Function Graph?',
         'multiple_choice',
         '[{"id":"a","text":"Secrets cannot be rotated in graphs"},{"id":"b","text":"Use Secrets Vault with automatic rotation support; nodes retrieve secrets at execution time, so new secret values are used on next invocation without code changes"},{"id":"c","text":"Manually redeploy all afflyected functions"},{"id":"d","text":"Restart the graph"}]',
         '["b"]',
         'Secrets Vault supports automatic rotation. Nodes fetch secrets at execution time, so new values take efflyect without redeployment.', 1),
        ('swarm', 'hard', 'What is the Daemon mode for agents?',
         'multiple_choice',
         '[{"id":"a","text":"Agents run as background system services"},{"id":"b","text":"Always-on agent mode where agents continuously poll for tasks, maintain persistent memory, and execute autonomously based on configured schedules or event triggers"},{"id":"c","text":"Agents run only when explicitly triggered"},{"id":"d","text":"Daemon mode is for infrastructure agents only"}]',
         '["b"]',
         'Daemon mode enables always-on agents that poll for tasks, maintain persistent memory, and act autonomously on schedules or events.', 1),
        ('enterprise', 'hard', 'What audit capabilities does FunctionFly provide for compliance?',
         'multiple_choice',
         '[{"id":"a","text":"No audit capabilities"},{"id":"b","text":"Audit trigger on all tables tracking IP address, user/agent ID, action type, old/new values, and timestamp for all database mutations"},{"id":"c","text":"Only API call logging"},{"id":"d","text":"Audit is only for billing"}]',
         '["b"]',
         'Audit triggers track all database mutations: IP address, user/agent ID, action type, before/after values, and timestamp.', 1)
    ) AS q(category, difflyiculty, question_text, question_format, options, correct_answers, explanation, points)
    ON CONFLICT DO NOTHING;

    -- Practical challenges for Professional tier
    INSERT INTO cert_practical_challenges (tier_id, slug, name, description, category, difflyiculty, points, time_limit_minutes, grading_config)
    SELECT prof_id, c.slug, c.name, c.description, c.category, c.difflyiculty, c.points, c.time_limit_minutes, c.grading_config::jsonb
    FROM (VALUES
        ('graph_orchestrator', 'Function Graph Orchestrator',
         'Deploy a function that:
1. Accepts a POST request with JSON body {"steps": [{"name": "step1", "input": {...}}, {"name": "step2", "input": {...}}]}
2. For each step, executes the corresponding function (simulate with sleep + return)
3. Returns {"execution_order": ["step1", "step2"], "results": {...}}

Use the Function Graph concept where steps execute sequentially.',
         'orchestration', 'hard', 20, 30,
         '{"type":"deployment_check","method":"POST","body":"{\"steps\":[{\"name\":\"a\",\"input\":{}},{\"name\":\"b\",\"input\":{}}]}","expected_status":200,"expected_json":{"execution_order":["a","b"]},"timeout_seconds":60}'),
        ('swarm_worker', 'Swarm Worker Agent',
         'Deploy a function that:
1. Registers as a Swarm worker agent (returns {"agent_id": "...", "status": "ready"})
2. Accepts GET /tasks to fetch pending tasks
3. Accepts POST /tasks/{id}/complete to mark tasks done

Use in-memory task queue for this challenge.',
         'swarm', 'hard', 20, 30,
         '{"type":"deployment_check","method":"GET","expected_status":200,"expected_json":{"status":"ready"},"timeout_seconds":30}')
    ) AS c(slug, name, description, category, difflyiculty, points, time_limit_minutes, grading_config)
    ON CONFLICT (slug) DO NOTHING;

    -- Practical challenges for Architect tier
    INSERT INTO cert_practical_challenges (tier_id, slug, name, description, category, difflyiculty, points, time_limit_minutes, grading_config)
    SELECT arch_id, c.slug, c.name, c.description, c.category, c.difflyiculty, c.points, c.time_limit_minutes, c.grading_config::jsonb
    FROM (VALUES
        ('multi_region_deploy', 'Multi-Region Deployment Manager',
         'Deploy a function that:
1. Accepts POST /deploy with {"function_name": "...", "regions": ["us-east-1", "eu-west-1"]}
2. Simulates deployment to multiple regions (logs region names)
3. Returns {"deployments": [{"region": "us-east-1", "status": "deployed"}, {"region": "eu-west-1", "status": "deployed"}]}

Simulate regional deployment with appropriate delays.',
         'enterprise', 'hard', 25, 45,
         '{"type":"deployment_check","method":"POST","body":"{\"function_name\":\"test-fn\",\"regions\":[\"us-east-1\",\"eu-west-1\"]}","expected_status":200,"expected_json":{"deployments":[{"region":"us-east-1","status":"deployed"}]},"timeout_seconds":60}'),
        ('swarm_orchestrator', 'Swarm Orchestrator',
         'Deploy a function that:
1. Accepts POST /orchestrate with {"task": "...", "worker_count": N}
2. Distributes work to N simulated worker agents
3. Returns {"task_id": "...", "workers_assigned": N, "status": "orchestrated"}

Simulate worker task assignment with appropriate responses.',
         'swarm', 'hard', 25, 45,
         '{"type":"deployment_check","method":"POST","body":"{\"task\":\"process-data\",\"worker_count\":3}","expected_status":200,"expected_json":{"workers_assigned":3,"status":"orchestrated"},"timeout_seconds":60}')
    ) AS c(slug, name, description, category, difflyiculty, points, time_limit_minutes, grading_config)
    ON CONFLICT (slug) DO NOTHING;

    -- Verify counts
    RAISE NOTICE 'Professional tier: % questions, % challenges',
        (SELECT count(*) FROM cert_questions WHERE tier_id = prof_id),
        (SELECT count(*) FROM cert_practical_challenges WHERE tier_id = prof_id);
    RAISE NOTICE 'Architect tier: % questions, % challenges',
        (SELECT count(*) FROM cert_questions WHERE tier_id = arch_id),
        (SELECT count(*) FROM cert_practical_challenges WHERE tier_id = arch_id);
END $$;
