// RecentReceipts — a section that appears on the FunctionPage showing
// the most recent public receipts generated by this function. Links
// each row to the public /r/:id page so visitors can click through
// to see the function in action.
//
// This is the main distribution surface: every function page is
// visited by potential new users; the receipts are proof the
// function is "alive" and runnable.
import { Clock, ExternalLink, Sparkles, Zap } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';

import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { API_URLS } from '@/lib/api-urls';

interface RecentReceipt {
  id: string;
  function_name: string;
  function_author: string;
  runtime: string;
  view_count: number;
  created_at: string;
  url: string;
}

interface RecentReceiptsProps {
  functionAuthor: string;
  functionName: string;
  /** How many recent receipts to show. Default 5. */
  limit?: number;
}

function formatTime(iso: string): string {
  try {
    const d = new Date(iso);
    const diff = (Date.now() - d.getTime()) / 1000;
    if (diff < 60) return 'just now';
    if (diff < 3600) return `${Math.round(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.round(diff / 3600)}h ago`;
    if (diff < 86400 * 7) return `${Math.round(diff / 86400)}d ago`;
    return d.toLocaleDateString();
  } catch {
    return iso;
  }
}

export function RecentReceipts({ receipts, loading, limit = 5 }: { receipts: Array<{ id: string; created_at: string; view_count: number }>; loading?: boolean; limit?: number }) {
  const rows = (receipts ?? []).slice(0, limit);

  return (
    <Card id="recent-receipts" data-testid="function-recent-receipts">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <Sparkles className="h-4 w-4 text-indigo-400" aria-hidden />
          Recent public receipts
        </CardTitle>
        <CardDescription>
          Every run of this function is automatically a public, shareable URL.
          Anyone can open it — no sign-up required.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {(loading ?? false) ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : rows.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No public receipts yet. Be the first to run this function and share it.
          </p>
        ) : (
          <ul className="space-y-2" data-testid="function-recent-receipts-list">
            {rows.map((r) => (
              <li
                key={r.id}
                className="group flex items-center gap-3 rounded-lg border border-border/40 bg-bg-tertiary/40 p-3 transition-colors hover:border-indigo-500/30 hover:bg-indigo-500/5"
              >
                <a
                  href={`/r/${r.id}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex-1 min-w-0"
                >
                  <div className="flex items-center gap-2">
                    <Zap className="h-3.5 w-3.5 text-indigo-400 shrink-0" aria-hidden />
                    <p className="font-mono text-xs text-foreground truncate" title={r.id}>
                      {r.id}
                    </p>
                  </div>
                  <div className="mt-1 flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground">
                    <span className="inline-flex items-center gap-1">
                      <Clock className="h-3 w-3" aria-hidden /> {formatTime(r.created_at)}
                    </span>
                    <span>·</span>
                    {(r.view_count > 0) && (
                      <>
                        <span>·</span>
                        <span>{r.view_count} view{r.view_count === 1 ? '' : 's'}</span>
                      </>
                    )}
                  </div>
                </a>
                <a
                  href={`/r/${r.id}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="shrink-0 inline-flex items-center gap-1 rounded-md bg-indigo-500/10 px-2 py-1 text-xs font-medium text-indigo-300 ring-1 ring-indigo-500/30 hover:bg-indigo-500/20"
                  aria-label={`Open receipt ${r.id} in a new tab`}
                >
                  <ExternalLink className="h-3 w-3" aria-hidden />
                  Open
                </a>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}

export default RecentReceipts;
