package devtools

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// generateJSONSchema generates schema as JSON
func (dt *DatabaseDevTools) generateJSONSchema(schema *SchemaInfo, outputFile string) error {
	dt.logger.WithField("format", "json").WithField("output_file", outputFile).Debug("Generating JSON schema")

	data, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		dt.logger.WithError(err).Error("Failed to marshal schema to JSON")
		return fmt.Errorf("failed to marshal schema to JSON: %w", err)
	}

	if outputFile != "" {
		if err := os.WriteFile(outputFile, data, dt.config.FilePermissions); err != nil {
			dt.logger.WithError(err).WithField("output_file", outputFile).Error("Failed to write JSON schema to file")
			return fmt.Errorf("failed to write JSON schema to file %s: %w", outputFile, err)
		}
		dt.logger.WithField("output_file", outputFile).WithField("size_bytes", len(data)).Info("JSON schema written to file")
		return nil
	}

	fmt.Println(string(data))
	dt.logger.WithField("size_bytes", len(data)).Debug("JSON schema printed to stdout")
	return nil
}

// generateSQLSchema generates schema as SQL
func (dt *DatabaseDevTools) generateSQLSchema(schema *SchemaInfo, outputFile string) error {
	dt.logger.WithField("format", "sql").WithField("output_file", outputFile).WithField("table_count", len(schema.Tables)).Debug("Generating SQL schema")

	var output strings.Builder

	output.WriteString("-- Database Schema Export\n")
	output.WriteString("-- Generated by DatabaseDevTools\n\n")

	for _, table := range schema.Tables {
		output.WriteString(fmt.Sprintf("-- Table: %s\n", table.Name))
		output.WriteString(fmt.Sprintf("CREATE TABLE %s (\n", table.Name))

		for i, col := range table.Columns {
			nullable := ""
			if !col.Nullable {
				nullable = " NOT NULL"
			}
			comma := ","
			if i == len(table.Columns)-1 {
				comma = ""
			}
			output.WriteString(fmt.Sprintf("  %s %s%s%s\n", col.Name, col.Type, nullable, comma))
		}
		output.WriteString(");\n\n")
	}

	result := output.String()

	if outputFile != "" {
		if err := os.WriteFile(outputFile, []byte(result), dt.config.FilePermissions); err != nil {
			dt.logger.WithError(err).WithField("output_file", outputFile).Error("Failed to write SQL schema to file")
			return fmt.Errorf("failed to write SQL schema to file %s: %w", outputFile, err)
		}
		dt.logger.WithField("output_file", outputFile).WithField("size_bytes", len(result)).Info("SQL schema written to file")
		return nil
	}

	fmt.Print(result)
	dt.logger.WithField("size_bytes", len(result)).Debug("SQL schema printed to stdout")
	return nil
}

// generateMermaidDiagram generates schema as Mermaid diagram
func (dt *DatabaseDevTools) generateMermaidDiagram(schema *SchemaInfo, outputFile string) error {
	dt.logger.WithField("format", "mermaid").WithField("output_file", outputFile).WithField("table_count", len(schema.Tables)).Debug("Generating Mermaid diagram")

	var output strings.Builder

	output.WriteString("```mermaid\nerDiagram\n")

	for _, table := range schema.Tables {
		output.WriteString(fmt.Sprintf("  %s {\n", table.Name))
		for _, col := range table.Columns {
			output.WriteString(fmt.Sprintf("    %s %s\n", col.Type, col.Name))
		}
		output.WriteString("  }\n")
	}

	// Add relationships (simplified)
	relationshipCount := 0
	for _, constraint := range schema.Constraints {
		if constraint.Type == "f" { // foreign key
			// Parse foreign key definition to extract relationship
			output.WriteString(fmt.Sprintf("  %s ||--o{ %s : \"\"\n", constraint.Table, "referenced_table"))
			relationshipCount++
		}
	}

	output.WriteString("```\n")

	result := output.String()

	if outputFile != "" {
		if err := os.WriteFile(outputFile, []byte(result), dt.config.FilePermissions); err != nil {
			dt.logger.WithError(err).WithField("output_file", outputFile).Error("Failed to write Mermaid diagram to file")
			return fmt.Errorf("failed to write Mermaid diagram to file %s: %w", outputFile, err)
		}
		dt.logger.WithField("output_file", outputFile).WithField("relationships", relationshipCount).Info("Mermaid diagram written to file")
		return nil
	}

	fmt.Print(result)
	dt.logger.WithField("relationships", relationshipCount).Debug("Mermaid diagram printed to stdout")
	return nil
}

// generatePlantUMLDiagram generates schema as PlantUML diagram
func (dt *DatabaseDevTools) generatePlantUMLDiagram(schema *SchemaInfo, outputFile string) error {
	dt.logger.WithField("format", "plantuml").WithField("output_file", outputFile).WithField("table_count", len(schema.Tables)).Debug("Generating PlantUML diagram")

	var output strings.Builder

	output.WriteString("@startuml\n")

	for _, table := range schema.Tables {
		output.WriteString(fmt.Sprintf("entity %s {\n", table.Name))
		for _, col := range table.Columns {
			output.WriteString(fmt.Sprintf("  * %s : %s\n", col.Name, col.Type))
		}
		output.WriteString("}\n")
	}

	output.WriteString("@enduml\n")

	result := output.String()

	if outputFile != "" {
		if err := os.WriteFile(outputFile, []byte(result), dt.config.FilePermissions); err != nil {
			dt.logger.WithError(err).WithField("output_file", outputFile).Error("Failed to write PlantUML diagram to file")
			return fmt.Errorf("failed to write PlantUML diagram to file %s: %w", outputFile, err)
		}
		dt.logger.WithField("output_file", outputFile).WithField("size_bytes", len(result)).Info("PlantUML diagram written to file")
		return nil
	}

	fmt.Print(result)
	dt.logger.WithField("size_bytes", len(result)).Debug("PlantUML diagram printed to stdout")
	return nil
}