// Proto generated code
pub mod server;

// tonic-prost-build writes the regenerated gRPC stubs (message types and
// the server trait) to OUT_DIR. We expose them through this module so the
// rest of the crate can write `crate::proto::*`.
//
// The pre-existing `prism_generated.rs` file that lived next to this
// file is now generated by build.rs into OUT_DIR; the build script
// deletes the stale on-disk copy to prevent conflicting definitions.
#[allow(clippy::duplicate_mod)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/prism.v1.rs"));
}

// Flat re-exports for the proto types so handlers and tests can write
// `crate::proto::CellStatus` instead of `crate::proto::generated::CellStatus`.
pub use generated::*;
