// This file is @generated by prost-build.
/// / Represents a single Adaptive Execution Cell - the fundamental unit of execution
// Note: serde derives removed - Timestamp fields don't implement Serialize
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionCell {
    /// Unique identifier (UUID)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Tenant isolation
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    /// Current cell status
    #[prost(enumeration = "CellStatus", tag = "3")]
    pub status: i32,
    /// Cell configuration
    #[prost(message, optional, tag = "4")]
    pub config: ::core::option::Option<CellConfig>,
    /// Resource allocation
    #[prost(message, optional, tag = "5")]
    pub resources: ::core::option::Option<CellResources>,
    /// Metadata and tags
    #[prost(message, optional, tag = "6")]
    pub metadata: ::core::option::Option<CellMetadata>,
    /// Execution state
    ///
    /// Reference to WASM module
    #[prost(string, tag = "10")]
    pub wasm_module_id: ::prost::alloc::string::String,
    /// Frozen execution state for migration
    #[prost(bytes = "vec", tag = "11")]
    pub serialized_state: ::prost::alloc::vec::Vec<u8>,
    /// Quantum snapshot epoch
    #[prost(uint64, tag = "12")]
    pub checkpoint_epoch: u64,
    /// Streaming state
    ///
    /// Live state partitions
    #[prost(message, repeated, tag = "13")]
    pub state_slices: ::prost::alloc::vec::Vec<StateSlice>,
    /// Streaming configuration
    #[prost(message, optional, tag = "14")]
    pub stream_config: ::core::option::Option<StateStreamConfig>,
    #[prost(message, optional, tag = "20")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "21")]
    pub last_executed_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "22")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CellConfig {
    #[prost(uint64, tag = "1")]
    pub memory_limit_mb: u64,
    #[prost(uint32, tag = "2")]
    pub timeout_ms: u32,
    #[prost(uint32, tag = "3")]
    pub max_instances: u32,
    #[prost(bool, tag = "4")]
    pub isolation_enabled: bool,
    /// Required capabilities
    #[prost(string, repeated, tag = "5")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Environment variables
    #[prost(btree_map = "string, string", tag = "6")]
    pub env_vars: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// "cloud", "edge", "browser", "robotic"
    #[prost(string, tag = "7")]
    pub execution_target: ::prost::alloc::string::String,
    /// Scheduling hint
    #[prost(message, optional, tag = "8")]
    pub placement_hint: ::core::option::Option<PlacementHint>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CellResources {
    #[prost(uint32, tag = "1")]
    pub vcpus: u32,
    #[prost(uint64, tag = "2")]
    pub memory_bytes: u64,
    #[prost(bool, tag = "3")]
    pub gpu_required: bool,
    #[prost(uint32, tag = "4")]
    pub gpu_memory_mb: u32,
    /// Where it's actually running
    #[prost(enumeration = "ExecutionLocation", tag = "5")]
    pub location: i32,
    /// Cost optimization weight
    #[prost(float, tag = "6")]
    pub cost_weight: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CellMetadata {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// "wasm", "python", "rust", etc.
    #[prost(string, tag = "3")]
    pub runtime: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "4")]
    pub tags: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Supported languages
    #[prost(string, repeated, tag = "5")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlacementHint {
    #[prost(enumeration = "ExecutionLocation", tag = "1")]
    pub preferred_location: i32,
    #[prost(string, repeated, tag = "2")]
    pub preferred_regions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 0.0 to 1.0
    #[prost(float, tag = "3")]
    pub latency_sensitivity: f32,
    /// 0.0 to 1.0
    #[prost(float, tag = "4")]
    pub cost_sensitivity: f32,
    #[prost(bool, tag = "5")]
    pub gpu_required: bool,
    /// For AI model routing
    #[prost(string, tag = "6")]
    pub model_affinity: ::prost::alloc::string::String,
}
/// / A slice of distributed state
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateSlice {
    #[prost(string, tag = "1")]
    pub slice_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    /// Serialized value (JSON, msgpack, etc.)
    #[prost(bytes = "vec", tag = "4")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "ValueEncoding", tag = "5")]
    pub encoding: i32,
    /// Vector clock version
    #[prost(uint64, tag = "6")]
    pub version: u64,
    /// For CRDT ordering
    #[prost(uint64, tag = "7")]
    pub logical_timestamp: u64,
    /// No more updates coming
    #[prost(bool, tag = "8")]
    pub is_final: bool,
    #[prost(message, optional, tag = "9")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateStreamConfig {
    #[prost(string, tag = "1")]
    pub stream_id: ::prost::alloc::string::String,
    #[prost(enumeration = "StreamStrategy", tag = "2")]
    pub strategy: i32,
    #[prost(uint32, tag = "3")]
    pub buffer_size: u32,
    #[prost(bool, tag = "4")]
    pub resumable: bool,
    #[prost(message, optional, tag = "5")]
    pub retention: ::core::option::Option<RetentionPolicy>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetentionPolicy {
    #[prost(uint32, tag = "1")]
    pub max_age_seconds: u32,
    #[prost(uint64, tag = "2")]
    pub max_items: u64,
    #[prost(bool, tag = "3")]
    pub persist_to_cold_storage: bool,
}
/// / A discoverable capability in the mesh
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Capability {
    #[prost(string, tag = "1")]
    pub capability_id: ::prost::alloc::string::String,
    /// e.g., "vision.detect", "speech.synthesize"
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "CapabilityCategory", tag = "3")]
    pub category: i32,
    #[prost(message, optional, tag = "4")]
    pub metadata: ::core::option::Option<CapabilityMetadata>,
    #[prost(message, optional, tag = "5")]
    pub performance: ::core::option::Option<PerformanceProfile>,
    #[prost(message, optional, tag = "6")]
    pub trust: ::core::option::Option<TrustLevel>,
    /// Supported runtimes
    #[prost(string, repeated, tag = "7")]
    pub runtimes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Supported languages
    #[prost(string, repeated, tag = "8")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Capability WASM module (optional)
    #[prost(bytes = "vec", tag = "9")]
    pub wasm_bundle: ::prost::alloc::vec::Vec<u8>,
    /// Requires network call
    #[prost(bool, tag = "10")]
    pub is_remote: bool,
    /// If is_remote, the endpoint URL
    #[prost(string, tag = "11")]
    pub endpoint: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CapabilityMetadata {
    #[prost(string, tag = "1")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "3")]
    pub tags: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Who provides this capability
    #[prost(string, tag = "4")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub documentation_url: ::prost::alloc::string::String,
    /// Other capabilities this depends on
    #[prost(string, repeated, tag = "6")]
    pub dependencies: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PerformanceProfile {
    #[prost(uint32, tag = "1")]
    pub avg_latency_ms: u32,
    #[prost(uint32, tag = "2")]
    pub p99_latency_ms: u32,
    #[prost(uint32, tag = "3")]
    pub throughput_rps: u32,
    /// 0.0 to 1.0
    #[prost(float, tag = "4")]
    pub trust_score: f32,
    #[prost(message, optional, tag = "5")]
    pub cost: ::core::option::Option<CostProfile>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CostProfile {
    #[prost(double, tag = "1")]
    pub per_call_usd: f64,
    #[prost(double, tag = "2")]
    pub per_mb_usd: f64,
    #[prost(bool, tag = "3")]
    pub is_free: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TrustLevel {
    /// 0.0 to 1.0
    #[prost(float, tag = "1")]
    pub score: f32,
    /// Remote attestation quote
    #[prost(string, tag = "2")]
    pub attestation: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_verified: bool,
    #[prost(message, optional, tag = "4")]
    pub last_verified_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Root certificates
    #[prost(string, repeated, tag = "5")]
    pub trust_anchors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / Discovery request for finding capabilities
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CapabilityDiscoveryRequest {
    /// Natural language query
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(enumeration = "CapabilityCategory", tag = "2")]
    pub category: i32,
    #[prost(string, repeated, tag = "3")]
    pub required_tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub requirements: ::core::option::Option<PerformanceRequirements>,
    #[prost(message, optional, tag = "5")]
    pub trust_requirements: ::core::option::Option<TrustRequirements>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PerformanceRequirements {
    #[prost(uint32, tag = "1")]
    pub max_latency_ms: u32,
    #[prost(uint32, tag = "2")]
    pub min_throughput_rps: u32,
    #[prost(bool, tag = "3")]
    pub gpu_required: bool,
    #[prost(string, repeated, tag = "4")]
    pub preferred_runtimes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TrustRequirements {
    #[prost(float, tag = "1")]
    pub min_trust_score: f32,
    #[prost(bool, tag = "2")]
    pub require_attestation: bool,
    #[prost(bool, tag = "3")]
    pub require_verification: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CapabilityDiscoveryResponse {
    #[prost(message, repeated, tag = "1")]
    pub matches: ::prost::alloc::vec::Vec<CapabilityMatch>,
    #[prost(string, tag = "2")]
    pub query_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CapabilityMatch {
    #[prost(message, optional, tag = "1")]
    pub capability: ::core::option::Option<Capability>,
    /// How well it matches the query
    #[prost(float, tag = "2")]
    pub relevance_score: f32,
    #[prost(string, repeated, tag = "3")]
    pub matched_tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub recommendation_reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScheduleRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub requirements: ::core::option::Option<CellRequirements>,
    #[prost(message, optional, tag = "3")]
    pub preference: ::core::option::Option<PlacementHint>,
    #[prost(string, tag = "4")]
    pub tenant_id: ::prost::alloc::string::String,
    /// Initial input for the cell
    #[prost(message, optional, tag = "5")]
    pub input: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CellRequirements {
    /// "wasm", "python", etc.
    #[prost(string, tag = "1")]
    pub runtime: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint32, tag = "3")]
    pub vcpus: u32,
    #[prost(uint64, tag = "4")]
    pub memory_bytes: u64,
    #[prost(bool, tag = "5")]
    pub gpu_required: bool,
    #[prost(uint32, tag = "6")]
    pub gpu_memory_mb: u32,
    #[prost(uint32, tag = "7")]
    pub timeout_ms: u32,
    #[prost(bool, tag = "8")]
    pub needs_state_stream: bool,
    #[prost(string, repeated, tag = "9")]
    pub required_capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScheduleResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ExecutionLocation", tag = "3")]
    pub assigned_location: i32,
    #[prost(string, tag = "4")]
    pub assigned_node_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub estimated_start_time_ms: u64,
    #[prost(float, tag = "6")]
    pub cost_estimate_usd: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlacementDecision {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ExecutionLocation", tag = "2")]
    pub location: i32,
    #[prost(string, tag = "3")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "4")]
    pub config_overrides: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "5")]
    pub scheduling_reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FusionGraph {
    #[prost(string, tag = "1")]
    pub graph_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub nodes: ::prost::alloc::vec::Vec<FusionNode>,
    #[prost(message, repeated, tag = "3")]
    pub edges: ::prost::alloc::vec::Vec<FusionEdge>,
    #[prost(message, optional, tag = "4")]
    pub config: ::core::option::Option<FusionConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FusionNode {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "FusionNodeType", tag = "3")]
    pub node_type: i32,
    #[prost(oneof = "fusion_node::Definition", tags = "10, 11, 12")]
    pub definition: ::core::option::Option<fusion_node::Definition>,
}
/// Nested message and enum types in `FusionNode`.
pub mod fusion_node {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Definition {
        #[prost(message, tag = "10")]
        WasmModule(super::WasmModuleDefinition),
        #[prost(message, tag = "11")]
        FunctionChain(super::FunctionChainDefinition),
        #[prost(message, tag = "12")]
        StreamProcessor(super::StreamProcessorDefinition),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WasmModuleDefinition {
    #[prost(string, tag = "1")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub wasm_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub entry_function: ::prost::alloc::string::String,
    /// Required host functions
    #[prost(string, repeated, tag = "4")]
    pub imports: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FunctionChainDefinition {
    #[prost(string, repeated, tag = "1")]
    pub function_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "ChainStrategy", tag = "2")]
    pub strategy: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamProcessorDefinition {
    /// "map", "filter", "reduce", "window"
    #[prost(string, tag = "1")]
    pub processor_type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FusionEdge {
    #[prost(string, tag = "1")]
    pub edge_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub target: ::prost::alloc::string::String,
    #[prost(enumeration = "EdgeKind", tag = "4")]
    pub kind: i32,
    #[prost(string, tag = "5")]
    pub output_mapping: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FusionConfig {
    #[prost(bool, tag = "1")]
    pub enable_streaming: bool,
    #[prost(bool, tag = "2")]
    pub enable_module_merging: bool,
    #[prost(bool, tag = "3")]
    pub enable_live_patch: bool,
    #[prost(uint32, tag = "4")]
    pub max_fusion_modules: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SnapshotRequest {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(enumeration = "SnapshotType", tag = "2")]
    pub snapshot_type: i32,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<SnapshotOptions>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SnapshotOptions {
    #[prost(bool, tag = "1")]
    pub include_memory: bool,
    #[prost(bool, tag = "2")]
    pub include_cpu_state: bool,
    #[prost(bool, tag = "3")]
    pub include_open_handles: bool,
    #[prost(bool, tag = "4")]
    pub compress: bool,
    #[prost(enumeration = "CompressionAlgorithm", tag = "5")]
    pub compression: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SnapshotResponse {
    #[prost(string, tag = "1")]
    pub snapshot_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub size_bytes: u64,
    #[prost(uint64, tag = "4")]
    pub checkpoint_epoch: u64,
    #[prost(bytes = "vec", tag = "5")]
    pub serialized_state: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MigrationRequest {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target_node_id: ::prost::alloc::string::String,
    #[prost(enumeration = "MigrationStrategy", tag = "3")]
    pub strategy: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MigrationResponse {
    #[prost(string, tag = "1")]
    pub migration_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub success: bool,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub downtime_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwarmCommand {
    #[prost(string, tag = "1")]
    pub swarm_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub command_id: ::prost::alloc::string::String,
    #[prost(enumeration = "SwarmCommandType", tag = "3")]
    pub command_type: i32,
    #[prost(message, optional, tag = "4")]
    pub payload: ::core::option::Option<::prost_types::Struct>,
    #[prost(btree_map = "string, string", tag = "5")]
    pub metadata: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwarmState {
    #[prost(string, tag = "1")]
    pub swarm_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub active_cells: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub completed_cells: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(btree_map = "string, string", tag = "4")]
    pub peer_nodes: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "5")]
    pub health: ::core::option::Option<SwarmHealth>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SwarmHealth {
    #[prost(bool, tag = "1")]
    pub is_healthy: bool,
    #[prost(uint32, tag = "2")]
    pub active_count: u32,
    #[prost(uint32, tag = "3")]
    pub total_count: u32,
    #[prost(string, repeated, tag = "4")]
    pub failed_cells: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeshNodeInfo {
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// "cloud", "edge", "browser"
    #[prost(string, tag = "2")]
    pub node_type: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub regions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub resources: ::core::option::Option<NodeResources>,
    #[prost(message, repeated, tag = "5")]
    pub advertised_capabilities: ::prost::alloc::vec::Vec<Capability>,
    #[prost(bool, tag = "6")]
    pub is_available: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeResources {
    #[prost(uint32, tag = "1")]
    pub vcpus: u32,
    #[prost(uint64, tag = "2")]
    pub memory_bytes: u64,
    #[prost(uint32, tag = "3")]
    pub gpu_count: u32,
    #[prost(uint32, tag = "4")]
    pub gpu_memory_mb: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OptimizationFeedback {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub metrics: ::core::option::Option<ExecutionMetrics>,
    #[prost(bool, tag = "3")]
    pub was_successful: bool,
    #[prost(string, tag = "4")]
    pub suggestion_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExecutionMetrics {
    #[prost(uint64, tag = "1")]
    pub duration_ms: u64,
    #[prost(uint64, tag = "2")]
    pub memory_used_bytes: u64,
    #[prost(double, tag = "3")]
    pub cpu_usage_percent: f64,
    #[prost(double, tag = "4")]
    pub cost_usd: f64,
    #[prost(uint32, tag = "5")]
    pub cache_hit_rate: u32,
    #[prost(uint64, tag = "6")]
    pub bytes_transferred: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionPackage {
    #[prost(string, tag = "1")]
    pub manifest_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<PackageMetadata>,
    #[prost(message, repeated, tag = "3")]
    pub modules: ::prost::alloc::vec::Vec<PackageModule>,
    #[prost(message, repeated, tag = "4")]
    pub resources: ::prost::alloc::vec::Vec<PackageResource>,
    #[prost(message, optional, tag = "5")]
    pub signature: ::core::option::Option<PackageSignature>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageMetadata {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// Primary runtime
    #[prost(string, tag = "4")]
    pub runtime: ::prost::alloc::string::String,
    /// Supported languages
    #[prost(string, repeated, tag = "5")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Required capabilities
    #[prost(btree_map = "string, string", tag = "6")]
    pub capabilities: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "7")]
    pub build_info: ::core::option::Option<PackageBuildInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PackageBuildInfo {
    #[prost(string, tag = "1")]
    pub compiler: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub compiler_version: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub build_flags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub built_at: ::core::option::Option<::prost_types::Timestamp>,
    /// "x86_64", "aarch64", "wasm32"
    #[prost(string, tag = "5")]
    pub architecture: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageModule {
    #[prost(string, tag = "1")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// "rust", "python", "typescript"
    #[prost(string, tag = "3")]
    pub language: ::prost::alloc::string::String,
    /// Compiled bytecode
    #[prost(bytes = "vec", tag = "4")]
    pub bytecode: ::prost::alloc::vec::Vec<u8>,
    /// "main", "handler", etc.
    #[prost(string, tag = "5")]
    pub entry_point: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub dependencies: ::prost::alloc::vec::Vec<ModuleDependency>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModuleDependency {
    #[prost(string, tag = "1")]
    pub module_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version_constraint: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageResource {
    #[prost(string, tag = "1")]
    pub resource_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// "config", "data", "model"
    #[prost(string, tag = "3")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(btree_map = "string, string", tag = "5")]
    pub metadata: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PackageSignature {
    /// "ed25519", "rsa4096"
    #[prost(string, tag = "1")]
    pub algorithm: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Base64 encoded
    #[prost(string, tag = "3")]
    pub public_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub signed_at: ::core::option::Option<::prost_types::Timestamp>,
    /// PEM encoded
    #[prost(string, tag = "5")]
    pub certificate_chain: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCellRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<CellConfig>,
    #[prost(bytes = "vec", tag = "3")]
    pub wasm_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub initial_state: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCellResponse {
    #[prost(message, optional, tag = "1")]
    pub cell: ::core::option::Option<ExecutionCell>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCellRequest {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCellResponse {
    #[prost(message, optional, tag = "1")]
    pub cell: ::core::option::Option<ExecutionCell>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCellRequest {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub input: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, optional, tag = "3")]
    pub options: ::core::option::Option<ExecuteCellOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCellOptions {
    #[prost(uint32, tag = "1")]
    pub timeout_ms: u32,
    #[prost(bool, tag = "2")]
    pub enable_streaming: bool,
    #[prost(btree_map = "string, string", tag = "3")]
    pub execution_context: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCellResponse {
    #[prost(string, tag = "1")]
    pub execution_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub output: ::core::option::Option<::prost_types::Struct>,
    #[prost(enumeration = "ExecutionStatus", tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub metrics: ::core::option::Option<ExecutionMetrics>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminateCellRequest {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub force: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminateCellResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateUpdate {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "ValueEncoding", tag = "4")]
    pub encoding: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStateSnapshotRequest {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStateSnapshotResponse {
    #[prost(message, repeated, tag = "1")]
    pub slices: ::prost::alloc::vec::Vec<StateSlice>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterCapabilityRequest {
    #[prost(message, optional, tag = "1")]
    pub capability: ::core::option::Option<Capability>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterCapabilityResponse {
    #[prost(string, tag = "1")]
    pub capability_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvokeCapabilityRequest {
    #[prost(string, tag = "1")]
    pub capability_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub parameters: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvokeCapabilityResponse {
    #[prost(message, optional, tag = "1")]
    pub result: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, optional, tag = "2")]
    pub metrics: ::core::option::Option<ExecutionMetrics>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPlacementSuggestionsRequest {
    #[prost(message, optional, tag = "1")]
    pub requirements: ::core::option::Option<CellRequirements>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPlacementSuggestionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub suggestions: ::prost::alloc::vec::Vec<PlacementDecision>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateFusionGraphRequest {
    #[prost(message, optional, tag = "1")]
    pub graph: ::core::option::Option<FusionGraph>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateFusionGraphResponse {
    #[prost(string, tag = "1")]
    pub graph_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteFusionGraphRequest {
    #[prost(string, tag = "1")]
    pub graph_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub input: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteFusionGraphResponse {
    #[prost(message, optional, tag = "1")]
    pub output: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, optional, tag = "2")]
    pub metrics: ::core::option::Option<ExecutionMetrics>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestoreSnapshotRequest {
    #[prost(string, tag = "1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub snapshot_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RestoreSnapshotResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSwarmRequest {
    #[prost(string, tag = "1")]
    pub swarm_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub initial_cell_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSwarmResponse {
    #[prost(message, optional, tag = "1")]
    pub state: ::core::option::Option<SwarmState>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwarmCommandResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(message, optional, tag = "2")]
    pub result: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSwarmStateRequest {
    #[prost(string, tag = "1")]
    pub swarm_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSwarmStateResponse {
    #[prost(message, optional, tag = "1")]
    pub state: ::core::option::Option<SwarmState>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterNodeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiscoverNodesRequest {
    #[prost(enumeration = "ExecutionLocation", tag = "1")]
    pub location: i32,
    #[prost(string, repeated, tag = "2")]
    pub regions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoverNodesResponse {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<MeshNodeInfo>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CellStatus {
    Unspecified = 0,
    Pending = 1,
    Initializing = 2,
    Running = 3,
    Waiting = 4,
    Migrating = 5,
    Frozen = 6,
    Failed = 7,
    Terminated = 8,
}
impl CellStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CELL_STATUS_UNSPECIFIED",
            Self::Pending => "CELL_STATUS_PENDING",
            Self::Initializing => "CELL_STATUS_INITIALIZING",
            Self::Running => "CELL_STATUS_RUNNING",
            Self::Waiting => "CELL_STATUS_WAITING",
            Self::Migrating => "CELL_STATUS_MIGRATING",
            Self::Frozen => "CELL_STATUS_FROZEN",
            Self::Failed => "CELL_STATUS_FAILED",
            Self::Terminated => "CELL_STATUS_TERMINATED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CELL_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "CELL_STATUS_PENDING" => Some(Self::Pending),
            "CELL_STATUS_INITIALIZING" => Some(Self::Initializing),
            "CELL_STATUS_RUNNING" => Some(Self::Running),
            "CELL_STATUS_WAITING" => Some(Self::Waiting),
            "CELL_STATUS_MIGRATING" => Some(Self::Migrating),
            "CELL_STATUS_FROZEN" => Some(Self::Frozen),
            "CELL_STATUS_FAILED" => Some(Self::Failed),
            "CELL_STATUS_TERMINATED" => Some(Self::Terminated),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionStatus {
    Unspecified = 0,
    Pending = 1,
    Running = 2,
    Completed = 3,
    Failed = 4,
    Cancelled = 5,
}
impl ExecutionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXECUTION_STATUS_UNSPECIFIED",
            Self::Pending => "EXECUTION_STATUS_PENDING",
            Self::Running => "EXECUTION_STATUS_RUNNING",
            Self::Completed => "EXECUTION_STATUS_COMPLETED",
            Self::Failed => "EXECUTION_STATUS_FAILED",
            Self::Cancelled => "EXECUTION_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXECUTION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "EXECUTION_STATUS_PENDING" => Some(Self::Pending),
            "EXECUTION_STATUS_RUNNING" => Some(Self::Running),
            "EXECUTION_STATUS_COMPLETED" => Some(Self::Completed),
            "EXECUTION_STATUS_FAILED" => Some(Self::Failed),
            "EXECUTION_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionLocation {
    Unspecified = 0,
    Cloud = 1,
    Edge = 2,
    Browser = 3,
    Robotic = 4,
    Mobile = 5,
    Iot = 6,
}
impl ExecutionLocation {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXECUTION_LOCATION_UNSPECIFIED",
            Self::Cloud => "EXECUTION_LOCATION_CLOUD",
            Self::Edge => "EXECUTION_LOCATION_EDGE",
            Self::Browser => "EXECUTION_LOCATION_BROWSER",
            Self::Robotic => "EXECUTION_LOCATION_ROBOTIC",
            Self::Mobile => "EXECUTION_LOCATION_MOBILE",
            Self::Iot => "EXECUTION_LOCATION_IOT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXECUTION_LOCATION_UNSPECIFIED" => Some(Self::Unspecified),
            "EXECUTION_LOCATION_CLOUD" => Some(Self::Cloud),
            "EXECUTION_LOCATION_EDGE" => Some(Self::Edge),
            "EXECUTION_LOCATION_BROWSER" => Some(Self::Browser),
            "EXECUTION_LOCATION_ROBOTIC" => Some(Self::Robotic),
            "EXECUTION_LOCATION_MOBILE" => Some(Self::Mobile),
            "EXECUTION_LOCATION_IOT" => Some(Self::Iot),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ValueEncoding {
    Unspecified = 0,
    Json = 1,
    Msgpack = 2,
    Cbor = 3,
    Prost = 4,
    Raw = 5,
}
impl ValueEncoding {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "VALUE_ENCODING_UNSPECIFIED",
            Self::Json => "VALUE_ENCODING_JSON",
            Self::Msgpack => "VALUE_ENCODING_MSGPACK",
            Self::Cbor => "VALUE_ENCODING_CBOR",
            Self::Prost => "VALUE_ENCODING_PROST",
            Self::Raw => "VALUE_ENCODING_RAW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VALUE_ENCODING_UNSPECIFIED" => Some(Self::Unspecified),
            "VALUE_ENCODING_JSON" => Some(Self::Json),
            "VALUE_ENCODING_MSGPACK" => Some(Self::Msgpack),
            "VALUE_ENCODING_CBOR" => Some(Self::Cbor),
            "VALUE_ENCODING_PROST" => Some(Self::Prost),
            "VALUE_ENCODING_RAW" => Some(Self::Raw),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamStrategy {
    Unspecified = 0,
    /// Immediate updates
    Realtime = 1,
    /// Batch updates
    Batch = 2,
    /// Adaptive based on load
    Adaptive = 3,
}
impl StreamStrategy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STREAM_STRATEGY_UNSPECIFIED",
            Self::Realtime => "STREAM_STRATEGY_REALTIME",
            Self::Batch => "STREAM_STRATEGY_BATCH",
            Self::Adaptive => "STREAM_STRATEGY_ADAPTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STREAM_STRATEGY_UNSPECIFIED" => Some(Self::Unspecified),
            "STREAM_STRATEGY_REALTIME" => Some(Self::Realtime),
            "STREAM_STRATEGY_BATCH" => Some(Self::Batch),
            "STREAM_STRATEGY_ADAPTIVE" => Some(Self::Adaptive),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CapabilityCategory {
    Unspecified = 0,
    /// ML inference, LLM, vision, audio
    Ai = 1,
    /// General computation
    Compute = 2,
    /// Database, file, cache
    Storage = 3,
    /// HTTP, websockets, NATS
    Network = 4,
    /// Encryption, signing, hashing
    Crypto = 5,
    /// IoT, robotics, hardware
    Sensors = 6,
    /// OS-level operations
    System = 7,
}
impl CapabilityCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CAPABILITY_CATEGORY_UNSPECIFIED",
            Self::Ai => "CAPABILITY_CATEGORY_AI",
            Self::Compute => "CAPABILITY_CATEGORY_COMPUTE",
            Self::Storage => "CAPABILITY_CATEGORY_STORAGE",
            Self::Network => "CAPABILITY_CATEGORY_NETWORK",
            Self::Crypto => "CAPABILITY_CATEGORY_CRYPTO",
            Self::Sensors => "CAPABILITY_CATEGORY_SENSORS",
            Self::System => "CAPABILITY_CATEGORY_SYSTEM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CAPABILITY_CATEGORY_UNSPECIFIED" => Some(Self::Unspecified),
            "CAPABILITY_CATEGORY_AI" => Some(Self::Ai),
            "CAPABILITY_CATEGORY_COMPUTE" => Some(Self::Compute),
            "CAPABILITY_CATEGORY_STORAGE" => Some(Self::Storage),
            "CAPABILITY_CATEGORY_NETWORK" => Some(Self::Network),
            "CAPABILITY_CATEGORY_CRYPTO" => Some(Self::Crypto),
            "CAPABILITY_CATEGORY_SENSORS" => Some(Self::Sensors),
            "CAPABILITY_CATEGORY_SYSTEM" => Some(Self::System),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FusionNodeType {
    Unspecified = 0,
    Wasm = 1,
    Python = 2,
    FunctionChain = 3,
    StreamMap = 4,
    StreamFilter = 5,
    StreamReduce = 6,
}
impl FusionNodeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FUSION_NODE_TYPE_UNSPECIFIED",
            Self::Wasm => "FUSION_NODE_TYPE_WASM",
            Self::Python => "FUSION_NODE_TYPE_PYTHON",
            Self::FunctionChain => "FUSION_NODE_TYPE_FUNCTION_CHAIN",
            Self::StreamMap => "FUSION_NODE_TYPE_STREAM_MAP",
            Self::StreamFilter => "FUSION_NODE_TYPE_STREAM_FILTER",
            Self::StreamReduce => "FUSION_NODE_TYPE_STREAM_REDUCE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FUSION_NODE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "FUSION_NODE_TYPE_WASM" => Some(Self::Wasm),
            "FUSION_NODE_TYPE_PYTHON" => Some(Self::Python),
            "FUSION_NODE_TYPE_FUNCTION_CHAIN" => Some(Self::FunctionChain),
            "FUSION_NODE_TYPE_STREAM_MAP" => Some(Self::StreamMap),
            "FUSION_NODE_TYPE_STREAM_FILTER" => Some(Self::StreamFilter),
            "FUSION_NODE_TYPE_STREAM_REDUCE" => Some(Self::StreamReduce),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChainStrategy {
    Unspecified = 0,
    Sequential = 1,
    Parallel = 2,
    Conditional = 3,
}
impl ChainStrategy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHAIN_STRATEGY_UNSPECIFIED",
            Self::Sequential => "CHAIN_STRATEGY_SEQUENTIAL",
            Self::Parallel => "CHAIN_STRATEGY_PARALLEL",
            Self::Conditional => "CHAIN_STRATEGY_CONDITIONAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHAIN_STRATEGY_UNSPECIFIED" => Some(Self::Unspecified),
            "CHAIN_STRATEGY_SEQUENTIAL" => Some(Self::Sequential),
            "CHAIN_STRATEGY_PARALLEL" => Some(Self::Parallel),
            "CHAIN_STRATEGY_CONDITIONAL" => Some(Self::Conditional),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EdgeKind {
    Unspecified = 0,
    DataFlow = 1,
    ControlFlow = 2,
    Stream = 3,
}
impl EdgeKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EDGE_KIND_UNSPECIFIED",
            Self::DataFlow => "EDGE_KIND_DATA_FLOW",
            Self::ControlFlow => "EDGE_KIND_CONTROL_FLOW",
            Self::Stream => "EDGE_KIND_STREAM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EDGE_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "EDGE_KIND_DATA_FLOW" => Some(Self::DataFlow),
            "EDGE_KIND_CONTROL_FLOW" => Some(Self::ControlFlow),
            "EDGE_KIND_STREAM" => Some(Self::Stream),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SnapshotType {
    Unspecified = 0,
    /// Clean snapshot
    Fresh = 1,
    /// Delta from last snapshot
    Incremental = 2,
    /// Complete state
    Full = 3,
}
impl SnapshotType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SNAPSHOT_TYPE_UNSPECIFIED",
            Self::Fresh => "SNAPSHOT_TYPE_FRESH",
            Self::Incremental => "SNAPSHOT_TYPE_INCREMENTAL",
            Self::Full => "SNAPSHOT_TYPE_FULL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SNAPSHOT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SNAPSHOT_TYPE_FRESH" => Some(Self::Fresh),
            "SNAPSHOT_TYPE_INCREMENTAL" => Some(Self::Incremental),
            "SNAPSHOT_TYPE_FULL" => Some(Self::Full),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompressionAlgorithm {
    CompressionUnspecified = 0,
    CompressionNone = 1,
    CompressionZstd = 2,
    CompressionLz4 = 3,
}
impl CompressionAlgorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CompressionUnspecified => "COMPRESSION_UNSPECIFIED",
            Self::CompressionNone => "COMPRESSION_NONE",
            Self::CompressionZstd => "COMPRESSION_ZSTD",
            Self::CompressionLz4 => "COMPRESSION_LZ4",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPRESSION_UNSPECIFIED" => Some(Self::CompressionUnspecified),
            "COMPRESSION_NONE" => Some(Self::CompressionNone),
            "COMPRESSION_ZSTD" => Some(Self::CompressionZstd),
            "COMPRESSION_LZ4" => Some(Self::CompressionLz4),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MigrationStrategy {
    Unspecified = 0,
    /// Pre-copy memory pages
    PreCopy = 1,
    /// Stop, copy, resume
    StopCopy = 2,
    /// Live migration
    Live = 3,
}
impl MigrationStrategy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MIGRATION_STRATEGY_UNSPECIFIED",
            Self::PreCopy => "MIGRATION_STRATEGY_PRE_COPY",
            Self::StopCopy => "MIGRATION_STRATEGY_STOP_COPY",
            Self::Live => "MIGRATION_STRATEGY_LIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MIGRATION_STRATEGY_UNSPECIFIED" => Some(Self::Unspecified),
            "MIGRATION_STRATEGY_PRE_COPY" => Some(Self::PreCopy),
            "MIGRATION_STRATEGY_STOP_COPY" => Some(Self::StopCopy),
            "MIGRATION_STRATEGY_LIVE" => Some(Self::Live),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SwarmCommandType {
    SwarmCommandUnspecified = 0,
    /// Spawn new cell
    SwarmCommandSpawn = 1,
    /// Delegate work
    SwarmCommandDelegate = 2,
    /// Coordinate with peers
    SwarmCommandCoordinate = 3,
    /// Migrate to different node
    SwarmCommandMigrate = 4,
    /// Graceful shutdown
    SwarmCommandTerminate = 5,
    /// Self-heal
    SwarmCommandHeal = 6,
}
impl SwarmCommandType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SwarmCommandUnspecified => "SWARM_COMMAND_UNSPECIFIED",
            Self::SwarmCommandSpawn => "SWARM_COMMAND_SPAWN",
            Self::SwarmCommandDelegate => "SWARM_COMMAND_DELEGATE",
            Self::SwarmCommandCoordinate => "SWARM_COMMAND_COORDINATE",
            Self::SwarmCommandMigrate => "SWARM_COMMAND_MIGRATE",
            Self::SwarmCommandTerminate => "SWARM_COMMAND_TERMINATE",
            Self::SwarmCommandHeal => "SWARM_COMMAND_HEAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SWARM_COMMAND_UNSPECIFIED" => Some(Self::SwarmCommandUnspecified),
            "SWARM_COMMAND_SPAWN" => Some(Self::SwarmCommandSpawn),
            "SWARM_COMMAND_DELEGATE" => Some(Self::SwarmCommandDelegate),
            "SWARM_COMMAND_COORDINATE" => Some(Self::SwarmCommandCoordinate),
            "SWARM_COMMAND_MIGRATE" => Some(Self::SwarmCommandMigrate),
            "SWARM_COMMAND_TERMINATE" => Some(Self::SwarmCommandTerminate),
            "SWARM_COMMAND_HEAL" => Some(Self::SwarmCommandHeal),
            _ => None,
        }
    }
}
