export const NAV_LABEL_KEYS: Record<string, string> = {
  'Discover': 'nav.discover',
  'Hot': 'nav.hot',
  'Trending': 'nav.trending',
  'New': 'nav.new',
  'Notifications': 'nav.notifications',
  'Conversations': 'nav.conversations',
  'My Functions': 'nav.myFunctions',
  'AI Composer': 'nav.aiComposer',
  'Graph Editor': 'nav.graphEditor',
  'State': 'nav.state',
  'Apps': 'nav.apps',
  'Agents': 'nav.agents',
  'Providers': 'nav.providers',
  'SDK': 'nav.sdk',
  'Secrets': 'nav.secrets',
  'API Keys': 'nav.apiKeys',
  'Connectors': 'nav.connectors',
  'Bundles': 'nav.bundles',
  'Analytics': 'nav.analytics',
  'Usage': 'nav.usage',
  'Wallet': 'nav.wallet',
  'Status': 'nav.status',
  'Time Machine': 'nav.timeMachine',
  'Function Consciousness': 'nav.consciousness',
  'Evolution': 'nav.evolution',
  'Marketplace': 'nav.marketplace',
  'Brain': 'nav.brain',
  'Memory': 'nav.memory',
  'Teams': 'nav.teams',
  'Decisions': 'nav.decisions',
  'State Fabric': 'nav.stateFabric',
  'GitHub Import': 'nav.githubImport',
  'Settings': 'nav.settings',
  'Support': 'nav.support',
  'Recent': 'nav.recent',
  'Getting Started': 'nav.gettingStarted',
  'Sign Out': 'nav.signOut',
  'Search Results': 'nav.search',
  'Favorites': 'nav.favorites',
};
