/**
 * UI Package Adapters
 * Central export for all UI package type adapters
 */

// Collaboration adapters
export {
  adaptCollaboratorPresence,
  adaptCollaboratorPresenceList,
  adaptVoiceSession,
  adaptExecutionBookmark,
  adaptGraphNode,
  adaptGraphEdge,
  adaptAnnotation,
  adaptActivityItem,
  adaptMemoryCard,
  adaptReviewComment,
  adaptReviewSession,
  adaptPromptSegment,
  adaptPairProgrammingSession,
  adaptTaskAssignee,
  adaptTaskAssignment,
  adaptTaskAssignmentList,
  adaptPromptVersion,
  adaptPromptVersionList,
  adaptPairSession,
  adaptComment,
  adaptCommentListToReviewSession,
  adaptGraphEdit,
  adaptExecutionToRecording,
  adaptExecutionToBookmarks,
  adaptCollabEvent,
  adaptCollabEventList,
  adaptExecutionToTask,
  adaptExecutionListToTasks,
  type PromptVersion,
  type PairSession,
  type Comment,
  type GraphEdit,
  type Execution,
  type CollabEvent,
} from './ui-collaboration-adapters';

// Data visualization adapters
export {
  adaptStreamingLineData,
  adaptScatterData,
  adaptTopologyNodes,
  adaptSunburstData,
  adaptTreemapData,
  adaptWaterfallData,
  adaptCostData,
  adaptClusterData,
  extractClusters,
  adaptAgentNodes,
  adaptAgentEdges,
  adaptCircularFlowConnections,
  type StreamingLineData,
  type ScatterDataInput,
  type TopologyNodeInput,
  type SunburstDataInput,
  type TreemapDataInput,
  type WaterfallDataInput,
  type CostDataInput,
  type ClusterDataInput,
  type AgentNodeInput,
  type AgentEdgeInput,
} from './ui-data-visualization-adapters';

// Code intelligence adapters
export {
  adaptCodePosition,
  adaptCodeRange,
  adaptDependencyNode,
  adaptDependencyEdge,
  adaptRefactorOpportunity,
  adaptSearchResult,
  adaptRiskIndicator,
  adaptImportNode,
  adaptImportEdge,
  adaptWatchExpression,
  adaptAICompletion,
  adaptSimulationChange,
  adaptRefactorSimulation,
  adaptFileOwnership,
  type PositionInput,
  type RangeInput,
  type DependencyNodeInput,
  type DependencyEdgeInput,
  type DiffFileInput,
  type ArchitectureNodeInput,
  type RefactorOpportunityInput,
  type SearchResultInput,
  type LineageNodeInput,
  type RiskIndicatorInput,
  type ImportNodeInput,
  type ImportEdgeInput,
  type WatchExpressionInput,
  type AICompletionInput,
  type SimulationChangeInput,
  type RefactorSimulationInput,
  type ArchitectureConstraintInput,
  type FileOwnershipInput,
} from './ui-code-intelligence-adapters';

// Simulation adapters
export {
  adaptSimulationConfig,
  adaptSimulationStatus,
  adaptSimulationMetrics,
  adaptStudioConfigFromUI,
  adaptForecastData,
  adaptFailureNodes,
  adaptLatencyData,
  adaptCostProjections,
  adaptScalingProjections,
  adaptBehaviorPredictions,
  adaptStressTestResults,
  createDefaultStressTestConfig,
  type ForecastDataInput,
  type FailureNodeInput,
  type LatencyDataPointInput,
  type CostEstimateInput,
  type ScalingProjectionInput,
  type AgentPredictionInput,
  type UISimulationConfig,
  type UISimulationMetrics,
  type UISimulationStatus,
  type UIForecastDataPoint,
  type UIFailureNode,
  type UILatencyDataPoint,
  type UICostProjection,
  type UIScalingProjection,
  type UIBehaviorPrediction,
  type UIStressTestResult,
  type UIHallucinationRisk,
} from './ui-simulation-adapters';
