// Code generated by mockery v2.53.6. DO NOT EDIT.

package dre

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	registry "github.com/functionfly/functionfly/internal/storage/registry"

	time "time"

	uuid "github.com/google/uuid"
)

// MockDRERepository is an autogenerated mock type for the DRERepository type
type MockDRERepository struct {
	mock.Mock
}

type MockDRERepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDRERepository) EXPECT() *MockDRERepository_Expecter {
	return &MockDRERepository_Expecter{mock: &_m.Mock}
}

// GetCertificateByExecutionID provides a mock function with given fields: executionID
func (_m *MockDRERepository) GetCertificateByExecutionID(executionID uuid.UUID) (*registry.ExecutionCertificate, error) {
	ret := _m.Called(executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateByExecutionID")
	}

	var r0 *registry.ExecutionCertificate
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*registry.ExecutionCertificate, error)); ok {
		return rf(executionID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *registry.ExecutionCertificate); ok {
		r0 = rf(executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.ExecutionCertificate)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(executionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetCertificateByExecutionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateByExecutionID'
type MockDRERepository_GetCertificateByExecutionID_Call struct {
	*mock.Call
}

// GetCertificateByExecutionID is a helper method to define mock.On call
//   - executionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetCertificateByExecutionID(executionID interface{}) *MockDRERepository_GetCertificateByExecutionID_Call {
	return &MockDRERepository_GetCertificateByExecutionID_Call{Call: _e.mock.On("GetCertificateByExecutionID", executionID)}
}

func (_c *MockDRERepository_GetCertificateByExecutionID_Call) Run(run func(executionID uuid.UUID)) *MockDRERepository_GetCertificateByExecutionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockDRERepository_GetCertificateByExecutionID_Call) Return(_a0 *registry.ExecutionCertificate, _a1 error) *MockDRERepository_GetCertificateByExecutionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetCertificateByExecutionID_Call) RunAndReturn(run func(uuid.UUID) (*registry.ExecutionCertificate, error)) *MockDRERepository_GetCertificateByExecutionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateByID provides a mock function with given fields: certID
func (_m *MockDRERepository) GetCertificateByID(certID string) (*registry.ExecutionCertificate, error) {
	ret := _m.Called(certID)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateByID")
	}

	var r0 *registry.ExecutionCertificate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*registry.ExecutionCertificate, error)); ok {
		return rf(certID)
	}
	if rf, ok := ret.Get(0).(func(string) *registry.ExecutionCertificate); ok {
		r0 = rf(certID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.ExecutionCertificate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(certID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetCertificateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateByID'
type MockDRERepository_GetCertificateByID_Call struct {
	*mock.Call
}

// GetCertificateByID is a helper method to define mock.On call
//   - certID string
func (_e *MockDRERepository_Expecter) GetCertificateByID(certID interface{}) *MockDRERepository_GetCertificateByID_Call {
	return &MockDRERepository_GetCertificateByID_Call{Call: _e.mock.On("GetCertificateByID", certID)}
}

func (_c *MockDRERepository_GetCertificateByID_Call) Run(run func(certID string)) *MockDRERepository_GetCertificateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDRERepository_GetCertificateByID_Call) Return(_a0 *registry.ExecutionCertificate, _a1 error) *MockDRERepository_GetCertificateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetCertificateByID_Call) RunAndReturn(run func(string) (*registry.ExecutionCertificate, error)) *MockDRERepository_GetCertificateByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificatesByFunctionID provides a mock function with given fields: functionID, limit, offset
func (_m *MockDRERepository) GetCertificatesByFunctionID(functionID uuid.UUID, limit int, offset int) ([]*registry.ExecutionCertificate, error) {
	ret := _m.Called(functionID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificatesByFunctionID")
	}

	var r0 []*registry.ExecutionCertificate
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]*registry.ExecutionCertificate, error)); ok {
		return rf(functionID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []*registry.ExecutionCertificate); ok {
		r0 = rf(functionID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*registry.ExecutionCertificate)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) error); ok {
		r1 = rf(functionID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetCertificatesByFunctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificatesByFunctionID'
type MockDRERepository_GetCertificatesByFunctionID_Call struct {
	*mock.Call
}

// GetCertificatesByFunctionID is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockDRERepository_Expecter) GetCertificatesByFunctionID(functionID interface{}, limit interface{}, offset interface{}) *MockDRERepository_GetCertificatesByFunctionID_Call {
	return &MockDRERepository_GetCertificatesByFunctionID_Call{Call: _e.mock.On("GetCertificatesByFunctionID", functionID, limit, offset)}
}

func (_c *MockDRERepository_GetCertificatesByFunctionID_Call) Run(run func(functionID uuid.UUID, limit int, offset int)) *MockDRERepository_GetCertificatesByFunctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockDRERepository_GetCertificatesByFunctionID_Call) Return(_a0 []*registry.ExecutionCertificate, _a1 error) *MockDRERepository_GetCertificatesByFunctionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetCertificatesByFunctionID_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]*registry.ExecutionCertificate, error)) *MockDRERepository_GetCertificatesByFunctionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriftReportsByFunctionID provides a mock function with given fields: functionID, limit, offset
func (_m *MockDRERepository) GetDriftReportsByFunctionID(functionID uuid.UUID, limit int, offset int) ([]*registry.DriftReportRecord, error) {
	ret := _m.Called(functionID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetDriftReportsByFunctionID")
	}

	var r0 []*registry.DriftReportRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]*registry.DriftReportRecord, error)); ok {
		return rf(functionID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int) []*registry.DriftReportRecord); ok {
		r0 = rf(functionID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*registry.DriftReportRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int) error); ok {
		r1 = rf(functionID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetDriftReportsByFunctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriftReportsByFunctionID'
type MockDRERepository_GetDriftReportsByFunctionID_Call struct {
	*mock.Call
}

// GetDriftReportsByFunctionID is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockDRERepository_Expecter) GetDriftReportsByFunctionID(functionID interface{}, limit interface{}, offset interface{}) *MockDRERepository_GetDriftReportsByFunctionID_Call {
	return &MockDRERepository_GetDriftReportsByFunctionID_Call{Call: _e.mock.On("GetDriftReportsByFunctionID", functionID, limit, offset)}
}

func (_c *MockDRERepository_GetDriftReportsByFunctionID_Call) Run(run func(functionID uuid.UUID, limit int, offset int)) *MockDRERepository_GetDriftReportsByFunctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockDRERepository_GetDriftReportsByFunctionID_Call) Return(_a0 []*registry.DriftReportRecord, _a1 error) *MockDRERepository_GetDriftReportsByFunctionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetDriftReportsByFunctionID_Call) RunAndReturn(run func(uuid.UUID, int, int) ([]*registry.DriftReportRecord, error)) *MockDRERepository_GetDriftReportsByFunctionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionTimelineBuckets provides a mock function with given fields: functionID, from, to, metric
func (_m *MockDRERepository) GetExecutionTimelineBuckets(functionID uuid.UUID, from time.Time, to time.Time, metric string) ([]registry.ExecutionTimelineBucket, error) {
	ret := _m.Called(functionID, from, to, metric)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionTimelineBuckets")
	}

	var r0 []registry.ExecutionTimelineBucket
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time, string) ([]registry.ExecutionTimelineBucket, error)); ok {
		return rf(functionID, from, to, metric)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time, string) []registry.ExecutionTimelineBucket); ok {
		r0 = rf(functionID, from, to, metric)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]registry.ExecutionTimelineBucket)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time, string) error); ok {
		r1 = rf(functionID, from, to, metric)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetExecutionTimelineBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionTimelineBuckets'
type MockDRERepository_GetExecutionTimelineBuckets_Call struct {
	*mock.Call
}

// GetExecutionTimelineBuckets is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - from time.Time
//   - to time.Time
//   - metric string
func (_e *MockDRERepository_Expecter) GetExecutionTimelineBuckets(functionID interface{}, from interface{}, to interface{}, metric interface{}) *MockDRERepository_GetExecutionTimelineBuckets_Call {
	return &MockDRERepository_GetExecutionTimelineBuckets_Call{Call: _e.mock.On("GetExecutionTimelineBuckets", functionID, from, to, metric)}
}

func (_c *MockDRERepository_GetExecutionTimelineBuckets_Call) Run(run func(functionID uuid.UUID, from time.Time, to time.Time, metric string)) *MockDRERepository_GetExecutionTimelineBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(time.Time), args[2].(time.Time), args[3].(string))
	})
	return _c
}

func (_c *MockDRERepository_GetExecutionTimelineBuckets_Call) Return(_a0 []registry.ExecutionTimelineBucket, _a1 error) *MockDRERepository_GetExecutionTimelineBuckets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetExecutionTimelineBuckets_Call) RunAndReturn(run func(uuid.UUID, time.Time, time.Time, string) ([]registry.ExecutionTimelineBucket, error)) *MockDRERepository_GetExecutionTimelineBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionByAuthorName provides a mock function with given fields: ctx, author, name
func (_m *MockDRERepository) GetFunctionByAuthorName(ctx context.Context, author string, name string) (*registry.RegistryFunction, error) {
	ret := _m.Called(ctx, author, name)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionByAuthorName")
	}

	var r0 *registry.RegistryFunction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*registry.RegistryFunction, error)); ok {
		return rf(ctx, author, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *registry.RegistryFunction); ok {
		r0 = rf(ctx, author, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryFunction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, author, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetFunctionByAuthorName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionByAuthorName'
type MockDRERepository_GetFunctionByAuthorName_Call struct {
	*mock.Call
}

// GetFunctionByAuthorName is a helper method to define mock.On call
//   - ctx context.Context
//   - author string
//   - name string
func (_e *MockDRERepository_Expecter) GetFunctionByAuthorName(ctx interface{}, author interface{}, name interface{}) *MockDRERepository_GetFunctionByAuthorName_Call {
	return &MockDRERepository_GetFunctionByAuthorName_Call{Call: _e.mock.On("GetFunctionByAuthorName", ctx, author, name)}
}

func (_c *MockDRERepository_GetFunctionByAuthorName_Call) Run(run func(ctx context.Context, author string, name string)) *MockDRERepository_GetFunctionByAuthorName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDRERepository_GetFunctionByAuthorName_Call) Return(_a0 *registry.RegistryFunction, _a1 error) *MockDRERepository_GetFunctionByAuthorName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetFunctionByAuthorName_Call) RunAndReturn(run func(context.Context, string, string) (*registry.RegistryFunction, error)) *MockDRERepository_GetFunctionByAuthorName_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionByID provides a mock function with given fields: ctx, id
func (_m *MockDRERepository) GetFunctionByID(ctx context.Context, id uuid.UUID) (*registry.RegistryFunction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionByID")
	}

	var r0 *registry.RegistryFunction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*registry.RegistryFunction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *registry.RegistryFunction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryFunction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetFunctionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionByID'
type MockDRERepository_GetFunctionByID_Call struct {
	*mock.Call
}

// GetFunctionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDRERepository_Expecter) GetFunctionByID(ctx interface{}, id interface{}) *MockDRERepository_GetFunctionByID_Call {
	return &MockDRERepository_GetFunctionByID_Call{Call: _e.mock.On("GetFunctionByID", ctx, id)}
}

func (_c *MockDRERepository_GetFunctionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDRERepository_GetFunctionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDRERepository_GetFunctionByID_Call) Return(_a0 *registry.RegistryFunction, _a1 error) *MockDRERepository_GetFunctionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetFunctionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*registry.RegistryFunction, error)) *MockDRERepository_GetFunctionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionVersion provides a mock function with given fields: functionID, version
func (_m *MockDRERepository) GetFunctionVersion(functionID uuid.UUID, version string) (*registry.RegistryFunctionVersion, error) {
	ret := _m.Called(functionID, version)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionVersion")
	}

	var r0 *registry.RegistryFunctionVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (*registry.RegistryFunctionVersion, error)); ok {
		return rf(functionID, version)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *registry.RegistryFunctionVersion); ok {
		r0 = rf(functionID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryFunctionVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(functionID, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetFunctionVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionVersion'
type MockDRERepository_GetFunctionVersion_Call struct {
	*mock.Call
}

// GetFunctionVersion is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - version string
func (_e *MockDRERepository_Expecter) GetFunctionVersion(functionID interface{}, version interface{}) *MockDRERepository_GetFunctionVersion_Call {
	return &MockDRERepository_GetFunctionVersion_Call{Call: _e.mock.On("GetFunctionVersion", functionID, version)}
}

func (_c *MockDRERepository_GetFunctionVersion_Call) Run(run func(functionID uuid.UUID, version string)) *MockDRERepository_GetFunctionVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *MockDRERepository_GetFunctionVersion_Call) Return(_a0 *registry.RegistryFunctionVersion, _a1 error) *MockDRERepository_GetFunctionVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetFunctionVersion_Call) RunAndReturn(run func(uuid.UUID, string) (*registry.RegistryFunctionVersion, error)) *MockDRERepository_GetFunctionVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestFunctionVersion provides a mock function with given fields: functionID
func (_m *MockDRERepository) GetLatestFunctionVersion(functionID uuid.UUID) (*registry.RegistryFunctionVersion, error) {
	ret := _m.Called(functionID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestFunctionVersion")
	}

	var r0 *registry.RegistryFunctionVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*registry.RegistryFunctionVersion, error)); ok {
		return rf(functionID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *registry.RegistryFunctionVersion); ok {
		r0 = rf(functionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryFunctionVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(functionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetLatestFunctionVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestFunctionVersion'
type MockDRERepository_GetLatestFunctionVersion_Call struct {
	*mock.Call
}

// GetLatestFunctionVersion is a helper method to define mock.On call
//   - functionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetLatestFunctionVersion(functionID interface{}) *MockDRERepository_GetLatestFunctionVersion_Call {
	return &MockDRERepository_GetLatestFunctionVersion_Call{Call: _e.mock.On("GetLatestFunctionVersion", functionID)}
}

func (_c *MockDRERepository_GetLatestFunctionVersion_Call) Run(run func(functionID uuid.UUID)) *MockDRERepository_GetLatestFunctionVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockDRERepository_GetLatestFunctionVersion_Call) Return(_a0 *registry.RegistryFunctionVersion, _a1 error) *MockDRERepository_GetLatestFunctionVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetLatestFunctionVersion_Call) RunAndReturn(run func(uuid.UUID) (*registry.RegistryFunctionVersion, error)) *MockDRERepository_GetLatestFunctionVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetMEGByExecutionID provides a mock function with given fields: executionID
func (_m *MockDRERepository) GetMEGByExecutionID(executionID uuid.UUID) (*registry.MEGRecord, error) {
	ret := _m.Called(executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMEGByExecutionID")
	}

	var r0 *registry.MEGRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*registry.MEGRecord, error)); ok {
		return rf(executionID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *registry.MEGRecord); ok {
		r0 = rf(executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.MEGRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(executionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetMEGByExecutionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMEGByExecutionID'
type MockDRERepository_GetMEGByExecutionID_Call struct {
	*mock.Call
}

// GetMEGByExecutionID is a helper method to define mock.On call
//   - executionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetMEGByExecutionID(executionID interface{}) *MockDRERepository_GetMEGByExecutionID_Call {
	return &MockDRERepository_GetMEGByExecutionID_Call{Call: _e.mock.On("GetMEGByExecutionID", executionID)}
}

func (_c *MockDRERepository_GetMEGByExecutionID_Call) Run(run func(executionID uuid.UUID)) *MockDRERepository_GetMEGByExecutionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockDRERepository_GetMEGByExecutionID_Call) Return(_a0 *registry.MEGRecord, _a1 error) *MockDRERepository_GetMEGByExecutionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetMEGByExecutionID_Call) RunAndReturn(run func(uuid.UUID) (*registry.MEGRecord, error)) *MockDRERepository_GetMEGByExecutionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMEGByExecutionRootHash provides a mock function with given fields: hash
func (_m *MockDRERepository) GetMEGByExecutionRootHash(hash string) (*registry.MEGRecord, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetMEGByExecutionRootHash")
	}

	var r0 *registry.MEGRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*registry.MEGRecord, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(string) *registry.MEGRecord); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.MEGRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetMEGByExecutionRootHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMEGByExecutionRootHash'
type MockDRERepository_GetMEGByExecutionRootHash_Call struct {
	*mock.Call
}

// GetMEGByExecutionRootHash is a helper method to define mock.On call
//   - hash string
func (_e *MockDRERepository_Expecter) GetMEGByExecutionRootHash(hash interface{}) *MockDRERepository_GetMEGByExecutionRootHash_Call {
	return &MockDRERepository_GetMEGByExecutionRootHash_Call{Call: _e.mock.On("GetMEGByExecutionRootHash", hash)}
}

func (_c *MockDRERepository_GetMEGByExecutionRootHash_Call) Run(run func(hash string)) *MockDRERepository_GetMEGByExecutionRootHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDRERepository_GetMEGByExecutionRootHash_Call) Return(_a0 *registry.MEGRecord, _a1 error) *MockDRERepository_GetMEGByExecutionRootHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetMEGByExecutionRootHash_Call) RunAndReturn(run func(string) (*registry.MEGRecord, error)) *MockDRERepository_GetMEGByExecutionRootHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetMEGRecordsByFunctionID provides a mock function with given fields: functionID, limit, offset, filters
func (_m *MockDRERepository) GetMEGRecordsByFunctionID(functionID uuid.UUID, limit int, offset int, filters registry.MEGRecordFilters) ([]*registry.MEGRecord, int64, error) {
	ret := _m.Called(functionID, limit, offset, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetMEGRecordsByFunctionID")
	}

	var r0 []*registry.MEGRecord
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, registry.MEGRecordFilters) ([]*registry.MEGRecord, int64, error)); ok {
		return rf(functionID, limit, offset, filters)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, int, int, registry.MEGRecordFilters) []*registry.MEGRecord); ok {
		r0 = rf(functionID, limit, offset, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*registry.MEGRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, int, int, registry.MEGRecordFilters) int64); ok {
		r1 = rf(functionID, limit, offset, filters)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, int, int, registry.MEGRecordFilters) error); ok {
		r2 = rf(functionID, limit, offset, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDRERepository_GetMEGRecordsByFunctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMEGRecordsByFunctionID'
type MockDRERepository_GetMEGRecordsByFunctionID_Call struct {
	*mock.Call
}

// GetMEGRecordsByFunctionID is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - limit int
//   - offset int
//   - filters registry.MEGRecordFilters
func (_e *MockDRERepository_Expecter) GetMEGRecordsByFunctionID(functionID interface{}, limit interface{}, offset interface{}, filters interface{}) *MockDRERepository_GetMEGRecordsByFunctionID_Call {
	return &MockDRERepository_GetMEGRecordsByFunctionID_Call{Call: _e.mock.On("GetMEGRecordsByFunctionID", functionID, limit, offset, filters)}
}

func (_c *MockDRERepository_GetMEGRecordsByFunctionID_Call) Run(run func(functionID uuid.UUID, limit int, offset int, filters registry.MEGRecordFilters)) *MockDRERepository_GetMEGRecordsByFunctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(int), args[2].(int), args[3].(registry.MEGRecordFilters))
	})
	return _c
}

func (_c *MockDRERepository_GetMEGRecordsByFunctionID_Call) Return(_a0 []*registry.MEGRecord, _a1 int64, _a2 error) *MockDRERepository_GetMEGRecordsByFunctionID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDRERepository_GetMEGRecordsByFunctionID_Call) RunAndReturn(run func(uuid.UUID, int, int, registry.MEGRecordFilters) ([]*registry.MEGRecord, int64, error)) *MockDRERepository_GetMEGRecordsByFunctionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreatePassport provides a mock function with given fields: functionID
func (_m *MockDRERepository) GetOrCreatePassport(functionID uuid.UUID) (*registry.ExecutionPassport, error) {
	ret := _m.Called(functionID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreatePassport")
	}

	var r0 *registry.ExecutionPassport
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*registry.ExecutionPassport, error)); ok {
		return rf(functionID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *registry.ExecutionPassport); ok {
		r0 = rf(functionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.ExecutionPassport)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(functionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetOrCreatePassport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreatePassport'
type MockDRERepository_GetOrCreatePassport_Call struct {
	*mock.Call
}

// GetOrCreatePassport is a helper method to define mock.On call
//   - functionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetOrCreatePassport(functionID interface{}) *MockDRERepository_GetOrCreatePassport_Call {
	return &MockDRERepository_GetOrCreatePassport_Call{Call: _e.mock.On("GetOrCreatePassport", functionID)}
}

func (_c *MockDRERepository_GetOrCreatePassport_Call) Run(run func(functionID uuid.UUID)) *MockDRERepository_GetOrCreatePassport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockDRERepository_GetOrCreatePassport_Call) Return(_a0 *registry.ExecutionPassport, _a1 error) *MockDRERepository_GetOrCreatePassport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetOrCreatePassport_Call) RunAndReturn(run func(uuid.UUID) (*registry.ExecutionPassport, error)) *MockDRERepository_GetOrCreatePassport_Call {
	_c.Call.Return(run)
	return _c
}

// GetPassportByFunctionID provides a mock function with given fields: functionID
func (_m *MockDRERepository) GetPassportByFunctionID(functionID uuid.UUID) (*registry.ExecutionPassport, error) {
	ret := _m.Called(functionID)

	if len(ret) == 0 {
		panic("no return value specified for GetPassportByFunctionID")
	}

	var r0 *registry.ExecutionPassport
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*registry.ExecutionPassport, error)); ok {
		return rf(functionID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *registry.ExecutionPassport); ok {
		r0 = rf(functionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.ExecutionPassport)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(functionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDRERepository_GetPassportByFunctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPassportByFunctionID'
type MockDRERepository_GetPassportByFunctionID_Call struct {
	*mock.Call
}

// GetPassportByFunctionID is a helper method to define mock.On call
//   - functionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetPassportByFunctionID(functionID interface{}) *MockDRERepository_GetPassportByFunctionID_Call {
	return &MockDRERepository_GetPassportByFunctionID_Call{Call: _e.mock.On("GetPassportByFunctionID", functionID)}
}

func (_c *MockDRERepository_GetPassportByFunctionID_Call) Run(run func(functionID uuid.UUID)) *MockDRERepository_GetPassportByFunctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockDRERepository_GetPassportByFunctionID_Call) Return(_a0 *registry.ExecutionPassport, _a1 error) *MockDRERepository_GetPassportByFunctionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDRERepository_GetPassportByFunctionID_Call) RunAndReturn(run func(uuid.UUID) (*registry.ExecutionPassport, error)) *MockDRERepository_GetPassportByFunctionID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertificateAnchored provides a mock function with given fields: certID, anchored, anchorChain, anchorTxHash, anchorMerkleRoot, anchorBlockNumber, anchoredAt
func (_m *MockDRERepository) UpdateCertificateAnchored(certID string, anchored bool, anchorChain string, anchorTxHash string, anchorMerkleRoot string, anchorBlockNumber int64, anchoredAt *time.Time) error {
	ret := _m.Called(certID, anchored, anchorChain, anchorTxHash, anchorMerkleRoot, anchorBlockNumber, anchoredAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificateAnchored")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool, string, string, string, int64, *time.Time) error); ok {
		r0 = rf(certID, anchored, anchorChain, anchorTxHash, anchorMerkleRoot, anchorBlockNumber, anchoredAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDRERepository_UpdateCertificateAnchored_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertificateAnchored'
type MockDRERepository_UpdateCertificateAnchored_Call struct {
	*mock.Call
}

// UpdateCertificateAnchored is a helper method to define mock.On call
//   - certID string
//   - anchored bool
//   - anchorChain string
//   - anchorTxHash string
//   - anchorMerkleRoot string
//   - anchorBlockNumber int64
//   - anchoredAt *time.Time
func (_e *MockDRERepository_Expecter) UpdateCertificateAnchored(certID interface{}, anchored interface{}, anchorChain interface{}, anchorTxHash interface{}, anchorMerkleRoot interface{}, anchorBlockNumber interface{}, anchoredAt interface{}) *MockDRERepository_UpdateCertificateAnchored_Call {
	return &MockDRERepository_UpdateCertificateAnchored_Call{Call: _e.mock.On("UpdateCertificateAnchored", certID, anchored, anchorChain, anchorTxHash, anchorMerkleRoot, anchorBlockNumber, anchoredAt)}
}

func (_c *MockDRERepository_UpdateCertificateAnchored_Call) Run(run func(certID string, anchored bool, anchorChain string, anchorTxHash string, anchorMerkleRoot string, anchorBlockNumber int64, anchoredAt *time.Time)) *MockDRERepository_UpdateCertificateAnchored_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool), args[2].(string), args[3].(string), args[4].(string), args[5].(int64), args[6].(*time.Time))
	})
	return _c
}

func (_c *MockDRERepository_UpdateCertificateAnchored_Call) Return(_a0 error) *MockDRERepository_UpdateCertificateAnchored_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDRERepository_UpdateCertificateAnchored_Call) RunAndReturn(run func(string, bool, string, string, string, int64, *time.Time) error) *MockDRERepository_UpdateCertificateAnchored_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDRERepository creates a new instance of MockDRERepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDRERepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDRERepository {
	mock := &MockDRERepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
