// Code generated by mockery v2.53.6. DO NOT EDIT.

package dre

import (
	context "context"

	cert "github.com/functionfly/functionfly/internal/dre/cert"

	mock "github.com/stretchr/testify/mock"
)

// MockAnchorServicer is an autogenerated mock type for the AnchorServicer type
type MockAnchorServicer struct {
	mock.Mock
}

type MockAnchorServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnchorServicer) EXPECT() *MockAnchorServicer_Expecter {
	return &MockAnchorServicer_Expecter{mock: &_m.Mock}
}

// Anchor provides a mock function with given fields: ctx, req
func (_m *MockAnchorServicer) Anchor(ctx context.Context, req *cert.AnchorRequest) (*cert.AnchorReceipt, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Anchor")
	}

	var r0 *cert.AnchorReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *cert.AnchorRequest) (*cert.AnchorReceipt, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *cert.AnchorRequest) *cert.AnchorReceipt); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cert.AnchorReceipt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *cert.AnchorRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAnchorServicer_Anchor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Anchor'
type MockAnchorServicer_Anchor_Call struct {
	*mock.Call
}

// Anchor is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cert.AnchorRequest
func (_e *MockAnchorServicer_Expecter) Anchor(ctx interface{}, req interface{}) *MockAnchorServicer_Anchor_Call {
	return &MockAnchorServicer_Anchor_Call{Call: _e.mock.On("Anchor", ctx, req)}
}

func (_c *MockAnchorServicer_Anchor_Call) Run(run func(ctx context.Context, req *cert.AnchorRequest)) *MockAnchorServicer_Anchor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*cert.AnchorRequest))
	})
	return _c
}

func (_c *MockAnchorServicer_Anchor_Call) Return(_a0 *cert.AnchorReceipt, _a1 error) *MockAnchorServicer_Anchor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAnchorServicer_Anchor_Call) RunAndReturn(run func(context.Context, *cert.AnchorRequest) (*cert.AnchorReceipt, error)) *MockAnchorServicer_Anchor_Call {
	_c.Call.Return(run)
	return _c
}

// Chains provides a mock function with no fields
func (_m *MockAnchorServicer) Chains() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chains")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockAnchorServicer_Chains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chains'
type MockAnchorServicer_Chains_Call struct {
	*mock.Call
}

// Chains is a helper method to define mock.On call
func (_e *MockAnchorServicer_Expecter) Chains() *MockAnchorServicer_Chains_Call {
	return &MockAnchorServicer_Chains_Call{Call: _e.mock.On("Chains")}
}

func (_c *MockAnchorServicer_Chains_Call) Run(run func()) *MockAnchorServicer_Chains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnchorServicer_Chains_Call) Return(_a0 []string) *MockAnchorServicer_Chains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnchorServicer_Chains_Call) RunAndReturn(run func() []string) *MockAnchorServicer_Chains_Call {
	_c.Call.Return(run)
	return _c
}

// IsConfigured provides a mock function with no fields
func (_m *MockAnchorServicer) IsConfigured() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConfigured")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAnchorServicer_IsConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConfigured'
type MockAnchorServicer_IsConfigured_Call struct {
	*mock.Call
}

// IsConfigured is a helper method to define mock.On call
func (_e *MockAnchorServicer_Expecter) IsConfigured() *MockAnchorServicer_IsConfigured_Call {
	return &MockAnchorServicer_IsConfigured_Call{Call: _e.mock.On("IsConfigured")}
}

func (_c *MockAnchorServicer_IsConfigured_Call) Run(run func()) *MockAnchorServicer_IsConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnchorServicer_IsConfigured_Call) Return(_a0 bool) *MockAnchorServicer_IsConfigured_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnchorServicer_IsConfigured_Call) RunAndReturn(run func() bool) *MockAnchorServicer_IsConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnchorServicer creates a new instance of MockAnchorServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnchorServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnchorServicer {
	mock := &MockAnchorServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
