// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dre

import (
	"context"
	"time"

	"github.com/functionfly/functionfly/internal/storage/registry"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDRERepository creates a new instance of MockDRERepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDRERepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDRERepository {
	mock := &MockDRERepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDRERepository is an autogenerated mock type for the DRERepository type
type MockDRERepository struct {
	mock.Mock
}

type MockDRERepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDRERepository) EXPECT() *MockDRERepository_Expecter {
	return &MockDRERepository_Expecter{mock: &_m.Mock}
}

// GetCertificateByExecutionID provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetCertificateByExecutionID(executionID uuid.UUID) (*registry.ExecutionCertificate, error) {
	ret := _mock.Called(executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateByExecutionID")
	}

	var r0 *registry.ExecutionCertificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*registry.ExecutionCertificate, error)); ok {
		return returnFunc(executionID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *registry.ExecutionCertificate); ok {
		r0 = returnFunc(executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.ExecutionCertificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(executionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetCertificateByExecutionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateByExecutionID'
type MockDRERepository_GetCertificateByExecutionID_Call struct {
	*mock.Call
}

// GetCertificateByExecutionID is a helper method to define mock.On call
//   - executionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetCertificateByExecutionID(executionID any) *MockDRERepository_GetCertificateByExecutionID_Call {
	return &MockDRERepository_GetCertificateByExecutionID_Call{Call: _e.mock.On("GetCertificateByExecutionID", executionID)}
}

func (_c *MockDRERepository_GetCertificateByExecutionID_Call) Run(run func(executionID uuid.UUID)) *MockDRERepository_GetCertificateByExecutionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetCertificateByExecutionID_Call) Return(executionCertificate *registry.ExecutionCertificate, err error) *MockDRERepository_GetCertificateByExecutionID_Call {
	_c.Call.Return(executionCertificate, err)
	return _c
}

func (_c *MockDRERepository_GetCertificateByExecutionID_Call) RunAndReturn(run func(executionID uuid.UUID) (*registry.ExecutionCertificate, error)) *MockDRERepository_GetCertificateByExecutionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateByID provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetCertificateByID(certID string) (*registry.ExecutionCertificate, error) {
	ret := _mock.Called(certID)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateByID")
	}

	var r0 *registry.ExecutionCertificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*registry.ExecutionCertificate, error)); ok {
		return returnFunc(certID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *registry.ExecutionCertificate); ok {
		r0 = returnFunc(certID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.ExecutionCertificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(certID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetCertificateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateByID'
type MockDRERepository_GetCertificateByID_Call struct {
	*mock.Call
}

// GetCertificateByID is a helper method to define mock.On call
//   - certID string
func (_e *MockDRERepository_Expecter) GetCertificateByID(certID any) *MockDRERepository_GetCertificateByID_Call {
	return &MockDRERepository_GetCertificateByID_Call{Call: _e.mock.On("GetCertificateByID", certID)}
}

func (_c *MockDRERepository_GetCertificateByID_Call) Run(run func(certID string)) *MockDRERepository_GetCertificateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetCertificateByID_Call) Return(executionCertificate *registry.ExecutionCertificate, err error) *MockDRERepository_GetCertificateByID_Call {
	_c.Call.Return(executionCertificate, err)
	return _c
}

func (_c *MockDRERepository_GetCertificateByID_Call) RunAndReturn(run func(certID string) (*registry.ExecutionCertificate, error)) *MockDRERepository_GetCertificateByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificatesByFunctionID provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetCertificatesByFunctionID(functionID uuid.UUID, limit int, offset int) ([]*registry.ExecutionCertificate, error) {
	ret := _mock.Called(functionID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificatesByFunctionID")
	}

	var r0 []*registry.ExecutionCertificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]*registry.ExecutionCertificate, error)); ok {
		return returnFunc(functionID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int) []*registry.ExecutionCertificate); ok {
		r0 = returnFunc(functionID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*registry.ExecutionCertificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, int, int) error); ok {
		r1 = returnFunc(functionID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetCertificatesByFunctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificatesByFunctionID'
type MockDRERepository_GetCertificatesByFunctionID_Call struct {
	*mock.Call
}

// GetCertificatesByFunctionID is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockDRERepository_Expecter) GetCertificatesByFunctionID(functionID any, limit any, offset any) *MockDRERepository_GetCertificatesByFunctionID_Call {
	return &MockDRERepository_GetCertificatesByFunctionID_Call{Call: _e.mock.On("GetCertificatesByFunctionID", functionID, limit, offset)}
}

func (_c *MockDRERepository_GetCertificatesByFunctionID_Call) Run(run func(functionID uuid.UUID, limit int, offset int)) *MockDRERepository_GetCertificatesByFunctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetCertificatesByFunctionID_Call) Return(executionCertificates []*registry.ExecutionCertificate, err error) *MockDRERepository_GetCertificatesByFunctionID_Call {
	_c.Call.Return(executionCertificates, err)
	return _c
}

func (_c *MockDRERepository_GetCertificatesByFunctionID_Call) RunAndReturn(run func(functionID uuid.UUID, limit int, offset int) ([]*registry.ExecutionCertificate, error)) *MockDRERepository_GetCertificatesByFunctionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriftReportsByFunctionID provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetDriftReportsByFunctionID(functionID uuid.UUID, limit int, offset int) ([]*registry.DriftReportRecord, error) {
	ret := _mock.Called(functionID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetDriftReportsByFunctionID")
	}

	var r0 []*registry.DriftReportRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]*registry.DriftReportRecord, error)); ok {
		return returnFunc(functionID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int) []*registry.DriftReportRecord); ok {
		r0 = returnFunc(functionID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*registry.DriftReportRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, int, int) error); ok {
		r1 = returnFunc(functionID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetDriftReportsByFunctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriftReportsByFunctionID'
type MockDRERepository_GetDriftReportsByFunctionID_Call struct {
	*mock.Call
}

// GetDriftReportsByFunctionID is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockDRERepository_Expecter) GetDriftReportsByFunctionID(functionID any, limit any, offset any) *MockDRERepository_GetDriftReportsByFunctionID_Call {
	return &MockDRERepository_GetDriftReportsByFunctionID_Call{Call: _e.mock.On("GetDriftReportsByFunctionID", functionID, limit, offset)}
}

func (_c *MockDRERepository_GetDriftReportsByFunctionID_Call) Run(run func(functionID uuid.UUID, limit int, offset int)) *MockDRERepository_GetDriftReportsByFunctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetDriftReportsByFunctionID_Call) Return(driftReportRecords []*registry.DriftReportRecord, err error) *MockDRERepository_GetDriftReportsByFunctionID_Call {
	_c.Call.Return(driftReportRecords, err)
	return _c
}

func (_c *MockDRERepository_GetDriftReportsByFunctionID_Call) RunAndReturn(run func(functionID uuid.UUID, limit int, offset int) ([]*registry.DriftReportRecord, error)) *MockDRERepository_GetDriftReportsByFunctionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionTimelineBuckets provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetExecutionTimelineBuckets(functionID uuid.UUID, from time.Time, to time.Time, metric string) ([]registry.ExecutionTimelineBucket, error) {
	ret := _mock.Called(functionID, from, to, metric)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionTimelineBuckets")
	}

	var r0 []registry.ExecutionTimelineBucket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time, string) ([]registry.ExecutionTimelineBucket, error)); ok {
		return returnFunc(functionID, from, to, metric)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, time.Time, time.Time, string) []registry.ExecutionTimelineBucket); ok {
		r0 = returnFunc(functionID, from, to, metric)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]registry.ExecutionTimelineBucket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, time.Time, time.Time, string) error); ok {
		r1 = returnFunc(functionID, from, to, metric)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetExecutionTimelineBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionTimelineBuckets'
type MockDRERepository_GetExecutionTimelineBuckets_Call struct {
	*mock.Call
}

// GetExecutionTimelineBuckets is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - from time.Time
//   - to time.Time
//   - metric string
func (_e *MockDRERepository_Expecter) GetExecutionTimelineBuckets(functionID any, from any, to any, metric any) *MockDRERepository_GetExecutionTimelineBuckets_Call {
	return &MockDRERepository_GetExecutionTimelineBuckets_Call{Call: _e.mock.On("GetExecutionTimelineBuckets", functionID, from, to, metric)}
}

func (_c *MockDRERepository_GetExecutionTimelineBuckets_Call) Run(run func(functionID uuid.UUID, from time.Time, to time.Time, metric string)) *MockDRERepository_GetExecutionTimelineBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetExecutionTimelineBuckets_Call) Return(executionTimelineBuckets []registry.ExecutionTimelineBucket, err error) *MockDRERepository_GetExecutionTimelineBuckets_Call {
	_c.Call.Return(executionTimelineBuckets, err)
	return _c
}

func (_c *MockDRERepository_GetExecutionTimelineBuckets_Call) RunAndReturn(run func(functionID uuid.UUID, from time.Time, to time.Time, metric string) ([]registry.ExecutionTimelineBucket, error)) *MockDRERepository_GetExecutionTimelineBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionByAuthorName provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetFunctionByAuthorName(ctx context.Context, author string, name string) (*registry.RegistryFunction, error) {
	ret := _mock.Called(ctx, author, name)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionByAuthorName")
	}

	var r0 *registry.RegistryFunction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*registry.RegistryFunction, error)); ok {
		return returnFunc(ctx, author, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *registry.RegistryFunction); ok {
		r0 = returnFunc(ctx, author, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryFunction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, author, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetFunctionByAuthorName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionByAuthorName'
type MockDRERepository_GetFunctionByAuthorName_Call struct {
	*mock.Call
}

// GetFunctionByAuthorName is a helper method to define mock.On call
//   - ctx context.Context
//   - author string
//   - name string
func (_e *MockDRERepository_Expecter) GetFunctionByAuthorName(ctx any, author any, name any) *MockDRERepository_GetFunctionByAuthorName_Call {
	return &MockDRERepository_GetFunctionByAuthorName_Call{Call: _e.mock.On("GetFunctionByAuthorName", ctx, author, name)}
}

func (_c *MockDRERepository_GetFunctionByAuthorName_Call) Run(run func(ctx context.Context, author string, name string)) *MockDRERepository_GetFunctionByAuthorName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetFunctionByAuthorName_Call) Return(registryFunction *registry.RegistryFunction, err error) *MockDRERepository_GetFunctionByAuthorName_Call {
	_c.Call.Return(registryFunction, err)
	return _c
}

func (_c *MockDRERepository_GetFunctionByAuthorName_Call) RunAndReturn(run func(ctx context.Context, author string, name string) (*registry.RegistryFunction, error)) *MockDRERepository_GetFunctionByAuthorName_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionByID provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetFunctionByID(ctx context.Context, id uuid.UUID) (*registry.RegistryFunction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionByID")
	}

	var r0 *registry.RegistryFunction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*registry.RegistryFunction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *registry.RegistryFunction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryFunction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetFunctionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionByID'
type MockDRERepository_GetFunctionByID_Call struct {
	*mock.Call
}

// GetFunctionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDRERepository_Expecter) GetFunctionByID(ctx any, id any) *MockDRERepository_GetFunctionByID_Call {
	return &MockDRERepository_GetFunctionByID_Call{Call: _e.mock.On("GetFunctionByID", ctx, id)}
}

func (_c *MockDRERepository_GetFunctionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDRERepository_GetFunctionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetFunctionByID_Call) Return(registryFunction *registry.RegistryFunction, err error) *MockDRERepository_GetFunctionByID_Call {
	_c.Call.Return(registryFunction, err)
	return _c
}

func (_c *MockDRERepository_GetFunctionByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*registry.RegistryFunction, error)) *MockDRERepository_GetFunctionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionVersion provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetFunctionVersion(functionID uuid.UUID, version string) (*registry.RegistryFunctionVersion, error) {
	ret := _mock.Called(functionID, version)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionVersion")
	}

	var r0 *registry.RegistryFunctionVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) (*registry.RegistryFunctionVersion, error)); ok {
		return returnFunc(functionID, version)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string) *registry.RegistryFunctionVersion); ok {
		r0 = returnFunc(functionID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryFunctionVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = returnFunc(functionID, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetFunctionVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionVersion'
type MockDRERepository_GetFunctionVersion_Call struct {
	*mock.Call
}

// GetFunctionVersion is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - version string
func (_e *MockDRERepository_Expecter) GetFunctionVersion(functionID any, version any) *MockDRERepository_GetFunctionVersion_Call {
	return &MockDRERepository_GetFunctionVersion_Call{Call: _e.mock.On("GetFunctionVersion", functionID, version)}
}

func (_c *MockDRERepository_GetFunctionVersion_Call) Run(run func(functionID uuid.UUID, version string)) *MockDRERepository_GetFunctionVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetFunctionVersion_Call) Return(registryFunctionVersion *registry.RegistryFunctionVersion, err error) *MockDRERepository_GetFunctionVersion_Call {
	_c.Call.Return(registryFunctionVersion, err)
	return _c
}

func (_c *MockDRERepository_GetFunctionVersion_Call) RunAndReturn(run func(functionID uuid.UUID, version string) (*registry.RegistryFunctionVersion, error)) *MockDRERepository_GetFunctionVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestFunctionVersion provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetLatestFunctionVersion(functionID uuid.UUID) (*registry.RegistryFunctionVersion, error) {
	ret := _mock.Called(functionID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestFunctionVersion")
	}

	var r0 *registry.RegistryFunctionVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*registry.RegistryFunctionVersion, error)); ok {
		return returnFunc(functionID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *registry.RegistryFunctionVersion); ok {
		r0 = returnFunc(functionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.RegistryFunctionVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(functionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetLatestFunctionVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestFunctionVersion'
type MockDRERepository_GetLatestFunctionVersion_Call struct {
	*mock.Call
}

// GetLatestFunctionVersion is a helper method to define mock.On call
//   - functionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetLatestFunctionVersion(functionID any) *MockDRERepository_GetLatestFunctionVersion_Call {
	return &MockDRERepository_GetLatestFunctionVersion_Call{Call: _e.mock.On("GetLatestFunctionVersion", functionID)}
}

func (_c *MockDRERepository_GetLatestFunctionVersion_Call) Run(run func(functionID uuid.UUID)) *MockDRERepository_GetLatestFunctionVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetLatestFunctionVersion_Call) Return(registryFunctionVersion *registry.RegistryFunctionVersion, err error) *MockDRERepository_GetLatestFunctionVersion_Call {
	_c.Call.Return(registryFunctionVersion, err)
	return _c
}

func (_c *MockDRERepository_GetLatestFunctionVersion_Call) RunAndReturn(run func(functionID uuid.UUID) (*registry.RegistryFunctionVersion, error)) *MockDRERepository_GetLatestFunctionVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetMEGByExecutionID provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetMEGByExecutionID(executionID uuid.UUID) (*registry.MEGRecord, error) {
	ret := _mock.Called(executionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMEGByExecutionID")
	}

	var r0 *registry.MEGRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*registry.MEGRecord, error)); ok {
		return returnFunc(executionID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *registry.MEGRecord); ok {
		r0 = returnFunc(executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.MEGRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(executionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetMEGByExecutionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMEGByExecutionID'
type MockDRERepository_GetMEGByExecutionID_Call struct {
	*mock.Call
}

// GetMEGByExecutionID is a helper method to define mock.On call
//   - executionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetMEGByExecutionID(executionID any) *MockDRERepository_GetMEGByExecutionID_Call {
	return &MockDRERepository_GetMEGByExecutionID_Call{Call: _e.mock.On("GetMEGByExecutionID", executionID)}
}

func (_c *MockDRERepository_GetMEGByExecutionID_Call) Run(run func(executionID uuid.UUID)) *MockDRERepository_GetMEGByExecutionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetMEGByExecutionID_Call) Return(mEGRecord *registry.MEGRecord, err error) *MockDRERepository_GetMEGByExecutionID_Call {
	_c.Call.Return(mEGRecord, err)
	return _c
}

func (_c *MockDRERepository_GetMEGByExecutionID_Call) RunAndReturn(run func(executionID uuid.UUID) (*registry.MEGRecord, error)) *MockDRERepository_GetMEGByExecutionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMEGByExecutionRootHash provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetMEGByExecutionRootHash(hash string) (*registry.MEGRecord, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetMEGByExecutionRootHash")
	}

	var r0 *registry.MEGRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*registry.MEGRecord, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *registry.MEGRecord); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.MEGRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetMEGByExecutionRootHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMEGByExecutionRootHash'
type MockDRERepository_GetMEGByExecutionRootHash_Call struct {
	*mock.Call
}

// GetMEGByExecutionRootHash is a helper method to define mock.On call
//   - hash string
func (_e *MockDRERepository_Expecter) GetMEGByExecutionRootHash(hash any) *MockDRERepository_GetMEGByExecutionRootHash_Call {
	return &MockDRERepository_GetMEGByExecutionRootHash_Call{Call: _e.mock.On("GetMEGByExecutionRootHash", hash)}
}

func (_c *MockDRERepository_GetMEGByExecutionRootHash_Call) Run(run func(hash string)) *MockDRERepository_GetMEGByExecutionRootHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetMEGByExecutionRootHash_Call) Return(mEGRecord *registry.MEGRecord, err error) *MockDRERepository_GetMEGByExecutionRootHash_Call {
	_c.Call.Return(mEGRecord, err)
	return _c
}

func (_c *MockDRERepository_GetMEGByExecutionRootHash_Call) RunAndReturn(run func(hash string) (*registry.MEGRecord, error)) *MockDRERepository_GetMEGByExecutionRootHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetMEGRecordsByFunctionID provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetMEGRecordsByFunctionID(functionID uuid.UUID, limit int, offset int, filters registry.MEGRecordFilters) ([]*registry.MEGRecord, int64, error) {
	ret := _mock.Called(functionID, limit, offset, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetMEGRecordsByFunctionID")
	}

	var r0 []*registry.MEGRecord
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int, registry.MEGRecordFilters) ([]*registry.MEGRecord, int64, error)); ok {
		return returnFunc(functionID, limit, offset, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int, registry.MEGRecordFilters) []*registry.MEGRecord); ok {
		r0 = returnFunc(functionID, limit, offset, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*registry.MEGRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, int, int, registry.MEGRecordFilters) int64); ok {
		r1 = returnFunc(functionID, limit, offset, filters)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID, int, int, registry.MEGRecordFilters) error); ok {
		r2 = returnFunc(functionID, limit, offset, filters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDRERepository_GetMEGRecordsByFunctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMEGRecordsByFunctionID'
type MockDRERepository_GetMEGRecordsByFunctionID_Call struct {
	*mock.Call
}

// GetMEGRecordsByFunctionID is a helper method to define mock.On call
//   - functionID uuid.UUID
//   - limit int
//   - offset int
//   - filters registry.MEGRecordFilters
func (_e *MockDRERepository_Expecter) GetMEGRecordsByFunctionID(functionID any, limit any, offset any, filters any) *MockDRERepository_GetMEGRecordsByFunctionID_Call {
	return &MockDRERepository_GetMEGRecordsByFunctionID_Call{Call: _e.mock.On("GetMEGRecordsByFunctionID", functionID, limit, offset, filters)}
}

func (_c *MockDRERepository_GetMEGRecordsByFunctionID_Call) Run(run func(functionID uuid.UUID, limit int, offset int, filters registry.MEGRecordFilters)) *MockDRERepository_GetMEGRecordsByFunctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 registry.MEGRecordFilters
		if args[3] != nil {
			arg3 = args[3].(registry.MEGRecordFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetMEGRecordsByFunctionID_Call) Return(mEGRecords []*registry.MEGRecord, n int64, err error) *MockDRERepository_GetMEGRecordsByFunctionID_Call {
	_c.Call.Return(mEGRecords, n, err)
	return _c
}

func (_c *MockDRERepository_GetMEGRecordsByFunctionID_Call) RunAndReturn(run func(functionID uuid.UUID, limit int, offset int, filters registry.MEGRecordFilters) ([]*registry.MEGRecord, int64, error)) *MockDRERepository_GetMEGRecordsByFunctionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreatePassport provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetOrCreatePassport(functionID uuid.UUID) (*registry.ExecutionPassport, error) {
	ret := _mock.Called(functionID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreatePassport")
	}

	var r0 *registry.ExecutionPassport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*registry.ExecutionPassport, error)); ok {
		return returnFunc(functionID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *registry.ExecutionPassport); ok {
		r0 = returnFunc(functionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.ExecutionPassport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(functionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetOrCreatePassport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreatePassport'
type MockDRERepository_GetOrCreatePassport_Call struct {
	*mock.Call
}

// GetOrCreatePassport is a helper method to define mock.On call
//   - functionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetOrCreatePassport(functionID any) *MockDRERepository_GetOrCreatePassport_Call {
	return &MockDRERepository_GetOrCreatePassport_Call{Call: _e.mock.On("GetOrCreatePassport", functionID)}
}

func (_c *MockDRERepository_GetOrCreatePassport_Call) Run(run func(functionID uuid.UUID)) *MockDRERepository_GetOrCreatePassport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetOrCreatePassport_Call) Return(executionPassport *registry.ExecutionPassport, err error) *MockDRERepository_GetOrCreatePassport_Call {
	_c.Call.Return(executionPassport, err)
	return _c
}

func (_c *MockDRERepository_GetOrCreatePassport_Call) RunAndReturn(run func(functionID uuid.UUID) (*registry.ExecutionPassport, error)) *MockDRERepository_GetOrCreatePassport_Call {
	_c.Call.Return(run)
	return _c
}

// GetPassportByFunctionID provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) GetPassportByFunctionID(functionID uuid.UUID) (*registry.ExecutionPassport, error) {
	ret := _mock.Called(functionID)

	if len(ret) == 0 {
		panic("no return value specified for GetPassportByFunctionID")
	}

	var r0 *registry.ExecutionPassport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*registry.ExecutionPassport, error)); ok {
		return returnFunc(functionID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *registry.ExecutionPassport); ok {
		r0 = returnFunc(functionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.ExecutionPassport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(functionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDRERepository_GetPassportByFunctionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPassportByFunctionID'
type MockDRERepository_GetPassportByFunctionID_Call struct {
	*mock.Call
}

// GetPassportByFunctionID is a helper method to define mock.On call
//   - functionID uuid.UUID
func (_e *MockDRERepository_Expecter) GetPassportByFunctionID(functionID any) *MockDRERepository_GetPassportByFunctionID_Call {
	return &MockDRERepository_GetPassportByFunctionID_Call{Call: _e.mock.On("GetPassportByFunctionID", functionID)}
}

func (_c *MockDRERepository_GetPassportByFunctionID_Call) Run(run func(functionID uuid.UUID)) *MockDRERepository_GetPassportByFunctionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDRERepository_GetPassportByFunctionID_Call) Return(executionPassport *registry.ExecutionPassport, err error) *MockDRERepository_GetPassportByFunctionID_Call {
	_c.Call.Return(executionPassport, err)
	return _c
}

func (_c *MockDRERepository_GetPassportByFunctionID_Call) RunAndReturn(run func(functionID uuid.UUID) (*registry.ExecutionPassport, error)) *MockDRERepository_GetPassportByFunctionID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertificateAnchored provides a mock function for the type MockDRERepository
func (_mock *MockDRERepository) UpdateCertificateAnchored(certID string, anchored bool, anchorChain string, anchorTxHash string, anchorMerkleRoot string, anchorBlockNumber int64, anchoredAt *time.Time) error {
	ret := _mock.Called(certID, anchored, anchorChain, anchorTxHash, anchorMerkleRoot, anchorBlockNumber, anchoredAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificateAnchored")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, bool, string, string, string, int64, *time.Time) error); ok {
		r0 = returnFunc(certID, anchored, anchorChain, anchorTxHash, anchorMerkleRoot, anchorBlockNumber, anchoredAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDRERepository_UpdateCertificateAnchored_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertificateAnchored'
type MockDRERepository_UpdateCertificateAnchored_Call struct {
	*mock.Call
}

// UpdateCertificateAnchored is a helper method to define mock.On call
//   - certID string
//   - anchored bool
//   - anchorChain string
//   - anchorTxHash string
//   - anchorMerkleRoot string
//   - anchorBlockNumber int64
//   - anchoredAt *time.Time
func (_e *MockDRERepository_Expecter) UpdateCertificateAnchored(certID any, anchored any, anchorChain any, anchorTxHash any, anchorMerkleRoot any, anchorBlockNumber any, anchoredAt any) *MockDRERepository_UpdateCertificateAnchored_Call {
	return &MockDRERepository_UpdateCertificateAnchored_Call{Call: _e.mock.On("UpdateCertificateAnchored", certID, anchored, anchorChain, anchorTxHash, anchorMerkleRoot, anchorBlockNumber, anchoredAt)}
}

func (_c *MockDRERepository_UpdateCertificateAnchored_Call) Run(run func(certID string, anchored bool, anchorChain string, anchorTxHash string, anchorMerkleRoot string, anchorBlockNumber int64, anchoredAt *time.Time)) *MockDRERepository_UpdateCertificateAnchored_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 *time.Time
		if args[6] != nil {
			arg6 = args[6].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockDRERepository_UpdateCertificateAnchored_Call) Return(err error) *MockDRERepository_UpdateCertificateAnchored_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDRERepository_UpdateCertificateAnchored_Call) RunAndReturn(run func(certID string, anchored bool, anchorChain string, anchorTxHash string, anchorMerkleRoot string, anchorBlockNumber int64, anchoredAt *time.Time) error) *MockDRERepository_UpdateCertificateAnchored_Call {
	_c.Call.Return(run)
	return _c
}
