// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dre

import (
	"context"

	"github.com/functionfly/functionfly/internal/dre/cert"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnchorServicer creates a new instance of MockAnchorServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnchorServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnchorServicer {
	mock := &MockAnchorServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnchorServicer is an autogenerated mock type for the AnchorServicer type
type MockAnchorServicer struct {
	mock.Mock
}

type MockAnchorServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnchorServicer) EXPECT() *MockAnchorServicer_Expecter {
	return &MockAnchorServicer_Expecter{mock: &_m.Mock}
}

// Anchor provides a mock function for the type MockAnchorServicer
func (_mock *MockAnchorServicer) Anchor(ctx context.Context, req *cert.AnchorRequest) (*cert.AnchorReceipt, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Anchor")
	}

	var r0 *cert.AnchorReceipt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cert.AnchorRequest) (*cert.AnchorReceipt, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cert.AnchorRequest) *cert.AnchorReceipt); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cert.AnchorReceipt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cert.AnchorRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnchorServicer_Anchor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Anchor'
type MockAnchorServicer_Anchor_Call struct {
	*mock.Call
}

// Anchor is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cert.AnchorRequest
func (_e *MockAnchorServicer_Expecter) Anchor(ctx any, req any) *MockAnchorServicer_Anchor_Call {
	return &MockAnchorServicer_Anchor_Call{Call: _e.mock.On("Anchor", ctx, req)}
}

func (_c *MockAnchorServicer_Anchor_Call) Run(run func(ctx context.Context, req *cert.AnchorRequest)) *MockAnchorServicer_Anchor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cert.AnchorRequest
		if args[1] != nil {
			arg1 = args[1].(*cert.AnchorRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnchorServicer_Anchor_Call) Return(anchorReceipt *cert.AnchorReceipt, err error) *MockAnchorServicer_Anchor_Call {
	_c.Call.Return(anchorReceipt, err)
	return _c
}

func (_c *MockAnchorServicer_Anchor_Call) RunAndReturn(run func(ctx context.Context, req *cert.AnchorRequest) (*cert.AnchorReceipt, error)) *MockAnchorServicer_Anchor_Call {
	_c.Call.Return(run)
	return _c
}

// Chains provides a mock function for the type MockAnchorServicer
func (_mock *MockAnchorServicer) Chains() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chains")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockAnchorServicer_Chains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chains'
type MockAnchorServicer_Chains_Call struct {
	*mock.Call
}

// Chains is a helper method to define mock.On call
func (_e *MockAnchorServicer_Expecter) Chains() *MockAnchorServicer_Chains_Call {
	return &MockAnchorServicer_Chains_Call{Call: _e.mock.On("Chains")}
}

func (_c *MockAnchorServicer_Chains_Call) Run(run func()) *MockAnchorServicer_Chains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnchorServicer_Chains_Call) Return(strings []string) *MockAnchorServicer_Chains_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockAnchorServicer_Chains_Call) RunAndReturn(run func() []string) *MockAnchorServicer_Chains_Call {
	_c.Call.Return(run)
	return _c
}

// IsConfigured provides a mock function for the type MockAnchorServicer
func (_mock *MockAnchorServicer) IsConfigured() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConfigured")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAnchorServicer_IsConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConfigured'
type MockAnchorServicer_IsConfigured_Call struct {
	*mock.Call
}

// IsConfigured is a helper method to define mock.On call
func (_e *MockAnchorServicer_Expecter) IsConfigured() *MockAnchorServicer_IsConfigured_Call {
	return &MockAnchorServicer_IsConfigured_Call{Call: _e.mock.On("IsConfigured")}
}

func (_c *MockAnchorServicer_IsConfigured_Call) Run(run func()) *MockAnchorServicer_IsConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnchorServicer_IsConfigured_Call) Return(b bool) *MockAnchorServicer_IsConfigured_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAnchorServicer_IsConfigured_Call) RunAndReturn(run func() bool) *MockAnchorServicer_IsConfigured_Call {
	_c.Call.Return(run)
	return _c
}
