/**
 * FlyQuickActions.tsx
 *
 * Dynamic action buttons generated by AI with support for multiple states,
 * icons, and visual grouping. Provides horizontal scrollable action chips.
 */

import React, { useCallback, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Zap,
  Play,
  DollarSign,
  RotateCcw,
  Rocket,
  FileText,
  Undo2,
  Check,
  X,
  Loader2,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

// ============================================================================
// Types & Interfaces
// ============================================================================

/**
 * Action variant determines visual styling
 */
export type ActionVariant = "primary" | "secondary" | "danger";

/**
 * Action state for visual feedback
 */
export type ActionState = "default" | "loading" | "success" | "error";

/**
 * Quick action item definition
 */
export interface QuickAction {
  /** Unique identifier */
  id: string;
  /** Display label */
  label: string;
  /** Icon name from predefined set */
  icon: ActionIconName;
  /** Visual variant */
  variant: ActionVariant;
  /** Current state */
  state?: ActionState;
  /** Disabled state */
  disabled?: boolean;
  /** Optional description for tooltip */
  description?: string;
}

/**
 * Predefined action icon names
 */
export type ActionIconName =
  | "optimize"
  | "test"
  | "monetize"
  | "replay"
  | "deploy"
  | "logs"
  | "rollback"
  | string;

/**
 * Props for the FlyQuickActions component
 */
export interface FlyQuickActionsProps {
  /** Array of quick action items */
  actions: QuickAction[];
  /** Callback when an action is triggered */
  onAction: (actionId: string) => void;
  /** Disable all actions */
  disabled?: boolean;
  /** Layout orientation */
  orientation?: "horizontal" | "vertical";
  /** Custom className */
  className?: string;
}

// ============================================================================
// Icon Mapping
// ============================================================================

const ICON_MAP: Record<string, LucideIcon> = {
  optimize: Zap,
  test: Play,
  monetize: DollarSign,
  replay: RotateCcw,
  deploy: Rocket,
  logs: FileText,
  rollback: Undo2,
};

/**
 * Get the icon component for an action
 */
function getActionIcon(iconName: string): LucideIcon {
  return ICON_MAP[iconName] || Zap;
}

// ============================================================================
// Action Button Component
// ============================================================================

interface ActionButtonProps {
  action: QuickAction;
  onClick: () => void;
  disabled?: boolean;
}

const ActionButton = React.memo<ActionButtonProps>(
  ({ action, onClick, disabled }) => {
    const Icon = getActionIcon(action.icon);
    const state = action.state || "default";
    const isDisabled = disabled || action.disabled || state === "loading";

    // Variant styles
    const variantStyles = useMemo(() => {
      switch (action.variant) {
        case "primary":
          return "bg-[var(--color-brand-600)] text-white hover:bg-[var(--color-brand-500)] border-transparent";
        case "danger":
          return "bg-red-600 text-white hover:bg-red-500 border-transparent";
        case "secondary":
        default:
          return "bg-transparent text-[var(--color-text-primary)] border border-[var(--color-border)] hover:border-[var(--color-brand-500)]/50";
      }
    }, [action.variant]);

    // State indicator
    const StateIcon = useMemo(() => {
      switch (state) {
        case "loading":
          return Loader2;
        case "success":
          return Check;
        case "error":
          return X;
        default:
          return null;
      }
    }, [state]);

    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.9 }}
        transition={{ duration: 0.2 }}
      >
        <button
          onClick={onClick}
          disabled={isDisabled}
          aria-label={action.description || action.label}
          aria-busy={state === "loading"}
          className={cn(
            // Base styles - pill shape
            "inline-flex items-center gap-2 px-3 py-1.5 rounded-[20px]",
            "text-[13px] font-medium",
            "transition-all duration-200",
            "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-brand-500)]/50",
            "disabled:opacity-50 disabled:cursor-not-allowed",
            "border",
            variantStyles,
            state === "loading" && "cursor-wait",
            state === "success" && "bg-emerald-600 hover:bg-emerald-500",
            state === "error" && "bg-red-600 hover:bg-red-500"
          )}
        >
          <AnimatePresence mode="wait">
            {StateIcon ? (
              <motion.span
                key="state-icon"
                initial={{ opacity: 0, rotate: -180 }}
                animate={{ opacity: 1, rotate: 0 }}
                exit={{ opacity: 0, rotate: 180 }}
                transition={{ duration: 0.2 }}
              >
                <StateIcon
                  className={cn(
                    "h-3.5 w-3.5",
                    state === "loading" && "animate-spin"
                  )}
                />
              </motion.span>
            ) : (
              <motion.span
                key="action-icon"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
              >
                <Icon className="h-3.5 w-3.5" />
              </motion.span>
            )}
          </AnimatePresence>
          <span>{action.label}</span>
        </button>
      </motion.div>
    );
  }
);

ActionButton.displayName = "ActionButton";

// ============================================================================
// Main Component
// ============================================================================

export const FlyQuickActions = React.memo<FlyQuickActionsProps>(
  ({
    actions,
    onAction,
    disabled = false,
    orientation = "horizontal",
    className,
  }) => {
    const handleAction = useCallback(
      (actionId: string) => {
        if (!disabled) {
          onAction(actionId);
        }
      },
      [disabled, onAction]
    );

    // Group actions by variant for visual organization
    const groupedActions = useMemo(() => {
      const primary = actions.filter((a) => a.variant === "primary");
      const danger = actions.filter((a) => a.variant === "danger");
      const secondary = actions.filter((a) => a.variant === "secondary");
      return { primary, danger, secondary };
    }, [actions]);

    if (actions.length === 0) {
      return null;
    }

    const isHorizontal = orientation === "horizontal";

    return (
      <div
        className={cn(
          "w-full",
          isHorizontal && "overflow-x-auto scrollbar-thin scrollbar-thumb-[var(--color-border)] scrollbar-track-transparent",
          className
        )}
      >
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className={cn(
            "flex gap-2",
            isHorizontal ? "flex-nowrap" : "flex-col",
            isHorizontal && "pb-1" // Space for scrollbar
          )}
          role="group"
          aria-label="Quick actions"
        >
          <AnimatePresence mode="popLayout">
            {/* Primary actions first */}
            {groupedActions.primary.map((action) => (
              <ActionButton
                key={action.id}
                action={action}
                onClick={() => handleAction(action.id)}
                disabled={disabled}
              />
            ))}

            {/* Danger actions */}
            {groupedActions.danger.map((action) => (
              <ActionButton
                key={action.id}
                action={action}
                onClick={() => handleAction(action.id)}
                disabled={disabled}
              />
            ))}

            {/* Secondary actions last */}
            {groupedActions.secondary.map((action) => (
              <ActionButton
                key={action.id}
                action={action}
                onClick={() => handleAction(action.id)}
                disabled={disabled}
              />
            ))}
          </AnimatePresence>
        </motion.div>
      </div>
    );
  }
);

FlyQuickActions.displayName = "FlyQuickActions";

export default FlyQuickActions;
