# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import flymind_pb2 as flymind__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flymind_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlyMindServiceStub(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoutingRecommendation = channel.unary_unary(
                '/flymind.FlyMindService/GetRoutingRecommendation',
                request_serializer=flymind__pb2.RoutingRequest.SerializeToString,
                response_deserializer=flymind__pb2.RoutingRecommendation.FromString,
                _registered_method=True)
        self.ReportExecutionOutcome = channel.unary_unary(
                '/flymind.FlyMindService/ReportExecutionOutcome',
                request_serializer=flymind__pb2.ExecutionOutcome.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ShouldPrewarm = channel.unary_unary(
                '/flymind.FlyMindService/ShouldPrewarm',
                request_serializer=flymind__pb2.PrewarmQuery.SerializeToString,
                response_deserializer=flymind__pb2.PrewarmDecision.FromString,
                _registered_method=True)
        self.GetCacheKey = channel.unary_unary(
                '/flymind.FlyMindService/GetCacheKey',
                request_serializer=flymind__pb2.CacheQuery.SerializeToString,
                response_deserializer=flymind__pb2.CacheDecision.FromString,
                _registered_method=True)
        self.ModerateContent = channel.unary_unary(
                '/flymind.FlyMindService/ModerateContent',
                request_serializer=flymind__pb2.ModerationRequest.SerializeToString,
                response_deserializer=flymind__pb2.ModerationResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/flymind.FlyMindService/HealthCheck',
                request_serializer=flymind__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=flymind__pb2.HealthResponse.FromString,
                _registered_method=True)


class FlyMindServiceServicer(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    """

    def GetRoutingRecommendation(self, request, context):
        """Get routing recommendation for an execution request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportExecutionOutcome(self, request, context):
        """Report execution outcome for learning and optimization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShouldPrewarm(self, request, context):
        """Ask FlyMind whether a function should be prewarmed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheKey(self, request, context):
        """Decide how to cache a given input.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModerateContent(self, request, context):
        """Run content moderation on function input/output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Lightweight liveness/readiness probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlyMindServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoutingRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutingRecommendation,
                    request_deserializer=flymind__pb2.RoutingRequest.FromString,
                    response_serializer=flymind__pb2.RoutingRecommendation.SerializeToString,
            ),
            'ReportExecutionOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportExecutionOutcome,
                    request_deserializer=flymind__pb2.ExecutionOutcome.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ShouldPrewarm': grpc.unary_unary_rpc_method_handler(
                    servicer.ShouldPrewarm,
                    request_deserializer=flymind__pb2.PrewarmQuery.FromString,
                    response_serializer=flymind__pb2.PrewarmDecision.SerializeToString,
            ),
            'GetCacheKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheKey,
                    request_deserializer=flymind__pb2.CacheQuery.FromString,
                    response_serializer=flymind__pb2.CacheDecision.SerializeToString,
            ),
            'ModerateContent': grpc.unary_unary_rpc_method_handler(
                    servicer.ModerateContent,
                    request_deserializer=flymind__pb2.ModerationRequest.FromString,
                    response_serializer=flymind__pb2.ModerationResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=flymind__pb2.HealthCheckRequest.FromString,
                    response_serializer=flymind__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flymind.FlyMindService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flymind.FlyMindService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlyMindService(object):
    """=============================================================================
    Service Definitions
    =============================================================================

    """

    @staticmethod
    def GetRoutingRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flymind.FlyMindService/GetRoutingRecommendation',
            flymind__pb2.RoutingRequest.SerializeToString,
            flymind__pb2.RoutingRecommendation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportExecutionOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flymind.FlyMindService/ReportExecutionOutcome',
            flymind__pb2.ExecutionOutcome.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShouldPrewarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flymind.FlyMindService/ShouldPrewarm',
            flymind__pb2.PrewarmQuery.SerializeToString,
            flymind__pb2.PrewarmDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCacheKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flymind.FlyMindService/GetCacheKey',
            flymind__pb2.CacheQuery.SerializeToString,
            flymind__pb2.CacheDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModerateContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flymind.FlyMindService/ModerateContent',
            flymind__pb2.ModerationRequest.SerializeToString,
            flymind__pb2.ModerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flymind.FlyMindService/HealthCheck',
            flymind__pb2.HealthCheckRequest.SerializeToString,
            flymind__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
