// Code generated by mockery. DO NOT EDIT.

package billing

import (
	context "context"

	notification "github.com/functionfly/functionfly/internal/notification"
	mock "github.com/stretchr/testify/mock"
)

// MockDunningNotificationService is an autogenerated mock type for the DunningNotificationService type
type MockDunningNotificationService struct {
	mock.Mock
}

type MockDunningNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDunningNotificationService) EXPECT() *MockDunningNotificationService_Expecter {
	return &MockDunningNotificationService_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, req
func (_m *MockDunningNotificationService) Send(ctx context.Context, req notification.SendRequest) (*notification.Notification, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *notification.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, notification.SendRequest) (*notification.Notification, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, notification.SendRequest) *notification.Notification); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(*notification.Notification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, notification.SendRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDunningNotificationService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDunningNotificationService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - req notification.SendRequest
func (_e *MockDunningNotificationService_Expecter) Send(ctx interface{}, req interface{}) *MockDunningNotificationService_Send_Call {
	return &MockDunningNotificationService_Send_Call{Call: _e.mock.On("Send", ctx, req)}
}

func (_c *MockDunningNotificationService_Send_Call) Run(run func(ctx context.Context, req notification.SendRequest)) *MockDunningNotificationService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(notification.SendRequest))
	})
	return _c
}

func (_c *MockDunningNotificationService_Send_Call) Return(_a0 *notification.Notification, _a1 error) *MockDunningNotificationService_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDunningNotificationService_Send_Call) RunAndReturn(run func(context.Context, notification.SendRequest) (*notification.Notification, error)) *MockDunningNotificationService_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendBillingAlert provides a mock function with given fields: ctx, email, alertType, data
func (_m *MockDunningNotificationService) SendBillingAlert(ctx context.Context, email string, alertType string, data map[string]interface{}) error {
	ret := _m.Called(ctx, email, alertType, data)

	if len(ret) == 0 {
		panic("no return value specified for SendBillingAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, email, alertType, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDunningNotificationService_SendBillingAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBillingAlert'
type MockDunningNotificationService_SendBillingAlert_Call struct {
	*mock.Call
}

// SendBillingAlert is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - alertType string
//   - data map[string]interface{}
func (_e *MockDunningNotificationService_Expecter) SendBillingAlert(ctx interface{}, email interface{}, alertType interface{}, data interface{}) *MockDunningNotificationService_SendBillingAlert_Call {
	return &MockDunningNotificationService_SendBillingAlert_Call{Call: _e.mock.On("SendBillingAlert", ctx, email, alertType, data)}
}

func (_c *MockDunningNotificationService_SendBillingAlert_Call) Run(run func(ctx context.Context, email string, alertType string, data map[string]interface{})) *MockDunningNotificationService_SendBillingAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]interface{}))
	})
	return _c
}

func (_c *MockDunningNotificationService_SendBillingAlert_Call) Return(_a0 error) *MockDunningNotificationService_SendBillingAlert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDunningNotificationService_SendBillingAlert_Call) RunAndReturn(run func(context.Context, string, string, map[string]interface{}) error) *MockDunningNotificationService_SendBillingAlert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDunningNotificationService creates a new instance of MockDunningNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDunningNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDunningNotificationService {
	mock := &MockDunningNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
