package bundler

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/functionfly/functionfly/internal/manifest"
)

// InstallDependencies installs the dependencies specified in the manifest.
// It handles different package managers based on the runtime.
func InstallDependencies(manifest *manifest.Manifest) error {
	if manifest == nil {
		return NewBundlerError("dependency install", "manifest cannot be nil")
	}

	if manifest.Dependencies == nil || len(manifest.Dependencies) == 0 {
		// No dependencies to install
		return nil
	}

	switch {
	case strings.HasPrefix(manifest.Runtime, "node"):
		return installNPMDependencies(manifest.Dependencies)
	case strings.HasPrefix(manifest.Runtime, "python"):
		return installPipDependencies(manifest.Dependencies)
	case manifest.Runtime == "deno":
		// Deno handles dependencies differently - they can be imported directly
		return nil
	default:
		return &RuntimeNotSupportedError{
			Runtime:   manifest.Runtime,
			Supported: []string{"node18", "node20", "python3.11", "deno"},
		}
	}
}

// installNPMDependencies installs Node.js dependencies using npm
func installNPMDependencies(deps map[string]string) error {
	// Check if package.json exists, create if not
	if _, err := os.Stat("package.json"); os.IsNotExist(err) {
		if err := createPackageJSON(deps); err != nil {
			return NewBundlerErrorWithCause("npm install", "failed to create package.json", err)
		}
	}

	// Check if node_modules exists and is up to date
	if needsNPMInstall(deps) {
		fmt.Println("Installing npm dependencies...")
		if err := runCommand("npm", "install"); err != nil {
			return NewDependencyErrorWithCause("npm install", "all", "npm install failed", err)
		}
		fmt.Println("✓ npm dependencies installed")
	} else {
		fmt.Println("✓ npm dependencies already up to date")
	}

	return nil
}

// installPipDependencies installs Python dependencies using pip
func installPipDependencies(deps map[string]string) error {
	// Check if requirements.txt exists, create if not
	if _, err := os.Stat("requirements.txt"); os.IsNotExist(err) {
		if err := createRequirementsTxt(deps); err != nil {
			return NewBundlerErrorWithCause("pip install", "failed to create requirements.txt", err)
		}
	}

	// Check if dependencies are installed
	if needsPipInstall(deps) {
		fmt.Println("Installing pip dependencies...")
		if err := runCommand("pip", "install", "-r", "requirements.txt"); err != nil {
			return NewDependencyErrorWithCause("pip install", "all", "pip install failed", err)
		}
		fmt.Println("✓ pip dependencies installed")
	} else {
		fmt.Println("✓ pip dependencies already up to date")
	}

	return nil
}

// needsNPMInstall checks if npm install is needed by comparing package.json with node_modules
func needsNPMInstall(deps map[string]string) bool {
	// For simplicity, we'll always install if node_modules doesn't exist
	// In a production system, you'd want more sophisticated dependency checking
	if _, err := os.Stat("node_modules"); os.IsNotExist(err) {
		return true
	}

	// Check if package-lock.json exists and is newer than package.json
	packageStat, err := os.Stat("package.json")
	if err != nil {
		return true
	}

	lockStat, err := os.Stat("package-lock.json")
	if err != nil {
		// No lock file, need to install
		return true
	}

	// If package.json is newer than package-lock.json, reinstall
	return packageStat.ModTime().After(lockStat.ModTime())
}

// needsPipInstall checks if pip install is needed
func needsPipInstall(deps map[string]string) bool {
	// For simplicity, check if any of the packages are not installed
	// In a production system, you'd want to check requirements.txt vs installed packages
	for pkg := range deps {
		if !isPythonPackageInstalled(pkg) {
			return true
		}
	}
	return false
}

// isPythonPackageInstalled checks if a Python package is installed
func isPythonPackageInstalled(pkgName string) bool {
	// Use pip show to check if package is installed
	cmd := exec.Command("pip", "show", pkgName)
	cmd.Stdout = nil
	cmd.Stderr = nil
	err := cmd.Run()
	return err == nil
}

// createPackageJSON creates a package.json file from manifest dependencies
func createPackageJSON(deps map[string]string) error {
	content := `{
  "name": "functionfly-function",
  "version": "1.0.0",
  "description": "Generated by FunctionFly bundler",
  "dependencies": {
`

	depsList := make([]string, 0, len(deps))
	for name, version := range deps {
		depsList = append(depsList, fmt.Sprintf(`    "%s": "%s"`, name, version))
	}

	content += strings.Join(depsList, ",\n")
	content += `
  }
}
`

	return os.WriteFile("package.json", []byte(content), 0644)
}

// createRequirementsTxt creates a requirements.txt file from manifest dependencies
func createRequirementsTxt(deps map[string]string) error {
	var lines []string
	for name, version := range deps {
		if version == "" || version == "*" {
			lines = append(lines, name)
		} else {
			lines = append(lines, fmt.Sprintf("%s%s", name, version))
		}
	}

	content := strings.Join(lines, "\n") + "\n"
	return os.WriteFile("requirements.txt", []byte(content), 0644)
}

// runCommand executes a command and returns an error if it fails
func runCommand(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("command failed: %s %s\nOutput: %s\nError: %v",
			name, strings.Join(args, " "), string(output), err)
	}
	return nil
}

// InstallDependenciesWithWorkingDirectory installs dependencies with explicit working directory support
func InstallDependenciesWithWorkingDirectory(manifest *manifest.Manifest, workingDir string) error {
	if manifest == nil {
		return NewBundlerError("dependency install", "manifest cannot be nil")
	}

	// Resolve and validate working directory
	resolvedDir, err := ResolveWorkingDirectory(workingDir)
	if err != nil {
		return NewBundlerErrorWithCause("dependency install", "failed to resolve working directory", err)
	}

	// Execute dependency installation within the specified working directory
	return WithWorkingDirectory(resolvedDir, func() error {
		return InstallDependencies(manifest)
	})
}