// go_toolchain.go centralizes Go toolchain detection and the hardened
// environment used to compile user code to wasip1 WebAssembly.
//
// File name does NOT end in _wasm.go because the Go toolchain treats
// that suffix as GOARCH=wasm-only sources.
package bundler

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
)

// RequiredGoMajor/Minor/Patch define the minimum Go version supported
// by the production Go runtime. Update in lockstep with the runtime
// metadata surfaced via the runtime registry handlers.
const (
	RequiredGoMajor = 1
	RequiredGoMinor = 26
	RequiredGoPatch = 5
)

type goVersion struct {
	Major int
	Minor int
	Patch int
	Raw   string
}

func (v goVersion) String() string {
	return fmt.Sprintf("go%d.%d.%d", v.Major, v.Minor, v.Patch)
}

var goVersionRE = regexp.MustCompile(`go version go(\d+)\.(\d+)(?:\.(\d+))?`)

func parseGoVersion(out string) (goVersion, error) {
	m := goVersionRE.FindStringSubmatch(strings.TrimSpace(out))
	if m == nil {
		return goVersion{}, fmt.Errorf("could not parse Go version from %q", out)
	}
	major, _ := strconv.Atoi(m[1])
	minor, _ := strconv.Atoi(m[2])
	patch := 0
	if m[3] != "" {
		patch, _ = strconv.Atoi(m[3])
	}
	return goVersion{Major: major, Minor: minor, Patch: patch, Raw: out}, nil
}

func requireGoVersion() error {
	path, err := exec.LookPath("go")
	if err != nil {
		return fmt.Errorf("go runtime requires the Go toolchain on PATH; install Go %d.%d.%d+ from https://go.dev/dl/: %w",
			RequiredGoMajor, RequiredGoMinor, RequiredGoPatch, err)
	}
	out, err := exec.Command(path, "version").Output()
	if err != nil {
		return fmt.Errorf("go runtime: failed to execute `go version`: %w", err)
	}
	v, err := parseGoVersion(string(out))
	if err != nil {
		return fmt.Errorf("go runtime: %w", err)
	}
	if v.Major != RequiredGoMajor {
		return fmt.Errorf("go runtime requires Go %d.x; found %s", RequiredGoMajor, v)
	}
	if v.Minor < RequiredGoMinor {
		return fmt.Errorf("go runtime requires Go %d.%d.%d+; found %s",
			RequiredGoMajor, RequiredGoMinor, RequiredGoPatch, v)
	}
	if v.Minor == RequiredGoMinor && v.Patch < RequiredGoPatch {
		return fmt.Errorf("go runtime requires Go %d.%d.%d+; found %s",
			RequiredGoMajor, RequiredGoMinor, RequiredGoPatch, v)
	}
	return nil
}

func GoToolchainVersion() (goVersion, error) {
	path, err := exec.LookPath("go")
	if err != nil {
		return goVersion{}, err
	}
	out, err := exec.Command(path, "version").Output()
	if err != nil {
		return goVersion{}, err
	}
	return parseGoVersion(string(out))
}

func goWasip1Env() []string {
	var out []string
	for _, e := range os.Environ() {
		if strings.HasPrefix(e, "GOOS=") ||
			strings.HasPrefix(e, "GOARCH=") ||
			strings.HasPrefix(e, "CGO_ENABLED=") ||
			strings.HasPrefix(e, "GOTOOLCHAIN=") {
			continue
		}
		out = append(out, e)
	}
	return append(out,
		"GOOS=wasip1",
		"GOARCH=wasm",
		"CGO_ENABLED=0",
		"GOTOOLCHAIN=local+auto",
		"GOPROXY=https://proxy.golang.org,direct",
		"GOSUMDB=sum.golang.org",
	)
}

const generatedGoMod = "module functionflyfn\n\ngo 1.26\n"

const goWrapperSource = `package main

// Code below is generated by FunctionFly's Go bundler. It reads input
// from the host-managed directory and writes the structured response
// envelope. Do not edit; the file is regenerated on every bundle.

import (
	"encoding/json"
	"fmt"
	"os"
)

type ffResponse struct {
	Success bool        ` + "`json:\"success\"`" + `
	Result  interface{} ` + "`json:\"result,omitempty\"`" + `
	Error   string      ` + "`json:\"error,omitempty\"`" + `
}

const (
	ffInputPath  = "/functionfly/input.json"
	ffOutputPath = "/functionfly/output.json"
)

func ffRun() {
	in, err := os.ReadFile(ffInputPath)
	if err != nil {
		ffWriteError("read input: " + err.Error())
		os.Exit(1)
	}

	out, runErr := Handler(json.RawMessage(in))
	resp := ffResponse{Success: runErr == nil, Result: out}
	if runErr != nil {
		resp.Error = runErr.Error()
	}

	payload, err := json.Marshal(resp)
	if err != nil {
		ffWriteError("marshal response: " + err.Error())
		os.Exit(1)
	}
	if err := os.WriteFile(ffOutputPath, payload, 0o600); err != nil {
		ffWriteError("write output: " + err.Error())
		os.Exit(1)
	}
}

func ffWriteError(msg string) {
	resp := ffResponse{Success: false, Error: msg}
	payload, _ := json.Marshal(resp)
	_ = os.WriteFile(ffOutputPath, payload, 0o600)
	fmt.Fprintln(os.Stderr, "functionfly:", msg)
}

func main() {
	ffRun()
}
`
